// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntArrayDeque } from "./bigint-array-deque.js";

describe("BigIntArrayDeque generated", () => {
  it("addFirst and addLast", () => {
    const d = new BigIntArrayDeque();
    d.addFirst(1n);
    d.addLast(2n);
    expect(d.size).toBe(2);
    expect(d.peekFirst()).toBe(1n);
    expect(d.peekLast()).toBe(2n);
  });

  it("of", () => {
    const d = BigIntArrayDeque.of([1n, 2n, 3n]);
    expect(d.size).toBe(3);
    expect(d.peekFirst()).toBe(1n);
    expect(d.peekLast()).toBe(3n);
  });

  it("removeFirst and removeLast", () => {
    const d = BigIntArrayDeque.of([1n, 2n, 3n]);
    const first = d.removeFirst();
    expect(first).toBe(1n);
    expect(d.size).toBe(2);
    const last = d.removeLast();
    expect(last).toBe(3n);
    expect(d.size).toBe(1);
  });

  it("peekFirst and peekLast", () => {
    const d = BigIntArrayDeque.of([1n, 2n]);
    expect(d.peekFirst()).toBe(1n);
    expect(d.peekLast()).toBe(2n);
  });

  it("peekFirst on empty returns undefined", () => {
    const d = new BigIntArrayDeque();
    expect(d.peekFirst()).toBeUndefined();
    expect(d.peekLast()).toBeUndefined();
  });

  it("isEmpty and clear", () => {
    const d = new BigIntArrayDeque();
    expect(d.isEmpty).toBe(true);
    d.addLast(1n);
    expect(d.isEmpty).toBe(false);
    d.clear();
    expect(d.size).toBe(0);
    expect(d.isEmpty).toBe(true);
  });

  it("contains", () => {
    const d = BigIntArrayDeque.of([1n, 2n, 3n]);
    expect(d.contains(2n)).toBe(true);
    expect(d.contains(99n)).toBe(false);
  });

  it("anySatisfy and allSatisfy", () => {
    const d = BigIntArrayDeque.of([1n, 2n, 3n]);
    expect(d.anySatisfy((x) => x === 2n)).toBe(true);
    expect(d.anySatisfy((x) => x === 99n)).toBe(false);
    expect(d.allSatisfy((x) => x > 0n)).toBe(true);
  });

  it("forEach", () => {
    const d = BigIntArrayDeque.of([1n, 2n, 3n]);
    const acc: bigint[] = [];
    d.forEach((x) => acc.push(x));
    expect(acc).toEqual([1n, 2n, 3n]);
  });

  it("toArray", () => {
    const d = BigIntArrayDeque.of([1n, 2n, 3n]);
    expect(d.toArray()).toEqual([1n, 2n, 3n]);
  });

  it("equals", () => {
    const d1 = BigIntArrayDeque.of([1n, 2n, 3n]);
    const d2 = BigIntArrayDeque.of([1n, 2n, 3n]);
    const d3 = BigIntArrayDeque.of([1n, 2n]);
    expect(d1.equals(d2)).toBe(true);
    expect(d1.equals(d3)).toBe(false);
  });

  it("toString", () => {
    const d = BigIntArrayDeque.of([1n, 2n]);
    expect(d.toString()).toBe("[1, 2]");
  });

  it("Symbol.iterator", () => {
    const d = BigIntArrayDeque.of([1n, 2n, 3n]);
    expect([...d]).toEqual([1n, 2n, 3n]);
  });

  it("large deque operations", () => {
    const d = new BigIntArrayDeque();
    for (let i = 0; i < 1000; i++) {
      d.addLast(i);
    }
    expect(d.size).toBe(1000);
    expect(d.peekFirst()).toBe(0);
    expect(d.peekLast()).toBe(999);
  });
});
