// Code generated by mapdb-codegen. DO NOT EDIT.
import { BigIntArrayDeque } from "./bigint-array-deque.js";

/**
 * Immutable double-ended queue for bigint values.
 * Wraps a mutable BigIntArrayDeque, exposing only read-only operations.
 * Persistent operations (withFirst/withLast/withoutFirst/withoutLast) return new immutable deques.
 */
export class ImmutableBigIntArrayDeque {
  private readonly delegate: BigIntArrayDeque;

  constructor(source: BigIntArrayDeque) {
    // Copy all entries into a fresh mutable deque so the caller cannot mutate our data.
    this.delegate = new BigIntArrayDeque();
    for (const v of source.entries()) {
      this.delegate.addLast(v);
    }
  }

  /** Creates an immutable deque from an array of values in front-to-back order. */
  static of(values: bigint[]): ImmutableBigIntArrayDeque {
    return new ImmutableBigIntArrayDeque(BigIntArrayDeque.of(values));
  }

  /** Returns the front element without removing it. Returns undefined if empty. */
  peekFirst(): bigint | undefined {
    return this.delegate.peekFirst();
  }

  /** Returns the back element without removing it. Returns undefined if empty. */
  peekLast(): bigint | undefined {
    return this.delegate.peekLast();
  }

  /** Returns the number of elements. */
  get size(): number {
    return this.delegate.size;
  }

  /** Returns true if the deque has no elements. */
  get isEmpty(): boolean {
    return this.delegate.isEmpty;
  }

  /** Returns true if the deque contains the given value. */
  contains(value: bigint): boolean {
    return this.delegate.contains(value);
  }

  /** Yields all elements in front-to-back order. */
  *entries(): Generator<bigint> {
    yield* this.delegate.entries();
  }

  /** Calls the function for each element, front to back. */
  forEach(fn: (value: bigint) => void): void {
    this.delegate.forEach(fn);
  }

  /** Returns true if any element satisfies the predicate. */
  anySatisfy(predicate: (value: bigint) => boolean): boolean {
    return this.delegate.anySatisfy(predicate);
  }

  /** Returns true if every element satisfies the predicate. */
  allSatisfy(predicate: (value: bigint) => boolean): boolean {
    return this.delegate.allSatisfy(predicate);
  }

  /** Returns an array of elements in front-to-back order. */
  toArray(): bigint[] {
    return this.delegate.toArray();
  }

  /** Returns a new immutable deque with the value prepended at the front. O(n). */
  withFirst(value: bigint): ImmutableBigIntArrayDeque {
    const copy = this.toMutable();
    copy.addFirst(value);
    return new ImmutableBigIntArrayDeque(copy);
  }

  /** Returns a new immutable deque with the value appended at the back. O(1) amortized. */
  withLast(value: bigint): ImmutableBigIntArrayDeque {
    const copy = this.toMutable();
    copy.addLast(value);
    return new ImmutableBigIntArrayDeque(copy);
  }

  /** Returns a new deque without the front element, and the removed value. Returns undefined if empty. O(n). */
  withoutFirst():
    | { deque: ImmutableBigIntArrayDeque; value: bigint }
    | undefined {
    if (this.delegate.isEmpty) return undefined;
    const copy = this.toMutable();
    const value = copy.removeFirst()!;
    return { deque: new ImmutableBigIntArrayDeque(copy), value };
  }

  /** Returns a new deque without the back element, and the removed value. Returns undefined if empty. O(1). */
  withoutLast():
    | { deque: ImmutableBigIntArrayDeque; value: bigint }
    | undefined {
    if (this.delegate.isEmpty) return undefined;
    const copy = this.toMutable();
    const value = copy.removeLast()!;
    return { deque: new ImmutableBigIntArrayDeque(copy), value };
  }

  /** Returns true if both deques have the same elements in the same order. */
  equals(other: ImmutableBigIntArrayDeque): boolean {
    return this.delegate.equals(other.delegate);
  }

  /** Returns a string representation, front-to-back. */
  toString(): string {
    return this.delegate.toString();
  }

  /** Makes the deque iterable with for-of loops. Yields front to back. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    yield* this.delegate[Symbol.iterator]();
  }

  /** Returns a new mutable copy of this deque. */
  toMutable(): BigIntArrayDeque {
    return BigIntArrayDeque.of(this.delegate.toArray());
  }
}
