// Code generated by mapdb-codegen. DO NOT EDIT.

/**
 * Array-backed double-ended queue for number values.
 * Back operations (addLast/removeLast) are O(1) amortized.
 * Front operations (addFirst/removeFirst) are O(n).
 */
export class NumberArrayDeque {
  private data: number[];

  constructor() {
    this.data = [];
  }

  /** Creates a new deque from the given values in front-to-back order. */
  static of(values: number[]): NumberArrayDeque {
    const d = new NumberArrayDeque();
    for (const v of values) d.addLast(v);
    return d;
  }

  /** Adds a value to the front of the deque. O(n). */
  addFirst(value: number): void {
    this.data.unshift(value);
  }

  /** Adds a value to the back of the deque. O(1) amortized. */
  addLast(value: number): void {
    this.data.push(value);
  }

  /** Removes and returns the front element, or undefined if empty. O(n). */
  removeFirst(): number | undefined {
    return this.data.shift();
  }

  /** Removes and returns the back element, or undefined if empty. O(1). */
  removeLast(): number | undefined {
    return this.data.pop();
  }

  /** Returns the front element without removing it, or undefined if empty. */
  peekFirst(): number | undefined {
    return this.data.length === 0 ? undefined : this.data[0];
  }

  /** Returns the back element without removing it, or undefined if empty. */
  peekLast(): number | undefined {
    return this.data.length === 0 ? undefined : this.data[this.data.length - 1];
  }

  /** Returns the number of elements. */
  get size(): number {
    return this.data.length;
  }

  /** Returns true if the deque has no elements. */
  get isEmpty(): boolean {
    return this.data.length === 0;
  }

  /** Removes all elements. */
  clear(): void {
    this.data.length = 0;
  }

  /** Returns true if the deque contains the given value. */
  contains(value: number): boolean {
    for (let i = 0; i < this.data.length; i++) {
      if (this.data[i] === value) return true;
    }
    return false;
  }

  /** Calls the function for each element, front to back. */
  forEach(fn: (value: number) => void): void {
    for (let i = 0; i < this.data.length; i++) fn(this.data[i]);
  }

  /** Returns true if any element satisfies the predicate. */
  anySatisfy(predicate: (value: number) => boolean): boolean {
    for (let i = 0; i < this.data.length; i++) {
      if (predicate(this.data[i])) return true;
    }
    return false;
  }

  /** Returns true if every element satisfies the predicate. */
  allSatisfy(predicate: (value: number) => boolean): boolean {
    for (let i = 0; i < this.data.length; i++) {
      if (!predicate(this.data[i])) return false;
    }
    return true;
  }

  /** Returns an array of elements in front-to-back order. */
  toArray(): number[] {
    return this.data.slice();
  }

  /** Yields values from front to back. Alias for [Symbol.iterator]. */
  *entries(): Generator<number> {
    for (let i = 0; i < this.data.length; i++) yield this.data[i];
  }

  /** Returns true if the other deque has the same elements in the same order. */
  equals(other: NumberArrayDeque): boolean {
    if (this.data.length !== other.data.length) return false;
    for (let i = 0; i < this.data.length; i++) {
      if (this.data[i] !== other.data[i]) return false;
    }
    return true;
  }

  /** Returns a string representation, front-to-back. */
  toString(): string {
    return `[${this.data.join(", ")}]`;
  }

  /** Yields values from front to back. */
  *[Symbol.iterator](): Generator<number> {
    for (let i = 0; i < this.data.length; i++) yield this.data[i];
  }
}
