// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberArrayDeque } from "./number-array-deque.js";

describe("NumberArrayDeque generated", () => {
  it("addFirst and addLast", () => {
    const d = new NumberArrayDeque();
    d.addFirst(1);
    d.addLast(2);
    expect(d.size).toBe(2);
    expect(d.peekFirst()).toBe(1);
    expect(d.peekLast()).toBe(2);
  });

  it("of", () => {
    const d = NumberArrayDeque.of([1, 2, 3]);
    expect(d.size).toBe(3);
    expect(d.peekFirst()).toBe(1);
    expect(d.peekLast()).toBe(3);
  });

  it("removeFirst and removeLast", () => {
    const d = NumberArrayDeque.of([1, 2, 3]);
    const first = d.removeFirst();
    expect(first).toBe(1);
    expect(d.size).toBe(2);
    const last = d.removeLast();
    expect(last).toBe(3);
    expect(d.size).toBe(1);
  });

  it("peekFirst and peekLast", () => {
    const d = NumberArrayDeque.of([1, 2]);
    expect(d.peekFirst()).toBe(1);
    expect(d.peekLast()).toBe(2);
  });

  it("peekFirst on empty returns undefined", () => {
    const d = new NumberArrayDeque();
    expect(d.peekFirst()).toBeUndefined();
    expect(d.peekLast()).toBeUndefined();
  });

  it("isEmpty and clear", () => {
    const d = new NumberArrayDeque();
    expect(d.isEmpty).toBe(true);
    d.addLast(1);
    expect(d.isEmpty).toBe(false);
    d.clear();
    expect(d.size).toBe(0);
    expect(d.isEmpty).toBe(true);
  });

  it("contains", () => {
    const d = NumberArrayDeque.of([1, 2, 3]);
    expect(d.contains(2)).toBe(true);
    expect(d.contains(99)).toBe(false);
  });

  it("anySatisfy and allSatisfy", () => {
    const d = NumberArrayDeque.of([1, 2, 3]);
    expect(d.anySatisfy((x) => x === 2)).toBe(true);
    expect(d.anySatisfy((x) => x === 99)).toBe(false);
    expect(d.allSatisfy((x) => x > 0)).toBe(true);
  });

  it("forEach", () => {
    const d = NumberArrayDeque.of([1, 2, 3]);
    const acc: number[] = [];
    d.forEach((x) => acc.push(x));
    expect(acc).toEqual([1, 2, 3]);
  });

  it("toArray", () => {
    const d = NumberArrayDeque.of([1, 2, 3]);
    expect(d.toArray()).toEqual([1, 2, 3]);
  });

  it("equals", () => {
    const d1 = NumberArrayDeque.of([1, 2, 3]);
    const d2 = NumberArrayDeque.of([1, 2, 3]);
    const d3 = NumberArrayDeque.of([1, 2]);
    expect(d1.equals(d2)).toBe(true);
    expect(d1.equals(d3)).toBe(false);
  });

  it("toString", () => {
    const d = NumberArrayDeque.of([1, 2]);
    expect(d.toString()).toBe("[1, 2]");
  });

  it("Symbol.iterator", () => {
    const d = NumberArrayDeque.of([1, 2, 3]);
    expect([...d]).toEqual([1, 2, 3]);
  });

  it("large deque operations", () => {
    const d = new NumberArrayDeque();
    for (let i = 0; i < 1000; i++) {
      d.addLast(i);
    }
    expect(d.size).toBe(1000);
    expect(d.peekFirst()).toBe(0);
    expect(d.peekLast()).toBe(999);
  });
});
