// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbMutableSet } from "../api/index";

const DEFAULT_CAPACITY = 16;
const LOAD_FACTOR = 0.75;

/**
 * Open-addressing hash set for bigint values.
 * Uses a bitmap (occupied array) to track which slots contain data.
 */
export class BigIntHashSet implements MapDbMutableSet<bigint> {
  private data: bigint[];
  private occupied: boolean[];
  private _size: number;

  constructor(capacity: number = DEFAULT_CAPACITY) {
    const cap = nextPowerOfTwo(capacity);
    this.data = new Array<bigint>(cap).fill(0n);
    this.occupied = new Array<boolean>(cap).fill(false);
    this._size = 0;
  }

  /** Creates a new set from an array of values. */
  static of(values: bigint[]): BigIntHashSet {
    const set = new BigIntHashSet(values.length * 2);
    for (const v of values) {
      set.add(v);
    }
    return set;
  }

  /** Adds a value to the set. Returns true if the value was added (not already present). */
  add(value: bigint): boolean {
    if (this.needsResize()) {
      this.resize();
    }
    const cap = this.data.length;
    const mask = cap - 1;
    let idx = this.hash(value) & mask;

    while (true) {
      if (!this.occupied[idx]) {
        this.data[idx] = value;
        this.occupied[idx] = true;
        this._size++;
        return true;
      }
      if (Object.is(this.data[idx], value)) {
        return false;
      }
      idx = (idx + 1) & mask;
    }
  }

  /** Removes a value from the set. Returns true if the value was present. */
  remove(value: bigint): boolean {
    const cap = this.data.length;
    if (cap === 0) return false;
    const mask = cap - 1;
    let idx = this.hash(value) & mask;

    while (true) {
      if (!this.occupied[idx]) return false;
      if (Object.is(this.data[idx], value)) {
        this.occupied[idx] = false;
        this.data[idx] = 0n;
        this._size--;
        this.rehashFrom(idx, mask);
        return true;
      }
      idx = (idx + 1) & mask;
    }
  }

  /** Returns true if the set contains the given value. */
  contains(value: bigint): boolean {
    const cap = this.data.length;
    if (cap === 0) return false;
    const mask = cap - 1;
    let idx = this.hash(value) & mask;

    while (true) {
      if (!this.occupied[idx]) return false;
      if (Object.is(this.data[idx], value)) return true;
      idx = (idx + 1) & mask;
    }
  }

  /** Returns the number of elements. */
  size(): number {
    return this._size;
  }

  /** Returns true if the set is empty. */
  isEmpty(): boolean {
    return this._size === 0;
  }

  /** Removes all elements. */
  clear(): void {
    this.data.fill(0n);
    this.occupied.fill(false);
    this._size = 0;
  }

  /** Returns a new set that is the union of this set and the other. */
  union(other: BigIntHashSet): BigIntHashSet {
    const result = new BigIntHashSet((this._size + other._size) * 2);
    for (const v of this.values()) {
      result.add(v);
    }
    for (const v of other.values()) {
      result.add(v);
    }
    return result;
  }

  /** Returns a new set that is the intersection of this set and the other. */
  intersect(other: BigIntHashSet): BigIntHashSet {
    const result = new BigIntHashSet();
    for (const v of this.values()) {
      if (other.contains(v)) {
        result.add(v);
      }
    }
    return result;
  }

  /** Returns a new set with elements in this set but not in the other. */
  difference(other: BigIntHashSet): BigIntHashSet {
    const result = new BigIntHashSet();
    for (const v of this.values()) {
      if (!other.contains(v)) {
        result.add(v);
      }
    }
    return result;
  }

  /** Returns a new set with elements satisfying the predicate. */
  select(predicate: (value: bigint) => boolean): BigIntHashSet {
    const result = new BigIntHashSet();
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && predicate(this.data[i])) {
        result.add(this.data[i]);
      }
    }
    return result;
  }

  /** Returns a new set with elements NOT satisfying the predicate. */
  reject(predicate: (value: bigint) => boolean): BigIntHashSet {
    const result = new BigIntHashSet();
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && !predicate(this.data[i])) {
        result.add(this.data[i]);
      }
    }
    return result;
  }

  /** Calls the function for each element. */
  forEach(f: (value: bigint) => void): void {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) {
        f(this.data[i]);
      }
    }
  }

  /** Returns a new array with the results of calling `f` on each element. */
  map<U>(f: (value: bigint) => U): U[] {
    const result: U[] = [];
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) result.push(f(this.data[i]));
    }
    return result;
  }

  /** Returns a new array with elements satisfying the predicate. */
  filter(predicate: (value: bigint) => boolean): bigint[] {
    const result: bigint[] = [];
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && predicate(this.data[i]))
        result.push(this.data[i]);
    }
    return result;
  }

  /** Returns the first element satisfying the predicate, or undefined. */
  find(predicate: (value: bigint) => boolean): bigint | undefined {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && predicate(this.data[i])) return this.data[i];
    }
    return undefined;
  }

  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: bigint) => boolean): boolean {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && !predicate(this.data[i])) return false;
    }
    return true;
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: bigint) => boolean): boolean {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && predicate(this.data[i])) return true;
    }
    return false;
  }

  /** Reduces the set to a single value using the accumulator function. */
  reduce<U>(f: (acc: U, value: bigint) => U, initial: U): U {
    let acc = initial;
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) acc = f(acc, this.data[i]);
    }
    return acc;
  }

  /** Returns true if the set contains the value. Alias for `contains`. */
  includes(value: bigint): boolean {
    return this.contains(value);
  }

  /** Makes the set iterable with for-of loops. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) yield this.data[i];
    }
  }

  /** Yields all values. */
  *values(): Generator<bigint> {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) {
        yield this.data[i];
      }
    }
  }

  /** Returns all values as a plain array. */
  toArray(): bigint[] {
    const result: bigint[] = [];
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) result.push(this.data[i]);
    }
    return result;
  }

  /** Returns a string representation. */
  toString(): string {
    const parts: string[] = [];
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) {
        parts.push(`${this.data[i]}`);
      }
    }
    return `{${parts.join(", ")}}`;
  }

  private hash(value: bigint): number {
    let h = Number(value & 0xffffffffn);
    h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
    h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
    h = (h >> 16) ^ h;
    return h < 0 ? -h : h;
  }

  private needsResize(): boolean {
    return this._size + 1 > this.data.length * LOAD_FACTOR;
  }

  private resize(): void {
    const oldData = this.data;
    const oldOccupied = this.occupied;
    const newCap = oldData.length * 2;
    this.data = new Array<bigint>(newCap).fill(0n);
    this.occupied = new Array<boolean>(newCap).fill(false);
    this._size = 0;
    for (let i = 0; i < oldOccupied.length; i++) {
      if (oldOccupied[i]) {
        this.add(oldData[i]);
      }
    }
  }

  private rehashFrom(deleted: number, mask: number): void {
    const cap = this.data.length;
    let idx = (deleted + 1) & mask;
    while (this.occupied[idx]) {
      const ideal = this.hash(this.data[idx]) & mask;
      const distCurrent = (idx - ideal + cap) & mask;
      const distGap = (deleted - ideal + cap) & mask;
      if (distCurrent > distGap) {
        this.data[deleted] = this.data[idx];
        this.occupied[deleted] = true;
        this.occupied[idx] = false;
        this.data[idx] = 0n;
        deleted = idx;
      }
      idx = (idx + 1) & mask;
      if (idx === deleted) break;
    }
  }
}

function nextPowerOfTwo(n: number): number {
  if (n <= 0) return 16;
  n--;
  n |= n >> 1;
  n |= n >> 2;
  n |= n >> 4;
  n |= n >> 8;
  n |= n >> 16;
  n++;
  return n;
}
