// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbSet } from "../api/index";
import { BigIntHashSet } from "./bigint-hash-set.js";

/**
 * Immutable hash set for bigint values.
 * Wraps a mutable BigIntHashSet, exposing only read-only operations.
 */
export class ImmutableBigIntHashSet implements MapDbSet<bigint> {
  private readonly delegate: BigIntHashSet;

  constructor(source: BigIntHashSet) {
    // Copy all entries into a fresh mutable set so the caller cannot mutate our data.
    this.delegate = new BigIntHashSet();
    for (const v of source.values()) {
      this.delegate.add(v);
    }
  }

  /** Creates an immutable set from an array of values. */
  static of(values: bigint[]): ImmutableBigIntHashSet {
    return new ImmutableBigIntHashSet(BigIntHashSet.of(values));
  }

  /** Returns true if the set contains the given value. */
  contains(value: bigint): boolean {
    return this.delegate.contains(value);
  }

  /** Returns the number of elements. */
  size(): number {
    return this.delegate.size();
  }

  /** Returns true if the set is empty. */
  isEmpty(): boolean {
    return this.delegate.isEmpty();
  }

  /** Yields all values. */
  *values(): Generator<bigint> {
    yield* this.delegate.values();
  }

  /** Calls the function for each element. */
  forEach(f: (value: bigint) => void): void {
    this.delegate.forEach(f);
  }

  /** Returns a new array with the results of calling `f` on each element. */
  map<U>(f: (value: bigint) => U): U[] {
    return this.delegate.map(f);
  }

  /** Returns a new array with elements satisfying the predicate. */
  filter(predicate: (value: bigint) => boolean): bigint[] {
    return this.delegate.filter(predicate);
  }

  /** Returns the first element satisfying the predicate, or undefined. */
  find(predicate: (value: bigint) => boolean): bigint | undefined {
    return this.delegate.find(predicate);
  }

  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: bigint) => boolean): boolean {
    return this.delegate.every(predicate);
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: bigint) => boolean): boolean {
    return this.delegate.some(predicate);
  }

  /** Reduces the set to a single value using the accumulator function. */
  reduce<U>(f: (acc: U, value: bigint) => U, initial: U): U {
    return this.delegate.reduce(f, initial);
  }

  /** Returns true if the set contains the value. Alias for `contains`. */
  includes(value: bigint): boolean {
    return this.delegate.includes(value);
  }

  /** Makes the set iterable with for-of loops. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    yield* this.delegate[Symbol.iterator]();
  }

  /** Returns a new immutable set with elements satisfying the predicate. */
  select(predicate: (value: bigint) => boolean): ImmutableBigIntHashSet {
    return new ImmutableBigIntHashSet(this.delegate.select(predicate));
  }

  /** Returns a new immutable set with elements NOT satisfying the predicate. */
  reject(predicate: (value: bigint) => boolean): ImmutableBigIntHashSet {
    return new ImmutableBigIntHashSet(this.delegate.reject(predicate));
  }

  /** Returns a new immutable set that is the union of this set and the other. */
  union(other: ImmutableBigIntHashSet): ImmutableBigIntHashSet {
    const result = this.toMutable();
    for (const v of other.values()) {
      result.add(v);
    }
    return new ImmutableBigIntHashSet(result);
  }

  /** Returns a new immutable set that is the intersection of this set and the other. */
  intersect(other: ImmutableBigIntHashSet): ImmutableBigIntHashSet {
    const result = new BigIntHashSet();
    for (const v of this.delegate.values()) {
      if (other.contains(v)) {
        result.add(v);
      }
    }
    return new ImmutableBigIntHashSet(result);
  }

  /** Returns a new immutable set with elements in this set but not in the other. */
  difference(other: ImmutableBigIntHashSet): ImmutableBigIntHashSet {
    const result = new BigIntHashSet();
    for (const v of this.delegate.values()) {
      if (!other.contains(v)) {
        result.add(v);
      }
    }
    return new ImmutableBigIntHashSet(result);
  }

  /** Returns all values as a plain array. */
  toArray(): bigint[] {
    return this.delegate.toArray();
  }

  /** Returns a new mutable copy of this set. */
  toMutable(): BigIntHashSet {
    return BigIntHashSet.of(this.delegate.toArray());
  }

  /** Returns a string representation. */
  toString(): string {
    return this.delegate.toString();
  }
}
