// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberHashSet } from "./number-hash-set.js";

describe("NumberHashSet generated", () => {
  it("add and contains", () => {
    const s = new NumberHashSet();
    s.add(1);
    s.add(2);
    s.add(3);
    expect(s.size()).toBe(3);
    expect(s.contains(2)).toBe(true);
    expect(s.contains(99)).toBe(false);
  });
  it("add duplicate", () => {
    const s = new NumberHashSet();
    expect(s.add(1)).toBe(true);
    expect(s.add(1)).toBe(false);
    expect(s.size()).toBe(1);
  });
  it("of", () => {
    const s = NumberHashSet.of([1, 2, 3]);
    expect(s.size()).toBe(3);
  });
  it("remove", () => {
    const s = NumberHashSet.of([1, 2, 3]);
    expect(s.remove(2)).toBe(true);
    expect(s.contains(2)).toBe(false);
    expect(s.remove(99)).toBe(false);
  });
  it("clear and isEmpty", () => {
    const s = NumberHashSet.of([1]);
    s.clear();
    expect(s.isEmpty()).toBe(true);
  });
  it("select and reject", () => {
    const s = NumberHashSet.of([1, 2, 3, 4, 5]);
    expect(s.select((v) => v > 3).size()).toBe(2);
    expect(s.reject((v) => v > 3).size()).toBe(3);
  });
  it("union", () => {
    const a = NumberHashSet.of([1, 2, 3]);
    const b = NumberHashSet.of([3, 4, 5]);
    expect(a.union(b).size()).toBe(5);
  });
  it("intersect", () => {
    const a = NumberHashSet.of([1, 2, 3]);
    const b = NumberHashSet.of([2, 3, 4]);
    expect(a.intersect(b).size()).toBe(2);
  });
  it("difference", () => {
    const a = NumberHashSet.of([1, 2, 3]);
    const b = NumberHashSet.of([2, 3, 4]);
    expect(a.difference(b).size()).toBe(1);
  });
  it("entries generator", () => {
    const s = NumberHashSet.of([1, 2]);
    expect([...s.values()].length).toBe(2);
  });
  it("toArray", () => {
    const s = NumberHashSet.of([1, 2]);
    expect(s.toArray().length).toBe(2);
  });
  it("toString", () => {
    const s = NumberHashSet.of([1]);
    expect(s.toString()).not.toBe("");
  });

  describe("IEEE 754 edge cases", () => {
    it("NaN is findable", () => {
      const s = new NumberHashSet();
      s.add(NaN);
      expect(s.contains(NaN)).toBe(true);
      expect(s.size()).toBe(1);
    });
    it("NaN add duplicate does not grow", () => {
      const s = new NumberHashSet();
      expect(s.add(NaN)).toBe(true);
      expect(s.add(NaN)).toBe(false);
      expect(s.add(NaN)).toBe(false);
      expect(s.size()).toBe(1);
    });
    it("NaN remove works", () => {
      const s = new NumberHashSet();
      s.add(NaN);
      expect(s.remove(NaN)).toBe(true);
      expect(s.contains(NaN)).toBe(false);
      expect(s.size()).toBe(0);
    });
    it("-0.0 is distinct from +0.0", () => {
      const s = new NumberHashSet();
      s.add(0.0);
      s.add(-0.0);
      expect(s.size()).toBe(2);
      expect(s.contains(0.0)).toBe(true);
      expect(s.contains(-0.0)).toBe(true);
    });
    it("+/-Infinity are distinct elements", () => {
      const s = new NumberHashSet();
      s.add(Number.POSITIVE_INFINITY);
      s.add(Number.NEGATIVE_INFINITY);
      expect(s.size()).toBe(2);
      expect(s.contains(Number.POSITIVE_INFINITY)).toBe(true);
      expect(s.contains(Number.NEGATIVE_INFINITY)).toBe(true);
    });
  });
});
