// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntBigIntTreeMap } from "./bigint-bigint-tree-map.js";

describe("BigIntBigIntTreeMap generated", () => {
  it("put and get", () => {
    const m = new BigIntBigIntTreeMap();
    m.put(3n, 3n);
    m.put(1n, 1n);
    m.put(2n, 2n);
    expect(m.size()).toBe(3);
    expect(m.get(2n)).toBe(2n);
    expect(m.get(99n)).toBeUndefined();
  });
  it("remove", () => {
    const m = new BigIntBigIntTreeMap();
    m.put(1n, 1n);
    m.put(2n, 2n);
    expect(m.remove(1n)).toBe(1n);
    expect(m.size()).toBe(1);
  });
  it("min and max", () => {
    const m = new BigIntBigIntTreeMap();
    m.put(3n, 3n);
    m.put(1n, 1n);
    expect(m.min()?.[0]).toBe(1n);
    expect(m.max()?.[0]).toBe(3n);
  });
  it("sorted iteration", () => {
    const m = new BigIntBigIntTreeMap();
    m.put(3n, 3n);
    m.put(1n, 1n);
    m.put(2n, 2n);
    const keys = [...m.keys()];
    for (let i = 1; i < keys.length; i++) {
      expect(keys[i] >= keys[i - 1]).toBe(true);
    }
  });
  it("clear", () => {
    const m = new BigIntBigIntTreeMap();
    m.put(1n, 1n);
    m.clear();
    expect(m.isEmpty()).toBe(true);
  });
  it("select", () => {
    const m = new BigIntBigIntTreeMap();
    m.put(1n, 1n);
    m.put(2n, 2n);
    m.put(3n, 3n);
    expect(m.select((_k, v) => v > 1n).size()).toBe(2);
  });
  it("toString", () => {
    const m = new BigIntBigIntTreeMap();
    m.put(1n, 1n);
    expect(m.toString()).not.toBe("");
  });
});
