// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbMutableMap } from "../api/index";

const RED = false;
const BLACK = true;

interface NumberBigIntTreeMapNode {
  key: number;
  value: bigint;
  left: NumberBigIntTreeMapNode | null;
  right: NumberBigIntTreeMapNode | null;
  parent: NumberBigIntTreeMapNode | null;
  color: boolean;
}

/**
 * Sorted map with number keys and bigint values, backed by a red-black tree.
 * Keys are maintained in ascending order.
 */
export class NumberBigIntTreeMap implements MapDbMutableMap<number, bigint> {
  private root: NumberBigIntTreeMapNode | null = null;
  private _size = 0;

  /** Inserts or updates. Returns previous value or undefined. */
  put(key: number, value: bigint): bigint | undefined {
    if (this.root === null) {
      this.root = {
        key,
        value,
        left: null,
        right: null,
        parent: null,
        color: BLACK,
      };
      this._size++;
      return undefined;
    }
    let node = this.root;
    while (true) {
      if (key < node.key) {
        if (node.left === null) {
          node.left = {
            key,
            value,
            left: null,
            right: null,
            parent: node,
            color: RED,
          };
          this.fixAfterInsert(node.left);
          this._size++;
          return undefined;
        }
        node = node.left;
      } else if (key > node.key) {
        if (node.right === null) {
          node.right = {
            key,
            value,
            left: null,
            right: null,
            parent: node,
            color: RED,
          };
          this.fixAfterInsert(node.right);
          this._size++;
          return undefined;
        }
        node = node.right;
      } else {
        const old = node.value;
        node.value = value;
        return old;
      }
    }
  }

  get(key: number): bigint | undefined {
    const node = this.findNode(key);
    return node ? node.value : undefined;
  }

  getOrDefault(key: number, defaultValue: bigint): bigint {
    const v = this.get(key);
    return v !== undefined ? v : defaultValue;
  }

  containsKey(key: number): boolean {
    return this.findNode(key) !== null;
  }

  remove(key: number): bigint | undefined {
    const node = this.findNode(key);
    if (!node) return undefined;
    const old = node.value;
    this.deleteNode(node);
    this._size--;
    return old;
  }

  size(): number {
    return this._size;
  }
  isEmpty(): boolean {
    return this._size === 0;
  }
  clear(): void {
    this.root = null;
    this._size = 0;
  }

  min(): [number, bigint] | undefined {
    if (!this.root) return undefined;
    const n = this.minNode(this.root);
    return [n.key, n.value];
  }

  max(): [number, bigint] | undefined {
    if (!this.root) return undefined;
    const n = this.maxNode(this.root);
    return [n.key, n.value];
  }

  floor(key: number): [number, bigint] | undefined {
    let result: NumberBigIntTreeMapNode | null = null;
    let node = this.root;
    while (node) {
      if (key === node.key) return [node.key, node.value];
      if (key > node.key) {
        result = node;
        node = node.right;
      } else node = node.left;
    }
    return result ? [result.key, result.value] : undefined;
  }

  ceiling(key: number): [number, bigint] | undefined {
    let result: NumberBigIntTreeMapNode | null = null;
    let node = this.root;
    while (node) {
      if (key === node.key) return [node.key, node.value];
      if (key < node.key) {
        result = node;
        node = node.left;
      } else node = node.right;
    }
    return result ? [result.key, result.value] : undefined;
  }

  /** Yields entries in ascending key order. */
  *entries(): Generator<[number, bigint]> {
    function* inorder(
      node: NumberBigIntTreeMapNode | null,
    ): Generator<[number, bigint]> {
      if (!node) return;
      yield* inorder(node.left);
      yield [node.key, node.value];
      yield* inorder(node.right);
    }
    yield* inorder(this.root);
  }

  *keys(): Generator<number> {
    for (const [k] of this.entries()) yield k;
  }

  *values(): Generator<bigint> {
    for (const [, v] of this.entries()) yield v;
  }

  /** Yields entries with keys in [fromKey, toKey). */
  *rangeKeys(fromKey: number, toKey: number): Generator<[number, bigint]> {
    for (const [k, v] of this.entries()) {
      if (k < fromKey) continue;
      if (k >= toKey) return;
      yield [k, v];
    }
  }

  forEach(f: (key: number, value: bigint) => void): void {
    for (const [k, v] of this.entries()) f(k, v);
  }

  select(
    predicate: (key: number, value: bigint) => boolean,
  ): NumberBigIntTreeMap {
    const result = new NumberBigIntTreeMap();
    for (const [k, v] of this.entries()) {
      if (predicate(k, v)) result.put(k, v);
    }
    return result;
  }

  toString(): string {
    const parts: string[] = [];
    for (const [k, v] of this.entries()) parts.push(`${k}: ${v}`);
    return `{${parts.join(", ")}}`;
  }

  // --- Red-black tree internals ---

  private findNode(key: number): NumberBigIntTreeMapNode | null {
    let node = this.root;
    while (node) {
      if (key < node.key) node = node.left;
      else if (key > node.key) node = node.right;
      else return node;
    }
    return null;
  }

  private minNode(node: NumberBigIntTreeMapNode): NumberBigIntTreeMapNode {
    while (node.left) node = node.left;
    return node;
  }

  private maxNode(node: NumberBigIntTreeMapNode): NumberBigIntTreeMapNode {
    while (node.right) node = node.right;
    return node;
  }

  private rotateLeft(x: NumberBigIntTreeMapNode): void {
    const y = x.right!;
    x.right = y.left;
    if (y.left) y.left.parent = x;
    y.parent = x.parent;
    if (!x.parent) this.root = y;
    else if (x === x.parent.left) x.parent.left = y;
    else x.parent.right = y;
    y.left = x;
    x.parent = y;
  }

  private rotateRight(x: NumberBigIntTreeMapNode): void {
    const y = x.left!;
    x.left = y.right;
    if (y.right) y.right.parent = x;
    y.parent = x.parent;
    if (!x.parent) this.root = y;
    else if (x === x.parent.right) x.parent.right = y;
    else x.parent.left = y;
    y.right = x;
    x.parent = y;
  }

  private fixAfterInsert(z: NumberBigIntTreeMapNode): void {
    while (z.parent && z.parent.color === RED) {
      if (z.parent === z.parent.parent!.left) {
        const y = z.parent.parent!.right;
        if (y && y.color === RED) {
          z.parent.color = BLACK;
          y.color = BLACK;
          z.parent.parent!.color = RED;
          z = z.parent.parent!;
        } else {
          if (z === z.parent.right) {
            z = z.parent;
            this.rotateLeft(z);
          }
          z.parent!.color = BLACK;
          z.parent!.parent!.color = RED;
          this.rotateRight(z.parent!.parent!);
        }
      } else {
        const y = z.parent.parent!.left;
        if (y && y.color === RED) {
          z.parent.color = BLACK;
          y.color = BLACK;
          z.parent.parent!.color = RED;
          z = z.parent.parent!;
        } else {
          if (z === z.parent.left) {
            z = z.parent;
            this.rotateRight(z);
          }
          z.parent!.color = BLACK;
          z.parent!.parent!.color = RED;
          this.rotateLeft(z.parent!.parent!);
        }
      }
    }
    this.root!.color = BLACK;
  }

  private deleteNode(z: NumberBigIntTreeMapNode): void {
    if (z.left && z.right) {
      const succ = this.minNode(z.right);
      z.key = succ.key;
      z.value = succ.value;
      z = succ;
    }
    const child = z.left ?? z.right;
    if (child) {
      child.parent = z.parent;
      if (!z.parent) this.root = child;
      else if (z === z.parent.left) z.parent.left = child;
      else z.parent.right = child;
      if (z.color === BLACK) this.fixAfterDelete(child);
    } else if (!z.parent) {
      this.root = null;
    } else {
      if (z.color === BLACK) this.fixAfterDelete(z);
      if (z.parent) {
        if (z === z.parent.left) z.parent.left = null;
        else z.parent.right = null;
      }
    }
  }

  private fixAfterDelete(x: NumberBigIntTreeMapNode): void {
    while (x !== this.root && x.color === BLACK) {
      if (x === x.parent!.left) {
        let w = x.parent!.right;
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (w.color === RED) {
          w.color = BLACK;
          x.parent!.color = RED;
          this.rotateLeft(x.parent!);
          w = x.parent!.right;
        }
        if (!w) {
          x = x.parent!;
          continue;
        }
        const lb = !w.left || w.left.color === BLACK;
        const rb = !w.right || w.right.color === BLACK;
        if (lb && rb) {
          w.color = RED;
          x = x.parent!;
        } else {
          if (rb) {
            if (w.left) w.left.color = BLACK;
            w.color = RED;
            this.rotateRight(w);
            w = x.parent!.right!;
          }
          w.color = x.parent!.color;
          x.parent!.color = BLACK;
          if (w.right) w.right.color = BLACK;
          this.rotateLeft(x.parent!);
          x = this.root!;
        }
      } else {
        let w = x.parent!.left;
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (w.color === RED) {
          w.color = BLACK;
          x.parent!.color = RED;
          this.rotateRight(x.parent!);
          w = x.parent!.left;
        }
        if (!w) {
          x = x.parent!;
          continue;
        }
        const lb = !w.left || w.left.color === BLACK;
        const rb = !w.right || w.right.color === BLACK;
        if (lb && rb) {
          w.color = RED;
          x = x.parent!;
        } else {
          if (lb) {
            if (w.right) w.right.color = BLACK;
            w.color = RED;
            this.rotateLeft(w);
            w = x.parent!.left!;
          }
          w.color = x.parent!.color;
          x.parent!.color = BLACK;
          if (w.left) w.left.color = BLACK;
          this.rotateRight(x.parent!);
          x = this.root!;
        }
      }
    }
    x.color = BLACK;
  }
}
