// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberNumberTreeMap } from "./number-number-tree-map.js";

describe("NumberNumberTreeMap generated", () => {
  it("put and get", () => {
    const m = new NumberNumberTreeMap();
    m.put(3, 3);
    m.put(1, 1);
    m.put(2, 2);
    expect(m.size()).toBe(3);
    expect(m.get(2)).toBe(2);
    expect(m.get(99)).toBeUndefined();
  });
  it("remove", () => {
    const m = new NumberNumberTreeMap();
    m.put(1, 1);
    m.put(2, 2);
    expect(m.remove(1)).toBe(1);
    expect(m.size()).toBe(1);
  });
  it("min and max", () => {
    const m = new NumberNumberTreeMap();
    m.put(3, 3);
    m.put(1, 1);
    expect(m.min()?.[0]).toBe(1);
    expect(m.max()?.[0]).toBe(3);
  });
  it("sorted iteration", () => {
    const m = new NumberNumberTreeMap();
    m.put(3, 3);
    m.put(1, 1);
    m.put(2, 2);
    const keys = [...m.keys()];
    for (let i = 1; i < keys.length; i++) {
      expect(keys[i] >= keys[i - 1]).toBe(true);
    }
  });
  it("clear", () => {
    const m = new NumberNumberTreeMap();
    m.put(1, 1);
    m.clear();
    expect(m.isEmpty()).toBe(true);
  });
  it("select", () => {
    const m = new NumberNumberTreeMap();
    m.put(1, 1);
    m.put(2, 2);
    m.put(3, 3);
    expect(m.select((_k, v) => v > 1).size()).toBe(2);
  });
  it("toString", () => {
    const m = new NumberNumberTreeMap();
    m.put(1, 1);
    expect(m.toString()).not.toBe("");
  });
});
