// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntNumberHashMap } from "./bigint-number-hash-map.js";

describe("BigIntNumberHashMap generated", () => {
  it("put and get", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    m.put(3n, 3);
    expect(m.get(1n)).toBe(1);
    expect(m.get(99n)).toBeUndefined();
    expect(m.size()).toBe(3);
  });
  it("put overwrite", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    const old = m.put(1n, 2);
    expect(old).toBe(1);
    expect(m.get(1n)).toBe(2);
  });
  it("remove", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    const old = m.remove(1n);
    expect(old).toBe(1);
    expect(m.size()).toBe(1);
    expect(m.containsKey(1n)).toBe(false);
  });
  it("containsKey", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    expect(m.containsKey(1n)).toBe(true);
    expect(m.containsKey(99n)).toBe(false);
  });
  it("getOrDefault", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    expect(m.getOrDefault(1n, 3)).toBe(1);
    expect(m.getOrDefault(99n, 3)).toBe(3);
  });
  it("clear and isEmpty", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    expect(m.isEmpty()).toBe(false);
    m.clear();
    expect(m.isEmpty()).toBe(true);
  });
  it("select and reject", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    m.put(3n, 3);
    expect(m.select((_k, v) => v > 1).size()).toBe(2);
    expect(m.reject((_k, v) => v > 1).size()).toBe(1);
  });
  it("entries generator", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    expect([...m.entries()].length).toBe(2);
  });
  it("keysToArray and valuesToArray", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    expect(m.keysToArray().length).toBe(2);
    expect(m.valuesToArray().length).toBe(2);
  });
  it("injectInto", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    const sum = m.injectInto(0, (acc, _k, v) => acc + v);
    expect(sum).toBe(1 + 2);
  });
  it("resize", () => {
    const m = new BigIntNumberHashMap();
    for (let i = 0n; i < 100n; i += 1n) m.put(i, Number(i) * 10);
    expect(m.size()).toBe(100);
  });
  it("toString", () => {
    const m = new BigIntNumberHashMap();
    m.put(1n, 1);
    expect(m.toString()).not.toBe("");
  });
});
