// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbMutableMap } from "../api/index";

const DEFAULT_CAPACITY = 16;
const LOAD_FACTOR = 0.75;

/**
 * Open-addressing hash map with bigint keys and number values.
 * Uses a bitmap (occupied array) to track which slots contain data.
 */
export class BigIntNumberHashMap implements MapDbMutableMap<bigint, number> {
  private keys: bigint[];
  private values: number[];
  private occupied: boolean[];
  private _size: number;

  constructor(capacity: number = DEFAULT_CAPACITY) {
    const cap = nextPowerOfTwo(capacity);
    this.keys = new Array<bigint>(cap).fill(0n);
    this.values = new Array<number>(cap).fill(0);
    this.occupied = new Array<boolean>(cap).fill(false);
    this._size = 0;
  }

  /** Creates a new map from key-value pairs: [[k1, v1], [k2, v2], ...] */
  static of(pairs: [bigint, number][]): BigIntNumberHashMap {
    const m = new BigIntNumberHashMap(pairs.length * 2);
    for (const [k, v] of pairs) {
      m.put(k, v);
    }
    return m;
  }

  /** Inserts or updates a key-value pair. Returns the previous value or undefined. */
  put(key: bigint, value: number): number | undefined {
    if (this.needsResize()) {
      this.resize();
    }
    const cap = this.keys.length;
    const mask = cap - 1;
    let idx = this.hashKey(key) & mask;

    while (true) {
      if (!this.occupied[idx]) {
        this.keys[idx] = key;
        this.values[idx] = value;
        this.occupied[idx] = true;
        this._size++;
        return undefined;
      }
      if (Object.is(this.keys[idx], key)) {
        const old = this.values[idx];
        this.values[idx] = value;
        return old;
      }
      idx = (idx + 1) & mask;
    }
  }

  /** Returns the value for the key, or undefined if not found. */
  get(key: bigint): number | undefined {
    const cap = this.keys.length;
    if (cap === 0) return undefined;
    const mask = cap - 1;
    let idx = this.hashKey(key) & mask;

    while (true) {
      if (!this.occupied[idx]) return undefined;
      if (Object.is(this.keys[idx], key)) return this.values[idx];
      idx = (idx + 1) & mask;
    }
  }

  /** Returns the value for the key, or the default value if not found. */
  getOrDefault(key: bigint, defaultValue: number): number {
    const v = this.get(key);
    return v !== undefined ? v : defaultValue;
  }

  /** Removes the entry for the key. Returns the previous value or undefined. */
  remove(key: bigint): number | undefined {
    const cap = this.keys.length;
    if (cap === 0) return undefined;
    const mask = cap - 1;
    let idx = this.hashKey(key) & mask;

    while (true) {
      if (!this.occupied[idx]) return undefined;
      if (Object.is(this.keys[idx], key)) {
        const old = this.values[idx];
        this.occupied[idx] = false;
        this.keys[idx] = 0n;
        this.values[idx] = 0;
        this._size--;
        this.rehashFrom(idx, mask);
        return old;
      }
      idx = (idx + 1) & mask;
    }
  }

  /** Returns true if the map contains the key. */
  containsKey(key: bigint): boolean {
    return this.get(key) !== undefined;
  }

  /** Returns the number of entries. */
  size(): number {
    return this._size;
  }

  /** Returns true if the map is empty. */
  isEmpty(): boolean {
    return this._size === 0;
  }

  /** Removes all entries. */
  clear(): void {
    this.keys.fill(0n);
    this.values.fill(0);
    this.occupied.fill(false);
    this._size = 0;
  }

  /** Yields all key-value pairs as [key, value] tuples. */
  *entries(): Generator<[bigint, number]> {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) {
        yield [this.keys[i], this.values[i]];
      }
    }
  }

  /** Yields all keys. */
  *keysIter(): Generator<bigint> {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) {
        yield this.keys[i];
      }
    }
  }

  /** Yields all values. */
  *valuesIter(): Generator<number> {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) {
        yield this.values[i];
      }
    }
  }

  /** Calls the function for each key-value pair. */
  forEach(f: (key: bigint, value: number) => void): void {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) {
        f(this.keys[i], this.values[i]);
      }
    }
  }

  /** Returns a new map with entries satisfying the predicate. */
  select(
    predicate: (key: bigint, value: number) => boolean,
  ): BigIntNumberHashMap {
    const result = new BigIntNumberHashMap();
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && predicate(this.keys[i], this.values[i])) {
        result.put(this.keys[i], this.values[i]);
      }
    }
    return result;
  }

  /** Returns a new map with entries NOT satisfying the predicate. */
  reject(
    predicate: (key: bigint, value: number) => boolean,
  ): BigIntNumberHashMap {
    const result = new BigIntNumberHashMap();
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && !predicate(this.keys[i], this.values[i])) {
        result.put(this.keys[i], this.values[i]);
      }
    }
    return result;
  }

  /** Returns true if any entry satisfies the predicate. */
  anySatisfy(predicate: (key: bigint, value: number) => boolean): boolean {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && predicate(this.keys[i], this.values[i])) {
        return true;
      }
    }
    return false;
  }

  /** Returns true if all entries satisfy the predicate. */
  allSatisfy(predicate: (key: bigint, value: number) => boolean): boolean {
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i] && !predicate(this.keys[i], this.values[i])) {
        return false;
      }
    }
    return true;
  }

  /** Performs a left fold over all entries. */
  injectInto<R>(initial: R, f: (acc: R, key: bigint, value: number) => R): R {
    let result = initial;
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) {
        result = f(result, this.keys[i], this.values[i]);
      }
    }
    return result;
  }

  /** Returns all keys as an array. */
  keysToArray(): bigint[] {
    const result: bigint[] = [];
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) result.push(this.keys[i]);
    }
    return result;
  }

  /** Returns all values as an array. */
  valuesToArray(): number[] {
    const result: number[] = [];
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) result.push(this.values[i]);
    }
    return result;
  }

  /** Adds amount to the value for the key. If absent, inserts amount. Returns new value. */
  addToValue(key: bigint, amount: number): number {
    const existing = this.get(key);
    const newVal =
      existing !== undefined ? ((existing + amount) as number) : amount;
    this.put(key, newVal);
    return newVal;
  }

  /** Updates the value for the key. If absent, applies f to initialValue. Returns new value. */
  updateValue(
    key: bigint,
    initialValue: number,
    f: (value: number) => number,
  ): number {
    const existing = this.get(key);
    const newVal = f(existing !== undefined ? existing : initialValue);
    this.put(key, newVal);
    return newVal;
  }

  /** Fluent put. Returns this for chaining. */
  withKeyValue(key: bigint, value: number): this {
    this.put(key, value);
    return this;
  }

  /** Fluent remove. Returns this for chaining. */
  withoutKey(key: bigint): this {
    this.remove(key);
    return this;
  }

  /** Returns a string representation. */
  toString(): string {
    const parts: string[] = [];
    for (let i = 0; i < this.occupied.length; i++) {
      if (this.occupied[i]) {
        parts.push(`${this.keys[i]}: ${this.values[i]}`);
      }
    }
    return `{${parts.join(", ")}}`;
  }

  private hashKey(key: bigint): number {
    let h = Number(key & 0xffffffffn);
    h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
    h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
    h = (h >> 16) ^ h;
    return h < 0 ? -h : h;
  }

  private needsResize(): boolean {
    return this._size + 1 > this.keys.length * LOAD_FACTOR;
  }

  private resize(): void {
    const oldKeys = this.keys;
    const oldValues = this.values;
    const oldOccupied = this.occupied;
    const newCap = oldKeys.length * 2;
    this.keys = new Array<bigint>(newCap).fill(0n);
    this.values = new Array<number>(newCap).fill(0);
    this.occupied = new Array<boolean>(newCap).fill(false);
    this._size = 0;
    for (let i = 0; i < oldOccupied.length; i++) {
      if (oldOccupied[i]) {
        this.put(oldKeys[i], oldValues[i]);
      }
    }
  }

  private rehashFrom(deleted: number, mask: number): void {
    const cap = this.keys.length;
    let idx = (deleted + 1) & mask;
    while (this.occupied[idx]) {
      const ideal = this.hashKey(this.keys[idx]) & mask;
      const distCurrent = (idx - ideal + cap) & mask;
      const distGap = (deleted - ideal + cap) & mask;
      if (distCurrent > distGap) {
        this.keys[deleted] = this.keys[idx];
        this.values[deleted] = this.values[idx];
        this.occupied[deleted] = true;
        this.occupied[idx] = false;
        this.keys[idx] = 0n;
        this.values[idx] = 0;
        deleted = idx;
      }
      idx = (idx + 1) & mask;
      if (idx === deleted) break;
    }
  }
}

function nextPowerOfTwo(n: number): number {
  if (n <= 0) return 16;
  n--;
  n |= n >> 1;
  n |= n >> 2;
  n |= n >> 4;
  n |= n >> 8;
  n |= n >> 16;
  n++;
  return n;
}
