// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntBigIntHashMap } from "./bigint-bigint-hash-map.js";

describe("BigIntBigIntHashMap generated", () => {
  it("put and get", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    m.put(2n, 2n);
    m.put(3n, 3n);
    expect(m.get(1n)).toBe(1n);
    expect(m.get(99n)).toBeUndefined();
    expect(m.size()).toBe(3);
  });
  it("put overwrite", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    const old = m.put(1n, 2n);
    expect(old).toBe(1n);
    expect(m.get(1n)).toBe(2n);
  });
  it("remove", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    m.put(2n, 2n);
    const old = m.remove(1n);
    expect(old).toBe(1n);
    expect(m.size()).toBe(1);
    expect(m.containsKey(1n)).toBe(false);
  });
  it("containsKey", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    expect(m.containsKey(1n)).toBe(true);
    expect(m.containsKey(99n)).toBe(false);
  });
  it("getOrDefault", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    expect(m.getOrDefault(1n, 3n)).toBe(1n);
    expect(m.getOrDefault(99n, 3n)).toBe(3n);
  });
  it("clear and isEmpty", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    expect(m.isEmpty()).toBe(false);
    m.clear();
    expect(m.isEmpty()).toBe(true);
  });
  it("select and reject", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    m.put(2n, 2n);
    m.put(3n, 3n);
    expect(m.select((_k, v) => v > 1n).size()).toBe(2);
    expect(m.reject((_k, v) => v > 1n).size()).toBe(1);
  });
  it("entries generator", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    m.put(2n, 2n);
    expect([...m.entries()].length).toBe(2);
  });
  it("keysToArray and valuesToArray", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    m.put(2n, 2n);
    expect(m.keysToArray().length).toBe(2);
    expect(m.valuesToArray().length).toBe(2);
  });
  it("injectInto", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    m.put(2n, 2n);
    const sum = m.injectInto(0n, (acc, _k, v) => acc + v);
    expect(sum).toBe(1n + 2n);
  });
  it("resize", () => {
    const m = new BigIntBigIntHashMap();
    for (let i = 0n; i < 100n; i += 1n) m.put(i, i * 10n);
    expect(m.size()).toBe(100);
  });
  it("toString", () => {
    const m = new BigIntBigIntHashMap();
    m.put(1n, 1n);
    expect(m.toString()).not.toBe("");
  });
});
