// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntBigIntHashMap } from "./bigint-bigint-hash-map.js";
import { ImmutableBigIntBigIntHashMap } from "./immutable-bigint-bigint-hash-map.js";

describe("ImmutableBigIntBigIntHashMap generated", () => {
  it("get and size", () => {
    const im = ImmutableBigIntBigIntHashMap.of([
      [1n, 1n],
      [2n, 2n],
    ]);
    expect(im.size()).toBe(2);
    expect(im.get(1n)).toBe(1n);
    expect(im.get(99n)).toBeUndefined();
  });
  it("containsKey", () => {
    const im = ImmutableBigIntBigIntHashMap.of([[1n, 1n]]);
    expect(im.containsKey(1n)).toBe(true);
    expect(im.containsKey(99n)).toBe(false);
  });
  it("select", () => {
    const im = ImmutableBigIntBigIntHashMap.of([
      [1n, 1n],
      [2n, 2n],
      [3n, 3n],
    ]);
    expect(im.select((_k, v) => v > 1n).size()).toBe(2);
  });
  it("toMutable does not affect immutable", () => {
    const im = ImmutableBigIntBigIntHashMap.of([[1n, 1n]]);
    im.toMutable().put(2n, 2n);
    expect(im.size()).toBe(1);
  });
});
