// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbMap } from "../api/index";
import { BigIntBigIntHashMap } from "./bigint-bigint-hash-map.js";

/**
 * Immutable hash map with bigint keys and bigint values.
 * Wraps a mutable BigIntBigIntHashMap, exposing only read-only operations.
 */
export class ImmutableBigIntBigIntHashMap implements MapDbMap<bigint, bigint> {
  private readonly delegate: BigIntBigIntHashMap;

  constructor(source: BigIntBigIntHashMap) {
    // Copy all entries into a fresh mutable map so the caller cannot mutate our data.
    this.delegate = new BigIntBigIntHashMap();
    for (const [k, v] of source.entries()) {
      this.delegate.put(k, v);
    }
  }

  /** Creates an immutable map from key-value pairs: [[k1, v1], [k2, v2], ...] */
  static of(pairs: [bigint, bigint][]): ImmutableBigIntBigIntHashMap {
    const m = new BigIntBigIntHashMap(pairs.length * 2);
    for (const [k, v] of pairs) {
      m.put(k, v);
    }
    return new ImmutableBigIntBigIntHashMap(m);
  }

  /** Returns the value for the key, or undefined if not found. */
  get(key: bigint): bigint | undefined {
    return this.delegate.get(key);
  }

  /** Returns the value for the key, or the default value if not found. */
  getOrDefault(key: bigint, defaultValue: bigint): bigint {
    return this.delegate.getOrDefault(key, defaultValue);
  }

  /** Returns true if the map contains the key. */
  containsKey(key: bigint): boolean {
    return this.delegate.containsKey(key);
  }

  /** Returns the number of entries. */
  size(): number {
    return this.delegate.size();
  }

  /** Returns true if the map is empty. */
  isEmpty(): boolean {
    return this.delegate.isEmpty();
  }

  /** Yields all key-value pairs as [key, value] tuples. */
  *entries(): Generator<[bigint, bigint]> {
    yield* this.delegate.entries();
  }

  /** Yields all keys. */
  *keysIter(): Generator<bigint> {
    yield* this.delegate.keysIter();
  }

  /** Yields all values. */
  *valuesIter(): Generator<bigint> {
    yield* this.delegate.valuesIter();
  }

  /** Calls the function for each key-value pair. */
  forEach(f: (key: bigint, value: bigint) => void): void {
    this.delegate.forEach(f);
  }

  /** Returns a new immutable map with entries satisfying the predicate. */
  select(
    predicate: (key: bigint, value: bigint) => boolean,
  ): ImmutableBigIntBigIntHashMap {
    return new ImmutableBigIntBigIntHashMap(this.delegate.select(predicate));
  }

  /** Returns a new immutable map with entries NOT satisfying the predicate. */
  reject(
    predicate: (key: bigint, value: bigint) => boolean,
  ): ImmutableBigIntBigIntHashMap {
    return new ImmutableBigIntBigIntHashMap(this.delegate.reject(predicate));
  }

  /** Returns true if any entry satisfies the predicate. */
  anySatisfy(predicate: (key: bigint, value: bigint) => boolean): boolean {
    return this.delegate.anySatisfy(predicate);
  }

  /** Returns true if all entries satisfy the predicate. */
  allSatisfy(predicate: (key: bigint, value: bigint) => boolean): boolean {
    return this.delegate.allSatisfy(predicate);
  }

  /** Performs a left fold over all entries. */
  injectInto<R>(initial: R, f: (acc: R, key: bigint, value: bigint) => R): R {
    return this.delegate.injectInto(initial, f);
  }

  /** Returns all keys as an array. */
  keysToArray(): bigint[] {
    return this.delegate.keysToArray();
  }

  /** Returns all values as an array. */
  valuesToArray(): bigint[] {
    return this.delegate.valuesToArray();
  }

  /** Returns a new mutable copy of this map. */
  toMutable(): BigIntBigIntHashMap {
    const m = new BigIntBigIntHashMap();
    for (const [k, v] of this.delegate.entries()) {
      m.put(k, v);
    }
    return m;
  }

  /** Returns a string representation. */
  toString(): string {
    return this.delegate.toString();
  }
}
