// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberBigIntHashMap } from "./number-bigint-hash-map.js";
import { ImmutableNumberBigIntHashMap } from "./immutable-number-bigint-hash-map.js";

describe("ImmutableNumberBigIntHashMap generated", () => {
  it("get and size", () => {
    const im = ImmutableNumberBigIntHashMap.of([
      [1, 1n],
      [2, 2n],
    ]);
    expect(im.size()).toBe(2);
    expect(im.get(1)).toBe(1n);
    expect(im.get(99)).toBeUndefined();
  });
  it("containsKey", () => {
    const im = ImmutableNumberBigIntHashMap.of([[1, 1n]]);
    expect(im.containsKey(1)).toBe(true);
    expect(im.containsKey(99)).toBe(false);
  });
  it("select", () => {
    const im = ImmutableNumberBigIntHashMap.of([
      [1, 1n],
      [2, 2n],
      [3, 3n],
    ]);
    expect(im.select((_k, v) => v > 1n).size()).toBe(2);
  });
  it("toMutable does not affect immutable", () => {
    const im = ImmutableNumberBigIntHashMap.of([[1, 1n]]);
    im.toMutable().put(2, 2n);
    expect(im.size()).toBe(1);
  });
});
