// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberNumberHashMap } from "./number-number-hash-map.js";
import { ImmutableNumberNumberHashMap } from "./immutable-number-number-hash-map.js";

describe("ImmutableNumberNumberHashMap generated", () => {
  it("get and size", () => {
    const im = ImmutableNumberNumberHashMap.of([
      [1, 1],
      [2, 2],
    ]);
    expect(im.size()).toBe(2);
    expect(im.get(1)).toBe(1);
    expect(im.get(99)).toBeUndefined();
  });
  it("containsKey", () => {
    const im = ImmutableNumberNumberHashMap.of([[1, 1]]);
    expect(im.containsKey(1)).toBe(true);
    expect(im.containsKey(99)).toBe(false);
  });
  it("select", () => {
    const im = ImmutableNumberNumberHashMap.of([
      [1, 1],
      [2, 2],
      [3, 3],
    ]);
    expect(im.select((_k, v) => v > 1).size()).toBe(2);
  });
  it("toMutable does not affect immutable", () => {
    const im = ImmutableNumberNumberHashMap.of([[1, 1]]);
    im.toMutable().put(2, 2);
    expect(im.size()).toBe(1);
  });
});
