// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberBigIntHashMap } from "./number-bigint-hash-map.js";

describe("NumberBigIntHashMap generated", () => {
  it("put and get", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    m.put(3, 3n);
    expect(m.get(1)).toBe(1n);
    expect(m.get(99)).toBeUndefined();
    expect(m.size()).toBe(3);
  });
  it("put overwrite", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    const old = m.put(1, 2n);
    expect(old).toBe(1n);
    expect(m.get(1)).toBe(2n);
  });
  it("remove", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    const old = m.remove(1);
    expect(old).toBe(1n);
    expect(m.size()).toBe(1);
    expect(m.containsKey(1)).toBe(false);
  });
  it("containsKey", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    expect(m.containsKey(1)).toBe(true);
    expect(m.containsKey(99)).toBe(false);
  });
  it("getOrDefault", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    expect(m.getOrDefault(1, 3n)).toBe(1n);
    expect(m.getOrDefault(99, 3n)).toBe(3n);
  });
  it("clear and isEmpty", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    expect(m.isEmpty()).toBe(false);
    m.clear();
    expect(m.isEmpty()).toBe(true);
  });
  it("select and reject", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    m.put(3, 3n);
    expect(m.select((_k, v) => v > 1n).size()).toBe(2);
    expect(m.reject((_k, v) => v > 1n).size()).toBe(1);
  });
  it("entries generator", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    expect([...m.entries()].length).toBe(2);
  });
  it("keysToArray and valuesToArray", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    expect(m.keysToArray().length).toBe(2);
    expect(m.valuesToArray().length).toBe(2);
  });
  it("injectInto", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    const sum = m.injectInto(0n, (acc, _k, v) => acc + v);
    expect(sum).toBe(1n + 2n);
  });
  it("resize", () => {
    const m = new NumberBigIntHashMap();
    for (let i = 0; i < 100; i += 1) m.put(i, BigInt(i) * 10n);
    expect(m.size()).toBe(100);
  });
  it("toString", () => {
    const m = new NumberBigIntHashMap();
    m.put(1, 1n);
    expect(m.toString()).not.toBe("");
  });

  describe("IEEE 754 edge cases", () => {
    it("NaN key is findable", () => {
      const m = new NumberBigIntHashMap();
      m.put(NaN, 1n);
      expect(m.containsKey(NaN)).toBe(true);
      expect(m.get(NaN)).toBe(1n);
      expect(m.size()).toBe(1);
    });
    it("NaN key replaces, does not duplicate", () => {
      const m = new NumberBigIntHashMap();
      m.put(NaN, 1n);
      m.put(NaN, 2n);
      m.put(NaN, 3n);
      expect(m.size()).toBe(1);
      expect(m.get(NaN)).toBe(3n);
    });
    it("NaN key remove works", () => {
      const m = new NumberBigIntHashMap();
      m.put(NaN, 1n);
      const removed = m.remove(NaN);
      expect(removed).toBe(1n);
      expect(m.size()).toBe(0);
      expect(m.containsKey(NaN)).toBe(false);
    });
    it("-0.0 is distinct from +0.0", () => {
      const m = new NumberBigIntHashMap();
      m.put(0.0, 1n);
      m.put(-0.0, 2n);
      expect(m.size()).toBe(2);
      expect(m.get(0.0)).toBe(1n);
      expect(m.get(-0.0)).toBe(2n);
    });
    it("+/-Infinity keys", () => {
      const m = new NumberBigIntHashMap();
      m.put(Number.POSITIVE_INFINITY, 1n);
      m.put(Number.NEGATIVE_INFINITY, 2n);
      expect(m.size()).toBe(2);
      expect(m.get(Number.POSITIVE_INFINITY)).toBe(1n);
      expect(m.get(Number.NEGATIVE_INFINITY)).toBe(2n);
    });
  });
});
