// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbMutableMap } from "../api/index";

/**
 * Hash map with generic object keys and bigint values.
 * Uses the built-in Map<K, bigint> internally.
 */
export class ObjectBigIntHashMap<K> implements MapDbMutableMap<K, bigint> {
  private readonly map: Map<K, bigint>;

  constructor() {
    this.map = new Map<K, bigint>();
  }

  /** Creates a new map from key-value pairs: [[k1, v1], [k2, v2], ...] */
  static of<K>(pairs: [K, bigint][]): ObjectBigIntHashMap<K> {
    const m = new ObjectBigIntHashMap<K>();
    for (const [k, v] of pairs) {
      m.put(k, v);
    }
    return m;
  }

  /** Inserts or updates a key-value pair. Returns the previous value or undefined. */
  put(key: K, value: bigint): bigint | undefined {
    const old = this.map.get(key);
    this.map.set(key, value);
    return old;
  }

  /** Returns the value for the key, or undefined if not found. */
  get(key: K): bigint | undefined {
    return this.map.get(key);
  }

  /** Returns the value for the key, or the default value if not found. */
  getOrDefault(key: K, defaultValue: bigint): bigint {
    const v = this.map.get(key);
    return v !== undefined ? v : defaultValue;
  }

  /** Removes the entry for the key. Returns the previous value or undefined. */
  remove(key: K): bigint | undefined {
    const old = this.map.get(key);
    this.map.delete(key);
    return old;
  }

  /** Returns true if the map contains the key. */
  containsKey(key: K): boolean {
    return this.map.has(key);
  }

  /** Returns the number of entries. */
  size(): number {
    return this.map.size;
  }

  /** Returns true if the map is empty. */
  isEmpty(): boolean {
    return this.map.size === 0;
  }

  /** Removes all entries. */
  clear(): void {
    this.map.clear();
  }

  /** Yields all key-value pairs as [key, value] tuples. */
  *entries(): Generator<[K, bigint]> {
    for (const entry of this.map) {
      yield entry;
    }
  }

  /** Calls the function for each key-value pair. */
  forEach(f: (key: K, value: bigint) => void): void {
    for (const [k, v] of this.map) {
      f(k, v);
    }
  }

  /** Returns a new map with entries satisfying the predicate. */
  select(
    predicate: (key: K, value: bigint) => boolean,
  ): ObjectBigIntHashMap<K> {
    const result = new ObjectBigIntHashMap<K>();
    for (const [k, v] of this.map) {
      if (predicate(k, v)) {
        result.put(k, v);
      }
    }
    return result;
  }

  /** Returns a new map with entries NOT satisfying the predicate. */
  reject(
    predicate: (key: K, value: bigint) => boolean,
  ): ObjectBigIntHashMap<K> {
    const result = new ObjectBigIntHashMap<K>();
    for (const [k, v] of this.map) {
      if (!predicate(k, v)) {
        result.put(k, v);
      }
    }
    return result;
  }

  /** Returns all keys as an array. */
  keysToArray(): K[] {
    return Array.from(this.map.keys());
  }

  /** Returns all values as an array. */
  valuesToArray(): bigint[] {
    return Array.from(this.map.values());
  }

  /** Returns a string representation. */
  toString(): string {
    const parts: string[] = [];
    for (const [k, v] of this.map) {
      parts.push(`${k}: ${v}`);
    }
    return `{${parts.join(", ")}}`;
  }
}
