// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { Float32HashSet } from "./float32-hash-set.js";

describe("Float32HashSet generated", () => {
  it("add and contains", () => {
    const s = new Float32HashSet();
    s.add(1);
    s.add(2);
    s.add(3);
    expect(s.size()).toBe(3);
    expect(s.contains(2)).toBe(true);
    expect(s.contains(99)).toBe(false);
  });
  it("add duplicate", () => {
    const s = new Float32HashSet();
    expect(s.add(1)).toBe(true);
    expect(s.add(1)).toBe(false);
    expect(s.size()).toBe(1);
  });
  it("remove", () => {
    const s = new Float32HashSet();
    s.add(1);
    s.add(2);
    expect(s.remove(1)).toBe(true);
    expect(s.contains(1)).toBe(false);
    expect(s.remove(99)).toBe(false);
  });
  it("isEmpty and clear", () => {
    const s = new Float32HashSet();
    expect(s.isEmpty()).toBe(true);
    s.add(1);
    expect(s.isEmpty()).toBe(false);
    s.clear();
    expect(s.isEmpty()).toBe(true);
  });
  it("union", () => {
    const a = new Float32HashSet();
    a.add(1);
    a.add(2);
    const b = new Float32HashSet();
    b.add(2);
    b.add(3);
    expect(a.union(b).size()).toBe(3);
  });
  it("intersect", () => {
    const a = new Float32HashSet();
    a.add(1);
    a.add(2);
    const b = new Float32HashSet();
    b.add(2);
    b.add(3);
    expect(a.intersect(b).size()).toBe(1);
  });
  it("difference", () => {
    const a = new Float32HashSet();
    a.add(1);
    a.add(2);
    const b = new Float32HashSet();
    b.add(2);
    b.add(3);
    expect(a.difference(b).size()).toBe(1);
  });
  it("select", () => {
    const s = new Float32HashSet();
    s.add(1);
    s.add(2);
    s.add(3);
    expect(s.select((v) => v > 1).size()).toBe(2);
  });
  it("memoryBytes", () => {
    const s = new Float32HashSet(64);
    expect(s.memoryBytes()).toBeGreaterThan(0);
  });
  it("toString", () => {
    const s = new Float32HashSet();
    s.add(1);
    expect(s.toString()).not.toBe("");
  });

  describe("IEEE 754 edge cases", () => {
    it("NaN is findable", () => {
      const s = new Float32HashSet();
      s.add(NaN);
      expect(s.contains(NaN)).toBe(true);
      expect(s.size()).toBe(1);
    });
    it("NaN add duplicate does not grow", () => {
      const s = new Float32HashSet();
      expect(s.add(NaN)).toBe(true);
      expect(s.add(NaN)).toBe(false);
      expect(s.add(NaN)).toBe(false);
      expect(s.size()).toBe(1);
    });
    it("NaN remove works", () => {
      const s = new Float32HashSet();
      s.add(NaN);
      expect(s.remove(NaN)).toBe(true);
      expect(s.contains(NaN)).toBe(false);
      expect(s.size()).toBe(0);
    });
    it("-0.0 is distinct from +0.0", () => {
      const s = new Float32HashSet();
      s.add(0.0);
      s.add(-0.0);
      expect(s.size()).toBe(2);
      expect(s.contains(0.0)).toBe(true);
      expect(s.contains(-0.0)).toBe(true);
    });
    it("+/-Infinity are distinct elements", () => {
      const s = new Float32HashSet();
      s.add(Number.POSITIVE_INFINITY);
      s.add(Number.NEGATIVE_INFINITY);
      expect(s.size()).toBe(2);
      expect(s.contains(Number.POSITIVE_INFINITY)).toBe(true);
      expect(s.contains(Number.NEGATIVE_INFINITY)).toBe(true);
    });
  });
});
