// Code generated by mapdb-codegen. DO NOT EDIT.

import { BigInt64HashSet } from "./bigint64-hash-set";

/**
 * Immutable hash set backed by BigInt64Array with Uint8Array occupied bitmap.
 * Elements: 8 bytes each, contiguous memory.
 * Construct via static of(values) or fromMutable(mutable).
 * Mutations create new instances; select/reject return MUTABLE.
 */
export class ImmutableBigInt64HashSet {
  private items: BigInt64Array;
  private occupied: Uint8Array;
  private _size: number;
  private capacity: number;

  /** Creates an immutable set from an array of values (defensive copy). */
  static of(values: bigint[]): ImmutableBigInt64HashSet {
    const set = new BigInt64HashSet(values.length);
    for (const v of values) {
      set.add(v);
    }
    return ImmutableBigInt64HashSet.fromMutable(set);
  }

  /** Creates an immutable copy from a mutable set (defensive copy). */
  static fromMutable(mutable: BigInt64HashSet): ImmutableBigInt64HashSet {
    const arr = mutable.toArray();
    const c = nextPowerOfTwo(Math.max(arr.length * 2, 16));
    const items = new BigInt64Array(c);
    const occupied = new Uint8Array(c);
    let size = 0;
    for (const v of arr) {
      const idx = hash(v, c);
      let i = idx;
      while (true) {
        if (!occupied[i]) {
          items[i] = v;
          occupied[i] = 1;
          size++;
          break;
        }
        if (Object.is(items[i], v)) break;
        i = (i + 1) & (c - 1);
      }
    }
    return new ImmutableBigInt64HashSet(items, occupied, size, c);
  }

  private constructor(
    items: BigInt64Array,
    occupied: Uint8Array,
    size: number,
    capacity: number,
  ) {
    this.items = items;
    this.occupied = occupied;
    this._size = size;
    this.capacity = capacity;
  }

  /** Returns true if the set contains the given value. */
  contains(value: bigint): boolean {
    if (this.capacity === 0) return false;
    const mask = this.capacity - 1;
    let idx = hash(value, this.capacity);
    while (true) {
      if (!this.occupied[idx]) return false;
      if (Object.is(this.items[idx], value)) return true;
      idx = (idx + 1) & mask;
    }
  }

  /** Alias for contains. */
  includes(value: bigint): boolean {
    return this.contains(value);
  }

  /** Returns the number of elements. */
  size(): number {
    return this._size;
  }

  /** Returns true if the set is empty. */
  isEmpty(): boolean {
    return this._size === 0;
  }

  /** Returns a new MUTABLE set with elements satisfying the predicate. */
  select(predicate: (value: bigint) => boolean): BigInt64HashSet {
    const result = new BigInt64HashSet();
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && predicate(this.items[i])) {
        result.add(this.items[i]);
      }
    }
    return result;
  }

  /** Returns a new MUTABLE set with elements NOT satisfying the predicate. */
  reject(predicate: (value: bigint) => boolean): BigInt64HashSet {
    const result = new BigInt64HashSet();
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && !predicate(this.items[i])) {
        result.add(this.items[i]);
      }
    }
    return result;
  }

  /** Returns true if any element satisfies the predicate. */
  anySatisfy(predicate: (value: bigint) => boolean): boolean {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && predicate(this.items[i])) return true;
    }
    return false;
  }

  /** Returns true if all elements satisfy the predicate. */
  allSatisfy(predicate: (value: bigint) => boolean): boolean {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && !predicate(this.items[i])) return false;
    }
    return true;
  }

  /** Returns true if no element satisfies the predicate. */
  noneSatisfy(predicate: (value: bigint) => boolean): boolean {
    return !this.anySatisfy(predicate);
  }

  /** Returns the number of elements satisfying the predicate. */
  count(predicate: (value: bigint) => boolean): number {
    let c = 0;
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && predicate(this.items[i])) c++;
    }
    return c;
  }

  /** Yields all values. */
  *values(): Generator<bigint> {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) yield this.items[i];
    }
  }

  /** Makes the set iterable with for-of loops. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) yield this.items[i];
    }
  }

  /** Returns all elements as a new plain array (defensive copy). */
  toArray(): bigint[] {
    const result: bigint[] = [];
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) result.push(this.items[i]);
    }
    return result;
  }

  /** Returns a mutable copy of this immutable set. */
  toMutable(): BigInt64HashSet {
    return BigInt64HashSet.fromImmutable(this);
  }

  /** Calls the function for each element. */
  forEach(f: (value: bigint) => void): void {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) f(this.items[i]);
    }
  }

  /** Returns a new array with the results of calling f on each element. */
  map<U>(f: (value: bigint) => U): U[] {
    const result: U[] = [];
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) result.push(f(this.items[i]));
    }
    return result;
  }

  /** Returns a new array with elements satisfying the predicate. */
  filter(predicate: (value: bigint) => boolean): bigint[] {
    const result: bigint[] = [];
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && predicate(this.items[i]))
        result.push(this.items[i]);
    }
    return result;
  }

  /** Reduces the set to a single value. */
  reduce<U>(f: (acc: U, value: bigint) => U, initial: U): U {
    let acc = initial;
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) acc = f(acc, this.items[i]);
    }
    return acc;
  }

  /** Returns a string representation. */
  toString(): string {
    const parts: string[] = [];
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) parts.push(`${this.items[i]}`);
    }
    return `{${parts.join(", ")}}`;
  }

  /** Memory used by backing arrays in bytes. */
  memoryBytes(): number {
    return this.capacity * (8 + 1);
  }
}

function hash(key: bigint, cap: number): number {
  let h = Number(key & 0xffffffffn) | 0;
  h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
  h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
  h = ((h >> 16) ^ h) >>> 0;
  return h & (cap - 1);
}

function nextPowerOfTwo(n: number): number {
  if (n <= 0) return 16;
  n--;
  n |= n >> 1;
  n |= n >> 2;
  n |= n >> 4;
  n |= n >> 8;
  n |= n >> 16;
  n++;
  return n;
}
