// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { ImmutableBigInt64HashSet } from "./immutable_bigint64-hash-set.js";
import { BigInt64HashSet } from "./bigint64-hash-set.js";

describe("ImmutableBigInt64HashSet generated", () => {
  it("static of creates immutable set", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n]);
    expect(set.size()).toBe(3);
    expect(set.contains(1n)).toBe(true);
    expect(set.contains(3n)).toBe(true);
  });

  it("fromMutable creates defensive copy", () => {
    const mutable = new BigInt64HashSet();
    mutable.add(1n);
    mutable.add(2n);
    const imm = ImmutableBigInt64HashSet.fromMutable(mutable);
    mutable.add(3n);
    expect(imm.size()).toBe(2);
    expect(mutable.size()).toBe(3);
  });

  it("contains and includes", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n]);
    expect(set.contains(1n)).toBe(true);
    expect(set.contains(2n)).toBe(true);
    expect(set.contains(99n)).toBe(false);
    expect(set.includes(1n)).toBe(true);
  });

  it("size and isEmpty", () => {
    const empty = ImmutableBigInt64HashSet.of([]);
    expect(empty.size()).toBe(0);
    expect(empty.isEmpty()).toBe(true);
    const nonEmpty = ImmutableBigInt64HashSet.of([1n]);
    expect(nonEmpty.size()).toBe(1);
    expect(nonEmpty.isEmpty()).toBe(false);
  });

  it("select returns MUTABLE", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n, 4n, 5n]);
    const result = set.select((v) => v > 3n);
    expect(typeof result.add).toBe("function");
    expect(result.size()).toBe(2);
  });

  it("reject returns MUTABLE", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n, 4n, 5n]);
    const result = set.reject((v) => v > 3n);
    expect(typeof result.add).toBe("function");
    expect(result.size()).toBe(3);
  });

  it("anySatisfy / allSatisfy", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n]);
    expect(set.anySatisfy((v) => v === 2n)).toBe(true);
    expect(set.anySatisfy((v) => v === 99n)).toBe(false);
    expect(set.allSatisfy((v) => v > 0n)).toBe(true);
  });

  it("noneSatisfy", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n]);
    expect(set.noneSatisfy((v) => v === 99n)).toBe(true);
    expect(set.noneSatisfy((v) => v === 1n)).toBe(false);
  });

  it("count", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n, 4n, 5n]);
    expect(set.count((v) => v > 3n)).toBe(2);
  });

  it("toArray creates copy", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n]);
    const arr = set.toArray();
    // Modify the array - original should be unaffected (but we can't easily test this for sets)
    expect(arr.length).toBe(3);
  });

  it("toMutable round-trip", () => {
    const original = ImmutableBigInt64HashSet.of([1n, 2n, 3n]);
    const mutable = original.toMutable();
    mutable.add(4n);
    expect(mutable.size()).toBe(4);
    expect(original.size()).toBe(3);
  });

  it("forEach", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n]);
    const collected: bigint[] = [];
    set.forEach((v) => collected.push(v));
    expect(collected.length).toBe(3);
    expect(collected.includes(1n)).toBe(true);
  });

  it("map", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n]);
    const result = set.map((v) => v * 2n);
    expect(result.length).toBe(3);
  });

  it("filter", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n, 4n]);
    const result = set.filter((v) => v <= 3n);
    expect(result.length).toBe(3);
  });

  it("reduce", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n]);
    const sum = set.reduce((acc, v) => acc + v, 0n);
    expect(sum).toBe(1n + 2n + 3n);
  });

  it("values iterator", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n]);
    const collected: bigint[] = [];
    for (const v of set.values()) {
      collected.push(v);
    }
    expect(collected.length).toBe(3);
  });

  it("Symbol.iterator", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n]);
    const collected: bigint[] = [];
    for (const v of set) {
      collected.push(v);
    }
    expect(collected.length).toBe(2);
  });

  it("toString", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n]);
    const str = set.toString();
    expect(str).not.toBe("");
  });

  it("memoryBytes", () => {
    const set = ImmutableBigInt64HashSet.of([1n, 2n, 3n]);
    // At least 3 elements * (byteSize + 1 for occupied) bytes
    expect(set.memoryBytes()).toBeGreaterThanOrEqual(3 * (8 + 1));
  });

  it("defensive copy - modifying source array doesn't affect immutable", () => {
    const source = [1n, 2n, 3n];
    const set = ImmutableBigInt64HashSet.of(source);
    source[0] = 99n as any;
    expect(set.contains(1n)).toBe(true);
    expect(set.contains(99n)).toBe(false);
  });

  // Verify mutators are not available
  it("has no add method", () => {
    const set = ImmutableBigInt64HashSet.of([1n]);
    // @ts-expect-error - add should not exist on immutable
    expect(set.add).toBeUndefined();
  });

  it("has no remove method", () => {
    const set = ImmutableBigInt64HashSet.of([1n]);
    // @ts-expect-error - remove should not exist on immutable
    expect(set.remove).toBeUndefined();
  });
});
