// Code generated by mapdb-codegen. DO NOT EDIT.

const DEFAULT_CAPACITY = 16;
const LOAD_FACTOR = 0.75;

/**
 * Hash set backed by Int16Array with Uint8Array occupied bitmap.
 * Elements: 2 bytes each, contiguous memory, no GC pressure.
 * Open-addressing with linear probing.
 * Memory: 3 bytes/slot (vs ~50-70 bytes in Set<number>).
 */
export class Int16HashSet {
  private items: Int16Array;
  private occupied: Uint8Array;
  private _size = 0;
  private capacity: number;

  constructor(capacity = DEFAULT_CAPACITY) {
    this.capacity = nextPowerOfTwo(capacity);
    this.items = new Int16Array(this.capacity);
    this.occupied = new Uint8Array(this.capacity);
  }

  add(value: number): boolean {
    if (this.needsResize()) this.resize();
    const mask = this.capacity - 1;
    let idx = this.hash(value) & mask;
    while (true) {
      if (!this.occupied[idx]) {
        this.items[idx] = value;
        this.occupied[idx] = 1;
        this._size++;
        return true;
      }
      if (Object.is(this.items[idx], value)) return false;
      idx = (idx + 1) & mask;
    }
  }

  remove(value: number): boolean {
    if (this.capacity === 0) return false;
    const mask = this.capacity - 1;
    let idx = this.hash(value) & mask;
    while (true) {
      if (!this.occupied[idx]) return false;
      if (Object.is(this.items[idx], value)) {
        this.occupied[idx] = 0;
        this._size--;
        this.rehashFrom(idx, mask);
        return true;
      }
      idx = (idx + 1) & mask;
    }
  }

  contains(value: number): boolean {
    if (this.capacity === 0) return false;
    const mask = this.capacity - 1;
    let idx = this.hash(value) & mask;
    while (true) {
      if (!this.occupied[idx]) return false;
      if (Object.is(this.items[idx], value)) return true;
      idx = (idx + 1) & mask;
    }
  }

  size(): number {
    return this._size;
  }
  isEmpty(): boolean {
    return this._size === 0;
  }

  clear(): void {
    this.occupied.fill(0);
    this._size = 0;
  }

  union(other: Int16HashSet): Int16HashSet {
    const result = new Int16HashSet(this._size + other._size);
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) result.add(this.items[i]);
    }
    for (let i = 0; i < other.capacity; i++) {
      if (other.occupied[i]) result.add(other.items[i]);
    }
    return result;
  }

  intersect(other: Int16HashSet): Int16HashSet {
    const result = new Int16HashSet();
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && other.contains(this.items[i])) {
        result.add(this.items[i]);
      }
    }
    return result;
  }

  difference(other: Int16HashSet): Int16HashSet {
    const result = new Int16HashSet();
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && !other.contains(this.items[i])) {
        result.add(this.items[i]);
      }
    }
    return result;
  }

  *values(): Generator<number> {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) yield this.items[i];
    }
  }

  toArray(): Int16Array {
    const result = new Int16Array(this._size);
    let j = 0;
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) result[j++] = this.items[i];
    }
    return result;
  }

  /** Creates a mutable set from an immutable one. */
  static fromImmutable(imm: {
    toArray(): number[];
    size(): number;
  }): Int16HashSet {
    const arr = imm.toArray();
    const set = new Int16HashSet(arr.length);
    for (const v of arr) {
      set.add(v);
    }
    return set;
  }

  forEach(f: (value: number) => void): void {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) f(this.items[i]);
    }
  }

  select(predicate: (value: number) => boolean): Int16HashSet {
    const result = new Int16HashSet();
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && predicate(this.items[i])) {
        result.add(this.items[i]);
      }
    }
    return result;
  }

  reject(predicate: (value: number) => boolean): Int16HashSet {
    const result = new Int16HashSet();
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && !predicate(this.items[i])) {
        result.add(this.items[i]);
      }
    }
    return result;
  }

  toString(): string {
    const parts: string[] = [];
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) parts.push(`${this.items[i]}`);
    }
    return `{${parts.join(", ")}}`;
  }

  /** Memory used by backing arrays in bytes */
  memoryBytes(): number {
    return this.capacity * (2 + 1);
  }

  private hash(key: number): number {
    let h = key | 0;
    h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
    h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
    return ((h >> 16) ^ h) >>> 0;
  }

  private needsResize(): boolean {
    return this._size + 1 > this.capacity * LOAD_FACTOR;
  }

  private resize(): void {
    const oldItems = this.items;
    const oldOccupied = this.occupied;
    const oldCap = this.capacity;
    this.capacity *= 2;
    this.items = new Int16Array(this.capacity);
    this.occupied = new Uint8Array(this.capacity);
    this._size = 0;
    for (let i = 0; i < oldCap; i++) {
      if (oldOccupied[i]) this.add(oldItems[i]);
    }
  }

  private rehashFrom(deleted: number, mask: number): void {
    let idx = (deleted + 1) & mask;
    while (this.occupied[idx]) {
      const ideal = this.hash(this.items[idx]) & mask;
      const distCurrent = (idx - ideal + this.capacity) & mask;
      const distGap = (deleted - ideal + this.capacity) & mask;
      if (distCurrent > distGap) {
        this.items[deleted] = this.items[idx];
        this.occupied[deleted] = 1;
        this.occupied[idx] = 0;
        deleted = idx;
      }
      idx = (idx + 1) & mask;
      if (idx === deleted) break;
    }
  }
}

function nextPowerOfTwo(n: number): number {
  if (n <= 0) return 16;
  n--;
  n |= n >> 1;
  n |= n >> 2;
  n |= n >> 4;
  n |= n >> 8;
  n |= n >> 16;
  n++;
  return n;
}
