// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { Int8HashSet } from "./int8-hash-set.js";

describe("Int8HashSet generated", () => {
  it("add and contains", () => {
    const s = new Int8HashSet();
    s.add(1);
    s.add(2);
    s.add(3);
    expect(s.size()).toBe(3);
    expect(s.contains(2)).toBe(true);
    expect(s.contains(99)).toBe(false);
  });
  it("add duplicate", () => {
    const s = new Int8HashSet();
    expect(s.add(1)).toBe(true);
    expect(s.add(1)).toBe(false);
    expect(s.size()).toBe(1);
  });
  it("remove", () => {
    const s = new Int8HashSet();
    s.add(1);
    s.add(2);
    expect(s.remove(1)).toBe(true);
    expect(s.contains(1)).toBe(false);
    expect(s.remove(99)).toBe(false);
  });
  it("isEmpty and clear", () => {
    const s = new Int8HashSet();
    expect(s.isEmpty()).toBe(true);
    s.add(1);
    expect(s.isEmpty()).toBe(false);
    s.clear();
    expect(s.isEmpty()).toBe(true);
  });
  it("union", () => {
    const a = new Int8HashSet();
    a.add(1);
    a.add(2);
    const b = new Int8HashSet();
    b.add(2);
    b.add(3);
    expect(a.union(b).size()).toBe(3);
  });
  it("intersect", () => {
    const a = new Int8HashSet();
    a.add(1);
    a.add(2);
    const b = new Int8HashSet();
    b.add(2);
    b.add(3);
    expect(a.intersect(b).size()).toBe(1);
  });
  it("difference", () => {
    const a = new Int8HashSet();
    a.add(1);
    a.add(2);
    const b = new Int8HashSet();
    b.add(2);
    b.add(3);
    expect(a.difference(b).size()).toBe(1);
  });
  it("select", () => {
    const s = new Int8HashSet();
    s.add(1);
    s.add(2);
    s.add(3);
    expect(s.select((v) => v > 1).size()).toBe(2);
  });
  it("memoryBytes", () => {
    const s = new Int8HashSet(64);
    expect(s.memoryBytes()).toBeGreaterThan(0);
  });
  it("toString", () => {
    const s = new Int8HashSet();
    s.add(1);
    expect(s.toString()).not.toBe("");
  });
});
