// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigInt64ArrayList } from "./bigint64-array-list.js";

describe("BigInt64ArrayList generated", () => {
  it("add and get", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    l.add(3n);
    expect(l.size()).toBe(3);
    expect(l.get(0)).toBe(1n);
    expect(l.get(2)).toBe(3n);
  });
  it("set", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    const old = l.set(0, 3n);
    expect(old).toBe(1n);
    expect(l.get(0)).toBe(3n);
  });
  it("removeAtIndex", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    l.add(3n);
    const removed = l.removeAtIndex(1);
    expect(removed).toBe(2n);
    expect(l.size()).toBe(2);
  });
  it("contains and indexOf", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    expect(l.contains(1n)).toBe(true);
    expect(l.contains(99n)).toBe(false);
    expect(l.indexOf(2n)).toBe(1);
    expect(l.indexOf(99n)).toBe(-1);
  });
  it("isEmpty and clear", () => {
    const l = new BigInt64ArrayList();
    expect(l.isEmpty()).toBe(true);
    l.add(1n);
    expect(l.isEmpty()).toBe(false);
    l.clear();
    expect(l.size()).toBe(0);
  });
  it("select", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    l.add(3n);
    l.add(4n);
    l.add(5n);
    expect(l.select((v) => v > 3n).size()).toBe(2);
  });
  it("reject", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    l.add(3n);
    l.add(4n);
    l.add(5n);
    expect(l.reject((v) => v > 3n).size()).toBe(3);
  });
  it("detect", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    expect(l.detect((v) => v === 2n)).toBe(2n);
    expect(l.detect((v) => v === 99n)).toBeUndefined();
  });
  it("anySatisfy / allSatisfy", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    expect(l.anySatisfy((v) => v === 2n)).toBe(true);
    expect(l.anySatisfy((v) => v === 99n)).toBe(false);
    expect(l.allSatisfy((v) => v > 0n)).toBe(true);
  });
  it("count", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    l.add(3n);
    l.add(4n);
    l.add(5n);
    expect(l.count((v) => v > 3n)).toBe(2);
  });
  it("sum, min, max", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    l.add(2n);
    l.add(3n);
    expect(l.sum()).toBe(1n + 2n + 3n);
    expect(l.min()).toBe(1n);
    expect(l.max()).toBe(3n);
  });
  it("sort and toArray", () => {
    const l = new BigInt64ArrayList();
    l.add(3n);
    l.add(1n);
    l.add(2n);
    l.sort();
    expect(l.toArray()).toEqual(new BigInt64Array([1n, 2n, 3n]));
  });
  it("resize", () => {
    const l = new BigInt64ArrayList();
    for (let i = 0n; i < 100n; i += 1n) l.add(i);
    expect(l.size()).toBe(100);
  });
  it("memoryBytes", () => {
    const l = new BigInt64ArrayList(64);
    expect(l.memoryBytes()).toBe(64 * 8);
  });
  it("toString", () => {
    const l = new BigInt64ArrayList();
    l.add(1n);
    expect(l.toString()).not.toBe("");
  });
});
