// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { Float32ArrayList } from "./float32-array-list.js";

describe("Float32ArrayList generated", () => {
  it("add and get", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    l.add(3);
    expect(l.size()).toBe(3);
    expect(l.get(0)).toBe(1);
    expect(l.get(2)).toBe(3);
  });
  it("set", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    const old = l.set(0, 3);
    expect(old).toBe(1);
    expect(l.get(0)).toBe(3);
  });
  it("removeAtIndex", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    l.add(3);
    const removed = l.removeAtIndex(1);
    expect(removed).toBe(2);
    expect(l.size()).toBe(2);
  });
  it("contains and indexOf", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    expect(l.contains(1)).toBe(true);
    expect(l.contains(99)).toBe(false);
    expect(l.indexOf(2)).toBe(1);
    expect(l.indexOf(99)).toBe(-1);
  });
  it("isEmpty and clear", () => {
    const l = new Float32ArrayList();
    expect(l.isEmpty()).toBe(true);
    l.add(1);
    expect(l.isEmpty()).toBe(false);
    l.clear();
    expect(l.size()).toBe(0);
  });
  it("select", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    l.add(3);
    l.add(4);
    l.add(5);
    expect(l.select((v) => v > 3).size()).toBe(2);
  });
  it("reject", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    l.add(3);
    l.add(4);
    l.add(5);
    expect(l.reject((v) => v > 3).size()).toBe(3);
  });
  it("detect", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    expect(l.detect((v) => v === 2)).toBe(2);
    expect(l.detect((v) => v === 99)).toBeUndefined();
  });
  it("anySatisfy / allSatisfy", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    expect(l.anySatisfy((v) => v === 2)).toBe(true);
    expect(l.anySatisfy((v) => v === 99)).toBe(false);
    expect(l.allSatisfy((v) => v > 0)).toBe(true);
  });
  it("count", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    l.add(3);
    l.add(4);
    l.add(5);
    expect(l.count((v) => v > 3)).toBe(2);
  });
  it("sum, min, max", () => {
    const l = new Float32ArrayList();
    l.add(1);
    l.add(2);
    l.add(3);
    expect(l.sum()).toBe(1 + 2 + 3);
    expect(l.min()).toBe(1);
    expect(l.max()).toBe(3);
  });
  it("sort and toArray", () => {
    const l = new Float32ArrayList();
    l.add(3);
    l.add(1);
    l.add(2);
    l.sort();
    expect(l.toArray()).toEqual(new Float32Array([1, 2, 3]));
  });
  it("resize", () => {
    const l = new Float32ArrayList();
    for (let i = 0; i < 100; i += 1) l.add(i);
    expect(l.size()).toBe(100);
  });
  it("memoryBytes", () => {
    const l = new Float32ArrayList(64);
    expect(l.memoryBytes()).toBe(64 * 4);
  });
  it("toString", () => {
    const l = new Float32ArrayList();
    l.add(1);
    expect(l.toString()).not.toBe("");
  });
});
