// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { ImmutableBigInt64ArrayList } from "./immutable_bigint64-array-list.js";
import { BigInt64ArrayList } from "./bigint64-array-list.js";

describe("ImmutableBigInt64ArrayList generated", () => {
  it("static of creates immutable copy", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    expect(list.size()).toBe(3);
    expect(list.get(0)).toBe(1n);
    expect(list.get(2)).toBe(3n);
  });

  it("fromMutable creates defensive copy", () => {
    const mutable = new BigInt64ArrayList();
    mutable.add(1n);
    mutable.add(2n);
    const imm = ImmutableBigInt64ArrayList.fromMutable(mutable);
    // Mutating original doesn't affect immutable
    mutable.add(3n);
    expect(imm.size()).toBe(2);
    expect(mutable.size()).toBe(3);
  });

  it("get with bounds check", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n]);
    expect(list.get(0)).toBe(1n);
    expect(list.get(1)).toBe(2n);
    expect(() => list.get(2)).toThrow();
    expect(() => list.get(-1)).toThrow();
  });

  it("size and isEmpty", () => {
    const empty = ImmutableBigInt64ArrayList.of([]);
    expect(empty.size()).toBe(0);
    expect(empty.isEmpty()).toBe(true);
    const nonEmpty = ImmutableBigInt64ArrayList.of([1n]);
    expect(nonEmpty.size()).toBe(1);
    expect(nonEmpty.isEmpty()).toBe(false);
  });

  it("contains and includes", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n]);
    expect(list.contains(1n)).toBe(true);
    expect(list.contains(2n)).toBe(true);
    expect(list.contains(99n)).toBe(false);
    expect(list.includes(1n)).toBe(true);
  });

  it("indexOf", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    expect(list.indexOf(1n)).toBe(0);
    expect(list.indexOf(2n)).toBe(1);
    expect(list.indexOf(99n)).toBe(-1);
  });

  it("select returns MUTABLE", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n, 4n, 5n]);
    const result = list.select((v) => v > 3n);
    // Verify it's mutable by checking it has add method
    expect(typeof result.add).toBe("function");
    expect(result.size()).toBe(2);
  });

  it("reject returns MUTABLE", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n, 4n, 5n]);
    const result = list.reject((v) => v > 3n);
    expect(typeof result.add).toBe("function");
    expect(result.size()).toBe(3);
  });

  it("find", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n]);
    expect(list.find((v) => v === 2n)).toBe(2n);
    expect(list.find((v) => v === 99n)).toBeUndefined();
  });

  it("anySatisfy / allSatisfy", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n]);
    expect(list.anySatisfy((v) => v === 2n)).toBe(true);
    expect(list.anySatisfy((v) => v === 99n)).toBe(false);
    expect(list.allSatisfy((v) => v > 0n)).toBe(true);
  });

  it("noneSatisfy", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n]);
    expect(list.noneSatisfy((v) => v === 99n)).toBe(true);
    expect(list.noneSatisfy((v) => v === 1n)).toBe(false);
  });

  it("count", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n, 4n, 5n]);
    expect(list.count((v) => v > 3n)).toBe(2);
  });

  it("sum, min, max", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    expect(list.sum()).toBe(1n + 2n + 3n);
    expect(list.min()).toBe(1n);
    expect(list.max()).toBe(3n);
  });

  it("toArray creates copy", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    const arr = list.toArray();
    arr[0] = 99n as any;
    expect(list.get(0)).toBe(1n); // original unchanged
  });

  it("toMutable round-trip", () => {
    const original = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    const mutable = original.toMutable();
    mutable.add(4n);
    expect(mutable.size()).toBe(4);
    // Original unchanged
    expect(original.size()).toBe(3);
  });

  it("forEach", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    const collected: bigint[] = [];
    list.forEach((v) => collected.push(v));
    expect(collected).toEqual([1n, 2n, 3n]);
  });

  it("map", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    const result = list.map((v) => v * 2n);
    expect(result).toEqual([1n * 2n, 2n * 2n, 3n * 2n]);
  });

  it("filter", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n, 4n]);
    const result = list.filter((v) => v <= 3n);
    expect(result.length).toBe(3);
  });

  it("reduce", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    const sum = list.reduce((acc, v) => acc + v, 0n);
    expect(sum).toBe(1n + 2n + 3n);
  });

  it("values iterator", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    const collected: bigint[] = [];
    for (const v of list.values()) {
      collected.push(v);
    }
    expect(collected).toEqual([1n, 2n, 3n]);
  });

  it("Symbol.iterator", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n]);
    const collected: bigint[] = [];
    for (const v of list) {
      collected.push(v);
    }
    expect(collected).toEqual([1n, 2n]);
  });

  it("toString", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n]);
    const str = list.toString();
    expect(str).not.toBe("");
    expect(str.includes("[")).toBe(true);
    expect(str.includes("]")).toBe(true);
  });

  it("memoryBytes", () => {
    const list = ImmutableBigInt64ArrayList.of([1n, 2n, 3n]);
    // 3 elements * byteSize
    expect(list.memoryBytes()).toBe(3 * 8);
  });

  it("defensive copy - modifying source array doesn't affect immutable", () => {
    const source = [1n, 2n, 3n];
    const list = ImmutableBigInt64ArrayList.of(source);
    source[0] = 99n as any;
    expect(list.get(0)).toBe(1n);
  });

  // Verify mutators are not available
  it("has no add method", () => {
    const list = ImmutableBigInt64ArrayList.of([1n]);
    // @ts-expect-error - add should not exist on immutable
    expect(list.add).toBeUndefined();
  });
});
