// Code generated by mapdb-codegen. DO NOT EDIT.

import { Float64ArrayList } from "./float64-array-list";

/**
 * Immutable list backed by Float64Array.
 * Elements: 8 bytes each, contiguous memory.
 * Construct via static of(values) or fromMutable(mutable).
 * Mutations create new instances; select/reject return MUTABLE.
 */
export class ImmutableFloat64ArrayList {
  private data: Float64Array;
  private _size: number;

  /** Creates an immutable list from an array of values (defensive copy). */
  static of(values: number[]): ImmutableFloat64ArrayList {
    const size = values.length;
    const data = new Float64Array(size);
    data.set(values);
    return new ImmutableFloat64ArrayList(data, size);
  }

  /** Creates an immutable copy from a mutable list (defensive copy). */
  static fromMutable(mutable: Float64ArrayList): ImmutableFloat64ArrayList {
    const arr = mutable.toArray();
    const data = new Float64Array(arr.length);
    data.set(arr);
    return new ImmutableFloat64ArrayList(data, arr.length);
  }

  private constructor(data: Float64Array, size: number) {
    this.data = data;
    this._size = size;
  }

  /** Returns the value at the given index. */
  get(index: number): number {
    if (index < 0 || index >= this._size) {
      throw new RangeError(
        `Index ${index} out of bounds for size ${this._size}`,
      );
    }
    return this.data[index];
  }

  /** Returns the number of elements. */
  size(): number {
    return this._size;
  }

  /** Returns true if the list is empty. */
  isEmpty(): boolean {
    return this._size === 0;
  }

  /** Returns true if the list contains the given value. */
  contains(value: number): boolean {
    for (let i = 0; i < this._size; i++) {
      if (Object.is(this.data[i], value)) return true;
    }
    return false;
  }

  /** Alias for contains. */
  includes(value: number): boolean {
    return this.contains(value);
  }

  /** Returns the index of the first occurrence, or -1. */
  indexOf(value: number): number {
    for (let i = 0; i < this._size; i++) {
      if (Object.is(this.data[i], value)) return i;
    }
    return -1;
  }

  /** Returns a new MUTABLE list with elements satisfying the predicate. */
  select(predicate: (value: number) => boolean): Float64ArrayList {
    const result = new Float64ArrayList();
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) result.add(this.data[i]);
    }
    return result;
  }

  /** Returns a new MUTABLE list with elements NOT satisfying the predicate. */
  reject(predicate: (value: number) => boolean): Float64ArrayList {
    const result = new Float64ArrayList();
    for (let i = 0; i < this._size; i++) {
      if (!predicate(this.data[i])) result.add(this.data[i]);
    }
    return result;
  }

  /** Returns the first element satisfying the predicate, or undefined. */
  find(predicate: (value: number) => boolean): number | undefined {
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) return this.data[i];
    }
    return undefined;
  }

  /** Returns true if any element satisfies the predicate. */
  anySatisfy(predicate: (value: number) => boolean): boolean {
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) return true;
    }
    return false;
  }

  /** Returns true if all elements satisfy the predicate. */
  allSatisfy(predicate: (value: number) => boolean): boolean {
    for (let i = 0; i < this._size; i++) {
      if (!predicate(this.data[i])) return false;
    }
    return true;
  }

  /** Returns true if no element satisfies the predicate. */
  noneSatisfy(predicate: (value: number) => boolean): boolean {
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) return false;
    }
    return true;
  }

  /** Returns the number of elements satisfying the predicate. */
  count(predicate: (value: number) => boolean): number {
    let c = 0;
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) c++;
    }
    return c;
  }

  /** Returns the sum of all elements. */
  sum(): number {
    let s: number = 0 as number;
    for (let i = 0; i < this._size; i++) {
      s = ((s as any) + this.data[i]) as any as number;
    }
    return s;
  }

  /** Returns the minimum element, or undefined if empty. */
  min(): number | undefined {
    if (this._size === 0) return undefined;
    let m = this.data[0];
    for (let i = 1; i < this._size; i++) {
      if (this.data[i] < m) m = this.data[i];
    }
    return m;
  }

  /** Returns the maximum element, or undefined if empty. */
  max(): number | undefined {
    if (this._size === 0) return undefined;
    let m = this.data[0];
    for (let i = 1; i < this._size; i++) {
      if (this.data[i] > m) m = this.data[i];
    }
    return m;
  }

  /** Yields all values in order. */
  *values(): Generator<number> {
    for (let i = 0; i < this._size; i++) {
      yield this.data[i];
    }
  }

  /** Makes the list iterable with for-of loops. */
  *[Symbol.iterator](): IterableIterator<number> {
    for (let i = 0; i < this._size; i++) {
      yield this.data[i];
    }
  }

  /** Returns all elements as a new plain array (defensive copy). */
  toArray(): number[] {
    const result: number[] = [];
    for (let i = 0; i < this._size; i++) {
      result.push(this.data[i]);
    }
    return result;
  }

  /** Returns a mutable copy of this immutable list. */
  toMutable(): Float64ArrayList {
    return Float64ArrayList.fromImmutable(this);
  }

  /** Calls the function for each element. */
  forEach(f: (value: number, index: number) => void): void {
    for (let i = 0; i < this._size; i++) {
      f(this.data[i], i);
    }
  }

  /** Returns a new array with the results of calling f on each element. */
  map<U>(f: (value: number) => U): U[] {
    const result: U[] = [];
    for (let i = 0; i < this._size; i++) {
      result.push(f(this.data[i]));
    }
    return result;
  }

  /** Returns a new array with elements satisfying the predicate. */
  filter(predicate: (value: number) => boolean): number[] {
    const result: number[] = [];
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) result.push(this.data[i]);
    }
    return result;
  }

  /** Reduces the list to a single value. */
  reduce<U>(f: (acc: U, value: number) => U, initial: U): U {
    let acc = initial;
    for (let i = 0; i < this._size; i++) {
      acc = f(acc, this.data[i]);
    }
    return acc;
  }

  /** Returns a string representation. */
  toString(): string {
    const parts: string[] = [];
    for (let i = 0; i < this._size; i++) {
      parts.push(`${this.data[i]}`);
    }
    return `[${parts.join(", ")}]`;
  }

  /** Memory used by the backing TypedArray in bytes. */
  memoryBytes(): number {
    return this.data.byteLength;
  }
}
