// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { ImmutableInt32ArrayList } from "./immutable_int32-array-list.js";
import { Int32ArrayList } from "./int32-array-list.js";

describe("ImmutableInt32ArrayList generated", () => {
  it("static of creates immutable copy", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3]);
    expect(list.size()).toBe(3);
    expect(list.get(0)).toBe(1);
    expect(list.get(2)).toBe(3);
  });

  it("fromMutable creates defensive copy", () => {
    const mutable = new Int32ArrayList();
    mutable.add(1);
    mutable.add(2);
    const imm = ImmutableInt32ArrayList.fromMutable(mutable);
    // Mutating original doesn't affect immutable
    mutable.add(3);
    expect(imm.size()).toBe(2);
    expect(mutable.size()).toBe(3);
  });

  it("get with bounds check", () => {
    const list = ImmutableInt32ArrayList.of([1, 2]);
    expect(list.get(0)).toBe(1);
    expect(list.get(1)).toBe(2);
    expect(() => list.get(2)).toThrow();
    expect(() => list.get(-1)).toThrow();
  });

  it("size and isEmpty", () => {
    const empty = ImmutableInt32ArrayList.of([]);
    expect(empty.size()).toBe(0);
    expect(empty.isEmpty()).toBe(true);
    const nonEmpty = ImmutableInt32ArrayList.of([1]);
    expect(nonEmpty.size()).toBe(1);
    expect(nonEmpty.isEmpty()).toBe(false);
  });

  it("contains and includes", () => {
    const list = ImmutableInt32ArrayList.of([1, 2]);
    expect(list.contains(1)).toBe(true);
    expect(list.contains(2)).toBe(true);
    expect(list.contains(99)).toBe(false);
    expect(list.includes(1)).toBe(true);
  });

  it("indexOf", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3]);
    expect(list.indexOf(1)).toBe(0);
    expect(list.indexOf(2)).toBe(1);
    expect(list.indexOf(99)).toBe(-1);
  });

  it("select returns MUTABLE", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3, 4, 5]);
    const result = list.select((v) => v > 3);
    // Verify it's mutable by checking it has add method
    expect(typeof result.add).toBe("function");
    expect(result.size()).toBe(2);
  });

  it("reject returns MUTABLE", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3, 4, 5]);
    const result = list.reject((v) => v > 3);
    expect(typeof result.add).toBe("function");
    expect(result.size()).toBe(3);
  });

  it("find", () => {
    const list = ImmutableInt32ArrayList.of([1, 2]);
    expect(list.find((v) => v === 2)).toBe(2);
    expect(list.find((v) => v === 99)).toBeUndefined();
  });

  it("anySatisfy / allSatisfy", () => {
    const list = ImmutableInt32ArrayList.of([1, 2]);
    expect(list.anySatisfy((v) => v === 2)).toBe(true);
    expect(list.anySatisfy((v) => v === 99)).toBe(false);
    expect(list.allSatisfy((v) => v > 0)).toBe(true);
  });

  it("noneSatisfy", () => {
    const list = ImmutableInt32ArrayList.of([1, 2]);
    expect(list.noneSatisfy((v) => v === 99)).toBe(true);
    expect(list.noneSatisfy((v) => v === 1)).toBe(false);
  });

  it("count", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3, 4, 5]);
    expect(list.count((v) => v > 3)).toBe(2);
  });

  it("sum, min, max", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3]);
    expect(list.sum()).toBe(1 + 2 + 3);
    expect(list.min()).toBe(1);
    expect(list.max()).toBe(3);
  });

  it("toArray creates copy", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3]);
    const arr = list.toArray();
    arr[0] = 99 as any;
    expect(list.get(0)).toBe(1); // original unchanged
  });

  it("toMutable round-trip", () => {
    const original = ImmutableInt32ArrayList.of([1, 2, 3]);
    const mutable = original.toMutable();
    mutable.add(4);
    expect(mutable.size()).toBe(4);
    // Original unchanged
    expect(original.size()).toBe(3);
  });

  it("forEach", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3]);
    const collected: number[] = [];
    list.forEach((v) => collected.push(v));
    expect(collected).toEqual([1, 2, 3]);
  });

  it("map", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3]);
    const result = list.map((v) => v * 2);
    expect(result).toEqual([1 * 2, 2 * 2, 3 * 2]);
  });

  it("filter", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3, 4]);
    const result = list.filter((v) => v <= 3);
    expect(result.length).toBe(3);
  });

  it("reduce", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3]);
    const sum = list.reduce((acc, v) => acc + v, 0);
    expect(sum).toBe(1 + 2 + 3);
  });

  it("values iterator", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3]);
    const collected: number[] = [];
    for (const v of list.values()) {
      collected.push(v);
    }
    expect(collected).toEqual([1, 2, 3]);
  });

  it("Symbol.iterator", () => {
    const list = ImmutableInt32ArrayList.of([1, 2]);
    const collected: number[] = [];
    for (const v of list) {
      collected.push(v);
    }
    expect(collected).toEqual([1, 2]);
  });

  it("toString", () => {
    const list = ImmutableInt32ArrayList.of([1, 2]);
    const str = list.toString();
    expect(str).not.toBe("");
    expect(str.includes("[")).toBe(true);
    expect(str.includes("]")).toBe(true);
  });

  it("memoryBytes", () => {
    const list = ImmutableInt32ArrayList.of([1, 2, 3]);
    // 3 elements * byteSize
    expect(list.memoryBytes()).toBe(3 * 4);
  });

  it("defensive copy - modifying source array doesn't affect immutable", () => {
    const source = [1, 2, 3];
    const list = ImmutableInt32ArrayList.of(source);
    source[0] = 99 as any;
    expect(list.get(0)).toBe(1);
  });

  // Verify mutators are not available
  it("has no add method", () => {
    const list = ImmutableInt32ArrayList.of([1]);
    // @ts-expect-error - add should not exist on immutable
    expect(list.add).toBeUndefined();
  });
});
