// Code generated by mapdb-codegen. DO NOT EDIT.

const DEFAULT_CAPACITY = 16;

/**
 * Resizable list backed by Int16Array.
 * Elements: 2 bytes each, contiguous memory, no GC pressure.
 * Grows by 2x when capacity is exceeded (allocates new Int16Array and copies).
 */
export class Int16ArrayList {
  private data: Int16Array;
  private _size = 0;

  constructor(initialCapacity = DEFAULT_CAPACITY) {
    this.data = new Int16Array(Math.max(initialCapacity, 1));
  }

  add(value: number): void {
    this.ensureCapacity(this._size + 1);
    this.data[this._size++] = value;
  }

  get(index: number): number {
    this.checkIndex(index);
    return this.data[index];
  }

  set(index: number, value: number): number {
    this.checkIndex(index);
    const old = this.data[index];
    this.data[index] = value;
    return old;
  }

  removeAtIndex(index: number): number {
    this.checkIndex(index);
    const old = this.data[index];
    // Shift elements left by copying subarray
    if (index < this._size - 1) {
      this.data.copyWithin(index, index + 1, this._size);
    }
    this._size--;
    return old;
  }

  contains(value: number): boolean {
    for (let i = 0; i < this._size; i++) {
      if (Object.is(this.data[i], value)) return true;
    }
    return false;
  }

  indexOf(value: number): number {
    for (let i = 0; i < this._size; i++) {
      if (Object.is(this.data[i], value)) return i;
    }
    return -1;
  }

  size(): number {
    return this._size;
  }
  isEmpty(): boolean {
    return this._size === 0;
  }

  clear(): void {
    this._size = 0;
  }

  sort(): void {
    if (this._size <= 1) return;
    const view = this.data.subarray(0, this._size);
    view.sort();
  }

  select(predicate: (value: number) => boolean): Int16ArrayList {
    const result = new Int16ArrayList();
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) result.add(this.data[i]);
    }
    return result;
  }

  reject(predicate: (value: number) => boolean): Int16ArrayList {
    const result = new Int16ArrayList();
    for (let i = 0; i < this._size; i++) {
      if (!predicate(this.data[i])) result.add(this.data[i]);
    }
    return result;
  }

  detect(predicate: (value: number) => boolean): number | undefined {
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) return this.data[i];
    }
    return undefined;
  }

  anySatisfy(predicate: (value: number) => boolean): boolean {
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) return true;
    }
    return false;
  }

  allSatisfy(predicate: (value: number) => boolean): boolean {
    for (let i = 0; i < this._size; i++) {
      if (!predicate(this.data[i])) return false;
    }
    return true;
  }

  count(predicate: (value: number) => boolean): number {
    let c = 0;
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) c++;
    }
    return c;
  }

  sum(): number {
    let s: number = 0 as number;
    for (let i = 0; i < this._size; i++) {
      s = ((s as any) + this.data[i]) as any as number;
    }
    return s;
  }

  min(): number | undefined {
    if (this._size === 0) return undefined;
    let m = this.data[0];
    for (let i = 1; i < this._size; i++) {
      if (this.data[i] < m) m = this.data[i];
    }
    return m;
  }

  max(): number | undefined {
    if (this._size === 0) return undefined;
    let m = this.data[0];
    for (let i = 1; i < this._size; i++) {
      if (this.data[i] > m) m = this.data[i];
    }
    return m;
  }

  *entries(): Generator<number> {
    for (let i = 0; i < this._size; i++) {
      yield this.data[i];
    }
  }

  toArray(): Int16Array {
    return this.data.slice(0, this._size);
  }

  /** Creates a mutable list from an immutable one. */
  static fromImmutable(imm: { toArray(): number[] }): Int16ArrayList {
    const arr = imm.toArray();
    const list = new Int16ArrayList(arr.length);
    for (const v of arr) {
      list.add(v);
    }
    return list;
  }

  forEach(f: (value: number, index: number) => void): void {
    for (let i = 0; i < this._size; i++) {
      f(this.data[i], i);
    }
  }

  toString(): string {
    const parts: string[] = [];
    for (let i = 0; i < this._size; i++) {
      parts.push(`${this.data[i]}`);
    }
    return `[${parts.join(", ")}]`;
  }

  /** Memory used by the backing TypedArray in bytes */
  memoryBytes(): number {
    return this.data.byteLength;
  }

  private ensureCapacity(minCapacity: number): void {
    if (minCapacity <= this.data.length) return;
    let newCapacity = this.data.length * 2;
    if (newCapacity < minCapacity) newCapacity = minCapacity;
    const newData = new Int16Array(newCapacity);
    newData.set(this.data.subarray(0, this._size));
    this.data = newData;
  }

  private checkIndex(index: number): void {
    if (index < 0 || index >= this._size) {
      throw new RangeError(
        `Index ${index} out of bounds for size ${this._size}`,
      );
    }
  }
}
