// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigInt64ArrayStack } from "./bigint64-array-stack.js";

describe("BigInt64ArrayStack generated", () => {
  it("push and pop", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    expect(s.size()).toBe(3);
    expect(s.pop()).toBe(3n);
    expect(s.pop()).toBe(2n);
    expect(s.pop()).toBe(1n);
  });

  it("peek", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    expect(s.peek()).toBe(2n);
    expect(s.size()).toBe(2); // peek doesn't remove
  });

  it("peekAt", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    expect(s.peekAt(0)).toBe(3n); // top
    expect(s.peekAt(1)).toBe(2n);
    expect(s.peekAt(2)).toBe(1n); // bottom
  });

  it("pop on empty throws", () => {
    const s = new BigInt64ArrayStack();
    expect(() => s.pop()).toThrow();
  });

  it("contains", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    expect(s.contains(1n)).toBe(true);
    expect(s.contains(2n)).toBe(true);
    expect(s.contains(99n)).toBe(false);
  });

  it("includes alias for contains", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    expect(s.includes(1n)).toBe(true);
    expect(s.includes(99n)).toBe(false);
  });

  it("isEmpty and clear", () => {
    const s = new BigInt64ArrayStack();
    expect(s.isEmpty()).toBe(true);
    s.push(1n);
    expect(s.isEmpty()).toBe(false);
    s.clear();
    expect(s.size()).toBe(0);
    expect(s.isEmpty()).toBe(true);
  });

  it("select", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    s.push(4n);
    s.push(5n);
    // select preserves order (but stack reversal means bottom-to-top becomes top-to-bottom in result)
    const result = s.select((v) => v > 3n);
    expect(result.size()).toBe(2);
  });

  it("reject", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    s.push(4n);
    s.push(5n);
    expect(s.reject((v) => v > 3n).size()).toBe(3);
  });

  it("find", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    expect(s.find((v) => v === 2n)).toBe(2n);
    expect(s.find((v) => v === 99n)).toBeUndefined();
  });

  it("every", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    expect(s.every((v) => v < 100n)).toBe(true);
    expect(s.every((v) => v < 1n)).toBe(false);
  });

  it("some", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    expect(s.some((v) => v === 2n)).toBe(true);
    expect(s.some((v) => v === 99n)).toBe(false);
  });

  it("anySatisfy / allSatisfy", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    expect(s.anySatisfy((v) => v === 2n)).toBe(true);
    expect(s.anySatisfy((v) => v === 99n)).toBe(false);
    expect(s.allSatisfy((v) => v > 0n)).toBe(true);
  });

  it("count", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    s.push(4n);
    s.push(5n);
    expect(s.count((v) => v > 3n)).toBe(2);
  });

  it("sum, min, max", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    expect(s.sum()).toBe(1n + 2n + 3n);
    expect(s.min()).toBe(1n);
    expect(s.max()).toBe(3n);
  });

  it("map", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    // Use explicit bigint literal (2n) for multiplication with bigint values
    const two = 2n;
    const result = s.map((v) => v * two);
    const expected = [3n * two, 2n * two, 1n * two];
    expect(result).toEqual(expected); // top to bottom
  });

  it("filter", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    s.push(4n);
    const result = s.filter((v) => v <= 3n);
    expect(result.length).toBe(3);
  });

  it("reduce", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    const sum = s.reduce((acc, v) => acc + v, 0n);
    expect(sum).toBe(1n + 2n + 3n);
  });

  it("forEach", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    const collected: bigint[] = [];
    s.forEach((v) => collected.push(v));
    // forEach goes top to bottom
    expect(collected).toEqual([3n, 2n, 1n]);
  });

  it("resize", () => {
    const s = new BigInt64ArrayStack();
    for (let i = 0n; i < 100n; i += 1n) s.push(i);
    expect(s.size()).toBe(100);
  });

  it("memoryBytes", () => {
    const s = new BigInt64ArrayStack(64);
    expect(s.memoryBytes()).toBe(64 * 8);
  });

  it("toString", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    expect(s.toString()).not.toBe("");
  });

  it("toArray", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    const arr = s.toArray();
    expect(arr).toEqual([3n, 2n, 1n]); // top first
  });

  it("values iterator", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    s.push(3n);
    const collected: bigint[] = [];
    for (const v of s.values()) {
      collected.push(v);
    }
    expect(collected).toEqual([3n, 2n, 1n]); // top to bottom
  });

  it("Symbol.iterator", () => {
    const s = new BigInt64ArrayStack();
    s.push(1n);
    s.push(2n);
    const collected: bigint[] = [];
    for (const v of s) {
      collected.push(v);
    }
    expect(collected).toEqual([2n, 1n]); // top to bottom
  });

  it("of factory", () => {
    const s = BigInt64ArrayStack.of([1n, 2n, 3n]); // last element is top
    expect(s.size()).toBe(3);
    expect(s.peek()).toBe(3n);
    expect(s.pop()).toBe(3n);
    expect(s.pop()).toBe(2n);
    expect(s.pop()).toBe(1n);
  });
});
