// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { ImmutableFloat64ArrayStack } from "./immutable_float64-array-stack.js";
import { Float64ArrayStack } from "./float64-array-stack.js";

describe("ImmutableFloat64ArrayStack generated", () => {
  it("static of creates immutable stack", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]); // last = top
    expect(stack.size()).toBe(3);
    expect(stack.peek()).toBe(3);
  });

  it("fromMutable creates defensive copy", () => {
    const mutable = new Float64ArrayStack();
    mutable.push(1);
    mutable.push(2);
    const imm = ImmutableFloat64ArrayStack.fromMutable(mutable);
    mutable.push(3);
    expect(imm.size()).toBe(2);
    expect(mutable.size()).toBe(3);
  });

  it("peek returns top element", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]); // top = 3
    expect(stack.peek()).toBe(3);
  });

  it("peek throws on empty", () => {
    const stack = ImmutableFloat64ArrayStack.of([]);
    expect(() => stack.peek()).toThrow();
  });

  it("peekAt", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]); // top = 3
    expect(stack.peekAt(0)).toBe(3); // top
    expect(stack.peekAt(1)).toBe(2);
    expect(stack.peekAt(2)).toBe(1); // bottom
  });

  it("peekAt throws on out of bounds", () => {
    const stack = ImmutableFloat64ArrayStack.of([1]);
    expect(() => stack.peekAt(1)).toThrow();
    expect(() => stack.peekAt(-1)).toThrow();
  });

  it("size and isEmpty", () => {
    const empty = ImmutableFloat64ArrayStack.of([]);
    expect(empty.size()).toBe(0);
    expect(empty.isEmpty()).toBe(true);
    const nonEmpty = ImmutableFloat64ArrayStack.of([1]);
    expect(nonEmpty.size()).toBe(1);
    expect(nonEmpty.isEmpty()).toBe(false);
  });

  it("contains and includes", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2]);
    expect(stack.contains(1)).toBe(true);
    expect(stack.contains(2)).toBe(true);
    expect(stack.contains(99)).toBe(false);
    expect(stack.includes(1)).toBe(true);
  });

  it("select returns MUTABLE", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3, 4, 5]);
    const result = stack.select((v) => v > 3);
    expect(typeof result.push).toBe("function");
    expect(result.size()).toBe(2);
  });

  it("reject returns MUTABLE", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3, 4, 5]);
    const result = stack.reject((v) => v > 3);
    expect(typeof result.push).toBe("function");
    expect(result.size()).toBe(3);
  });

  it("find", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]); // top = 3
    expect(stack.find((v) => v === 3)).toBe(3);
    expect(stack.find((v) => v === 99)).toBeUndefined();
  });

  it("every / some", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]);
    expect(stack.every((v) => v < 100)).toBe(true);
    expect(stack.every((v) => v < 1)).toBe(false);
    expect(stack.some((v) => v === 2)).toBe(true);
    expect(stack.some((v) => v === 99)).toBe(false);
  });

  it("anySatisfy / allSatisfy", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2]);
    expect(stack.anySatisfy((v) => v === 2)).toBe(true);
    expect(stack.anySatisfy((v) => v === 99)).toBe(false);
    expect(stack.allSatisfy((v) => v > 0)).toBe(true);
  });

  it("count", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3, 4, 5]);
    expect(stack.count((v) => v > 3)).toBe(2);
  });

  it("sum, min, max", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]);
    expect(stack.sum()).toBe(1 + 2 + 3);
    expect(stack.min()).toBe(1);
    expect(stack.max()).toBe(3);
  });

  it("toArray top to bottom", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]); // top = 3
    const arr = stack.toArray();
    expect(arr).toEqual([3, 2, 1]); // top first
  });

  it("toMutable round-trip", () => {
    const original = ImmutableFloat64ArrayStack.of([1, 2, 3]);
    const mutable = original.toMutable();
    mutable.push(4);
    expect(mutable.size()).toBe(4);
    expect(original.size()).toBe(3);
  });

  it("forEach top to bottom", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]);
    const collected: number[] = [];
    stack.forEach((v) => collected.push(v));
    expect(collected).toEqual([3, 2, 1]); // top to bottom
  });

  it("map top to bottom", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]);
    const result = stack.map((v) => v * 2);
    expect(result).toEqual([3 * 2, 2 * 2, 1 * 2]);
  });

  it("filter top to bottom", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3, 4]);
    const result = stack.filter((v) => v <= 3);
    expect(result.length).toBe(3);
  });

  it("reduce top to bottom", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]);
    const sum = stack.reduce((acc, v) => acc + v, 0);
    expect(sum).toBe(1 + 2 + 3);
  });

  it("values iterator top to bottom", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]);
    const collected: number[] = [];
    for (const v of stack.values()) {
      collected.push(v);
    }
    expect(collected).toEqual([3, 2, 1]);
  });

  it("Symbol.iterator top to bottom", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2]);
    const collected: number[] = [];
    for (const v of stack) {
      collected.push(v);
    }
    expect(collected).toEqual([2, 1]);
  });

  it("toString", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2]); // top = 2
    const str = stack.toString();
    expect(str).not.toBe("");
    expect(str.includes("[")).toBe(true);
    expect(str.includes("]")).toBe(true);
  });

  it("memoryBytes", () => {
    const stack = ImmutableFloat64ArrayStack.of([1, 2, 3]);
    expect(stack.memoryBytes()).toBe(3 * 8);
  });

  it("defensive copy - modifying source array doesn't affect immutable", () => {
    const source = [1, 2, 3];
    const stack = ImmutableFloat64ArrayStack.of(source);
    source[0] = 99 as any;
    expect(stack.peek()).toBe(3);
  });

  // Verify mutators are not available
  it("has no push method", () => {
    const stack = ImmutableFloat64ArrayStack.of([1]);
    // @ts-expect-error - push should not exist on immutable
    expect(stack.push).toBeUndefined();
  });
});
