// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { ImmutableBigInt64ArrayStack } from "./immutable_bigint64-array-stack.js";
import { BigInt64ArrayStack } from "./bigint64-array-stack.js";

describe("ImmutableBigInt64ArrayStack generated", () => {
  it("static of creates immutable stack", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]); // last = top
    expect(stack.size()).toBe(3);
    expect(stack.peek()).toBe(3n);
  });

  it("fromMutable creates defensive copy", () => {
    const mutable = new BigInt64ArrayStack();
    mutable.push(1n);
    mutable.push(2n);
    const imm = ImmutableBigInt64ArrayStack.fromMutable(mutable);
    mutable.push(3n);
    expect(imm.size()).toBe(2);
    expect(mutable.size()).toBe(3);
  });

  it("peek returns top element", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]); // top = 3n
    expect(stack.peek()).toBe(3n);
  });

  it("peek throws on empty", () => {
    const stack = ImmutableBigInt64ArrayStack.of([]);
    expect(() => stack.peek()).toThrow();
  });

  it("peekAt", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]); // top = 3n
    expect(stack.peekAt(0)).toBe(3n); // top
    expect(stack.peekAt(1)).toBe(2n);
    expect(stack.peekAt(2)).toBe(1n); // bottom
  });

  it("peekAt throws on out of bounds", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n]);
    expect(() => stack.peekAt(1)).toThrow();
    expect(() => stack.peekAt(-1)).toThrow();
  });

  it("size and isEmpty", () => {
    const empty = ImmutableBigInt64ArrayStack.of([]);
    expect(empty.size()).toBe(0);
    expect(empty.isEmpty()).toBe(true);
    const nonEmpty = ImmutableBigInt64ArrayStack.of([1n]);
    expect(nonEmpty.size()).toBe(1);
    expect(nonEmpty.isEmpty()).toBe(false);
  });

  it("contains and includes", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n]);
    expect(stack.contains(1n)).toBe(true);
    expect(stack.contains(2n)).toBe(true);
    expect(stack.contains(99n)).toBe(false);
    expect(stack.includes(1n)).toBe(true);
  });

  it("select returns MUTABLE", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n, 4n, 5n]);
    const result = stack.select((v) => v > 3n);
    expect(typeof result.push).toBe("function");
    expect(result.size()).toBe(2);
  });

  it("reject returns MUTABLE", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n, 4n, 5n]);
    const result = stack.reject((v) => v > 3n);
    expect(typeof result.push).toBe("function");
    expect(result.size()).toBe(3);
  });

  it("find", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]); // top = 3n
    expect(stack.find((v) => v === 3n)).toBe(3n);
    expect(stack.find((v) => v === 99n)).toBeUndefined();
  });

  it("every / some", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]);
    expect(stack.every((v) => v < 100)).toBe(true);
    expect(stack.every((v) => v < 1n)).toBe(false);
    expect(stack.some((v) => v === 2n)).toBe(true);
    expect(stack.some((v) => v === 99n)).toBe(false);
  });

  it("anySatisfy / allSatisfy", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n]);
    expect(stack.anySatisfy((v) => v === 2n)).toBe(true);
    expect(stack.anySatisfy((v) => v === 99n)).toBe(false);
    expect(stack.allSatisfy((v) => v > 0n)).toBe(true);
  });

  it("count", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n, 4n, 5n]);
    expect(stack.count((v) => v > 3n)).toBe(2);
  });

  it("sum, min, max", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]);
    expect(stack.sum()).toBe(1n + 2n + 3n);
    expect(stack.min()).toBe(1n);
    expect(stack.max()).toBe(3n);
  });

  it("toArray top to bottom", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]); // top = 3n
    const arr = stack.toArray();
    expect(arr).toEqual([3n, 2n, 1n]); // top first
  });

  it("toMutable round-trip", () => {
    const original = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]);
    const mutable = original.toMutable();
    mutable.push(4n);
    expect(mutable.size()).toBe(4);
    expect(original.size()).toBe(3);
  });

  it("forEach top to bottom", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]);
    const collected: bigint[] = [];
    stack.forEach((v) => collected.push(v));
    expect(collected).toEqual([3n, 2n, 1n]); // top to bottom
  });

  it("map top to bottom", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]);
    const result = stack.map((v) => v * 2n);
    expect(result).toEqual([3n * 2n, 2n * 2n, 1n * 2n]);
  });

  it("filter top to bottom", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n, 4n]);
    const result = stack.filter((v) => v <= 3n);
    expect(result.length).toBe(3);
  });

  it("reduce top to bottom", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]);
    const sum = stack.reduce((acc, v) => acc + v, 0n);
    expect(sum).toBe(1n + 2n + 3n);
  });

  it("values iterator top to bottom", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]);
    const collected: bigint[] = [];
    for (const v of stack.values()) {
      collected.push(v);
    }
    expect(collected).toEqual([3n, 2n, 1n]);
  });

  it("Symbol.iterator top to bottom", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n]);
    const collected: bigint[] = [];
    for (const v of stack) {
      collected.push(v);
    }
    expect(collected).toEqual([2n, 1n]);
  });

  it("toString", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n]); // top = 2n
    const str = stack.toString();
    expect(str).not.toBe("");
    expect(str.includes("[")).toBe(true);
    expect(str.includes("]")).toBe(true);
  });

  it("memoryBytes", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n, 2n, 3n]);
    expect(stack.memoryBytes()).toBe(3 * 8);
  });

  it("defensive copy - modifying source array doesn't affect immutable", () => {
    const source = [1n, 2n, 3n];
    const stack = ImmutableBigInt64ArrayStack.of(source);
    source[0] = 99n as any;
    expect(stack.peek()).toBe(3n);
  });

  // Verify mutators are not available
  it("has no push method", () => {
    const stack = ImmutableBigInt64ArrayStack.of([1n]);
    // @ts-expect-error - push should not exist on immutable
    expect(stack.push).toBeUndefined();
  });
});
