// Code generated by mapdb-codegen. DO NOT EDIT.

import { Int8ArrayStack } from "./int8-array-stack";

/**
 * Immutable stack (LIFO) backed by Int8Array.
 * Elements: 1 bytes each, contiguous memory.
 * Construct via static of(values) or fromMutable(mutable).
 * Mutations create new instances; select/reject return MUTABLE.
 */
export class ImmutableInt8ArrayStack {
  private data: Int8Array;
  private _size: number;

  /** Creates an immutable stack from an array of values (defensive copy). Last element = top. */
  static of(values: number[]): ImmutableInt8ArrayStack {
    const size = values.length;
    const data = new Int8Array(size);
    data.set(values);
    return new ImmutableInt8ArrayStack(data, size);
  }

  /** Creates an immutable copy from a mutable stack (defensive copy). */
  static fromMutable(mutable: Int8ArrayStack): ImmutableInt8ArrayStack {
    const arr = mutable.toArray();
    const data = new Int8Array(arr.length);
    data.set(arr);
    return new ImmutableInt8ArrayStack(data, arr.length);
  }

  private constructor(data: Int8Array, size: number) {
    this.data = data;
    this._size = size;
  }

  /** Returns the top element without removing it. Throws if empty. */
  peek(): number {
    if (this._size === 0) {
      throw new Error("Stack is empty");
    }
    return this.data[this._size - 1];
  }

  /** Returns the element at the given distance from the top (0 = top). Throws if out of bounds. */
  peekAt(index: number): number {
    if (index < 0 || index >= this._size) {
      throw new RangeError(
        `Index ${index} out of bounds for stack size ${this._size}`,
      );
    }
    return this.data[this._size - 1 - index];
  }

  /** Returns the number of elements. */
  size(): number {
    return this._size;
  }

  /** Returns true if the stack is empty. */
  isEmpty(): boolean {
    return this._size === 0;
  }

  /** Returns true if the stack contains the given value. */
  contains(value: number): boolean {
    for (let i = 0; i < this._size; i++) {
      if (Object.is(this.data[i], value)) return true;
    }
    return false;
  }

  /** Alias for contains. */
  includes(value: number): boolean {
    return this.contains(value);
  }

  /** Returns a new MUTABLE stack with elements satisfying the predicate. */
  select(predicate: (value: number) => boolean): Int8ArrayStack {
    const result = new Int8ArrayStack();
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) {
        result.push(this.data[i]);
      }
    }
    return result;
  }

  /** Returns a new MUTABLE stack with elements NOT satisfying the predicate. */
  reject(predicate: (value: number) => boolean): Int8ArrayStack {
    const result = new Int8ArrayStack();
    for (let i = 0; i < this._size; i++) {
      if (!predicate(this.data[i])) {
        result.push(this.data[i]);
      }
    }
    return result;
  }

  /** Returns the first element (from top) satisfying the predicate, or undefined. */
  find(predicate: (value: number) => boolean): number | undefined {
    for (let i = this._size - 1; i >= 0; i--) {
      if (predicate(this.data[i])) return this.data[i];
    }
    return undefined;
  }

  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: number) => boolean): boolean {
    for (let i = 0; i < this._size; i++) {
      if (!predicate(this.data[i])) return false;
    }
    return true;
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: number) => boolean): boolean {
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) return true;
    }
    return false;
  }

  /** Returns true if any element satisfies the predicate. */
  anySatisfy(predicate: (value: number) => boolean): boolean {
    return this.some(predicate);
  }

  /** Returns true if all elements satisfy the predicate. */
  allSatisfy(predicate: (value: number) => boolean): boolean {
    return this.every(predicate);
  }

  /** Returns the number of elements satisfying the predicate. */
  count(predicate: (value: number) => boolean): number {
    let c = 0;
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) c++;
    }
    return c;
  }

  /** Returns the sum of all elements. */
  sum(): number {
    let s: number = 0 as number;
    for (let i = 0; i < this._size; i++) {
      s = ((s as any) + this.data[i]) as any as number;
    }
    return s;
  }

  /** Returns the minimum element, or undefined if empty. */
  min(): number | undefined {
    if (this._size === 0) return undefined;
    let m = this.data[0];
    for (let i = 1; i < this._size; i++) {
      if (this.data[i] < m) m = this.data[i];
    }
    return m;
  }

  /** Returns the maximum element, or undefined if empty. */
  max(): number | undefined {
    if (this._size === 0) return undefined;
    let m = this.data[0];
    for (let i = 1; i < this._size; i++) {
      if (this.data[i] > m) m = this.data[i];
    }
    return m;
  }

  /** Yields all values from top to bottom. */
  *values(): Generator<number> {
    for (let i = this._size - 1; i >= 0; i--) {
      yield this.data[i];
    }
  }

  /** Makes the stack iterable with for-of loops. Yields top to bottom. */
  *[Symbol.iterator](): IterableIterator<number> {
    for (let i = this._size - 1; i >= 0; i--) {
      yield this.data[i];
    }
  }

  /** Returns all elements as a new array (top element first). */
  toArray(): number[] {
    const result: number[] = [];
    for (let i = this._size - 1; i >= 0; i--) {
      result.push(this.data[i]);
    }
    return result;
  }

  /** Returns a mutable copy of this immutable stack. */
  toMutable(): Int8ArrayStack {
    return Int8ArrayStack.fromImmutable(this);
  }

  /** Calls the function for each element from top to bottom. */
  forEach(f: (value: number) => void): void {
    for (let i = this._size - 1; i >= 0; i--) {
      f(this.data[i]);
    }
  }

  /** Returns a new array with the results of calling f on each element (top to bottom). */
  map<U>(f: (value: number) => U): U[] {
    const result: U[] = [];
    for (let i = this._size - 1; i >= 0; i--) {
      result.push(f(this.data[i]));
    }
    return result;
  }

  /** Returns a new array with elements satisfying the predicate (top to bottom). */
  filter(predicate: (value: number) => boolean): number[] {
    const result: number[] = [];
    for (let i = this._size - 1; i >= 0; i--) {
      if (predicate(this.data[i])) result.push(this.data[i]);
    }
    return result;
  }

  /** Reduces the stack to a single value using the accumulator function (top to bottom). */
  reduce<U>(f: (acc: U, value: number) => U, initial: U): U {
    let acc = initial;
    for (let i = this._size - 1; i >= 0; i--) {
      acc = f(acc, this.data[i]);
    }
    return acc;
  }

  /** Returns a string representation (top element first). */
  toString(): string {
    const parts: string[] = [];
    for (let i = this._size - 1; i >= 0; i--) {
      parts.push(`${this.data[i]}`);
    }
    return `[${parts.join(", ")}]`;
  }

  /** Memory used by the backing TypedArray in bytes. */
  memoryBytes(): number {
    return this.data.byteLength;
  }
}
