// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { Int8ArrayStack } from "./int8-array-stack.js";

describe("Int8ArrayStack generated", () => {
  it("push and pop", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    expect(s.size()).toBe(3);
    expect(s.pop()).toBe(3);
    expect(s.pop()).toBe(2);
    expect(s.pop()).toBe(1);
  });

  it("peek", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    expect(s.peek()).toBe(2);
    expect(s.size()).toBe(2); // peek doesn't remove
  });

  it("peekAt", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    expect(s.peekAt(0)).toBe(3); // top
    expect(s.peekAt(1)).toBe(2);
    expect(s.peekAt(2)).toBe(1); // bottom
  });

  it("pop on empty throws", () => {
    const s = new Int8ArrayStack();
    expect(() => s.pop()).toThrow();
  });

  it("contains", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    expect(s.contains(1)).toBe(true);
    expect(s.contains(2)).toBe(true);
    expect(s.contains(99)).toBe(false);
  });

  it("includes alias for contains", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    expect(s.includes(1)).toBe(true);
    expect(s.includes(99)).toBe(false);
  });

  it("isEmpty and clear", () => {
    const s = new Int8ArrayStack();
    expect(s.isEmpty()).toBe(true);
    s.push(1);
    expect(s.isEmpty()).toBe(false);
    s.clear();
    expect(s.size()).toBe(0);
    expect(s.isEmpty()).toBe(true);
  });

  it("select", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    s.push(4);
    s.push(5);
    // select preserves order (but stack reversal means bottom-to-top becomes top-to-bottom in result)
    const result = s.select((v) => v > 3);
    expect(result.size()).toBe(2);
  });

  it("reject", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    s.push(4);
    s.push(5);
    expect(s.reject((v) => v > 3).size()).toBe(3);
  });

  it("find", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    expect(s.find((v) => v === 2)).toBe(2);
    expect(s.find((v) => v === 99)).toBeUndefined();
  });

  it("every", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    expect(s.every((v) => v < 100)).toBe(true);
    expect(s.every((v) => v < 1)).toBe(false);
  });

  it("some", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    expect(s.some((v) => v === 2)).toBe(true);
    expect(s.some((v) => v === 99)).toBe(false);
  });

  it("anySatisfy / allSatisfy", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    expect(s.anySatisfy((v) => v === 2)).toBe(true);
    expect(s.anySatisfy((v) => v === 99)).toBe(false);
    expect(s.allSatisfy((v) => v > 0)).toBe(true);
  });

  it("count", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    s.push(4);
    s.push(5);
    expect(s.count((v) => v > 3)).toBe(2);
  });

  it("sum, min, max", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    expect(s.sum()).toBe(1 + 2 + 3);
    expect(s.min()).toBe(1);
    expect(s.max()).toBe(3);
  });

  it("map", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    // Use explicit bigint literal (2n) for multiplication with bigint values
    const two = 2;
    const result = s.map((v) => v * two);
    const expected = [3 * two, 2 * two, 1 * two];
    expect(result).toEqual(expected); // top to bottom
  });

  it("filter", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    s.push(4);
    const result = s.filter((v) => v <= 3);
    expect(result.length).toBe(3);
  });

  it("reduce", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    const sum = s.reduce((acc, v) => acc + v, 0);
    expect(sum).toBe(1 + 2 + 3);
  });

  it("forEach", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    const collected: number[] = [];
    s.forEach((v) => collected.push(v));
    // forEach goes top to bottom
    expect(collected).toEqual([3, 2, 1]);
  });

  it("resize", () => {
    const s = new Int8ArrayStack();
    for (let i = 0; i < 100; i += 1) s.push(i);
    expect(s.size()).toBe(100);
  });

  it("memoryBytes", () => {
    const s = new Int8ArrayStack(64);
    expect(s.memoryBytes()).toBe(64 * 1);
  });

  it("toString", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    expect(s.toString()).not.toBe("");
  });

  it("toArray", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    const arr = s.toArray();
    expect(arr).toEqual([3, 2, 1]); // top first
  });

  it("values iterator", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    const collected: number[] = [];
    for (const v of s.values()) {
      collected.push(v);
    }
    expect(collected).toEqual([3, 2, 1]); // top to bottom
  });

  it("Symbol.iterator", () => {
    const s = new Int8ArrayStack();
    s.push(1);
    s.push(2);
    const collected: number[] = [];
    for (const v of s) {
      collected.push(v);
    }
    expect(collected).toEqual([2, 1]); // top to bottom
  });

  it("of factory", () => {
    const s = Int8ArrayStack.of([1, 2, 3]); // last element is top
    expect(s.size()).toBe(3);
    expect(s.peek()).toBe(3);
    expect(s.pop()).toBe(3);
    expect(s.pop()).toBe(2);
    expect(s.pop()).toBe(1);
  });
});
