// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigInt64HashBag } from "./bigint64-hash-bag.js";

describe("BigInt64HashBag generated", () => {
  it("add and occurrences", () => {
    const b = new BigInt64HashBag();
    b.add(1n);
    b.add(1n);
    b.add(2n);
    expect(b.occurrencesOf(1n)).toBe(2);
    expect(b.occurrencesOf(2n)).toBe(1);
    expect(b.size()).toBe(3);
    expect(b.sizeDistinct()).toBe(2);
  });
  it("remove and removeAll", () => {
    const b = new BigInt64HashBag();
    b.add(1n);
    b.add(1n);
    b.add(1n);
    b.remove(1n);
    expect(b.occurrencesOf(1n)).toBe(2);
    b.removeAll(1n);
    expect(b.contains(1n)).toBe(false);
  });
  it("isEmpty and clear", () => {
    const b = new BigInt64HashBag();
    expect(b.isEmpty()).toBe(true);
    b.add(1n);
    b.clear();
    expect(b.isEmpty()).toBe(true);
  });
  it("forEachWithOccurrences", () => {
    const b = new BigInt64HashBag();
    b.add(1n);
    b.add(1n);
    b.add(2n);
    let total = 0;
    b.forEachWithOccurrences((_v, c) => {
      total += c;
    });
    expect(total).toBe(3);
  });
  it("select", () => {
    const b = new BigInt64HashBag();
    b.add(1n);
    b.add(2n);
    b.add(3n);
    expect(b.select((v) => v > 1n).size()).toBe(2);
  });
  it("toString", () => {
    const b = new BigInt64HashBag();
    b.add(1n);
    expect(b.toString()).not.toBe("");
  });
});
