// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { Int32HashBag } from "./int32-hash-bag.js";

describe("Int32HashBag generated", () => {
  it("add and occurrences", () => {
    const b = new Int32HashBag();
    b.add(1);
    b.add(1);
    b.add(2);
    expect(b.occurrencesOf(1)).toBe(2);
    expect(b.occurrencesOf(2)).toBe(1);
    expect(b.size()).toBe(3);
    expect(b.sizeDistinct()).toBe(2);
  });
  it("remove and removeAll", () => {
    const b = new Int32HashBag();
    b.add(1);
    b.add(1);
    b.add(1);
    b.remove(1);
    expect(b.occurrencesOf(1)).toBe(2);
    b.removeAll(1);
    expect(b.contains(1)).toBe(false);
  });
  it("isEmpty and clear", () => {
    const b = new Int32HashBag();
    expect(b.isEmpty()).toBe(true);
    b.add(1);
    b.clear();
    expect(b.isEmpty()).toBe(true);
  });
  it("forEachWithOccurrences", () => {
    const b = new Int32HashBag();
    b.add(1);
    b.add(1);
    b.add(2);
    let total = 0;
    b.forEachWithOccurrences((_v, c) => {
      total += c;
    });
    expect(total).toBe(3);
  });
  it("select", () => {
    const b = new Int32HashBag();
    b.add(1);
    b.add(2);
    b.add(3);
    expect(b.select((v) => v > 1).size()).toBe(2);
  });
  it("toString", () => {
    const b = new Int32HashBag();
    b.add(1);
    expect(b.toString()).not.toBe("");
  });
});
