// Code generated by mapdb-codegen. DO NOT EDIT.

/**
 * Min-heap priority queue for bigint values, backed by a binary heap over
 * an array. O(log n) push/pop, O(1) peek.
 */
export class BigIntPriorityQueue {
  private data: bigint[];

  constructor() {
    this.data = [];
  }

  /** Creates a new priority queue and heapifies the given values in O(n). */
  static of(values: bigint[]): BigIntPriorityQueue {
    const q = new BigIntPriorityQueue();
    q.data = values.slice();
    if (q.data.length > 1) {
      for (let i = Math.floor(q.data.length / 2) - 1; i >= 0; i--) {
        q.siftDown(i);
      }
    }
    return q;
  }

  /** Pushes a value onto the heap. O(log n). */
  push(value: bigint): void {
    this.data.push(value);
    this.siftUp(this.data.length - 1);
  }

  /** Removes and returns the smallest element, or undefined if empty. O(log n). */
  pop(): bigint | undefined {
    if (this.data.length === 0) return undefined;
    const top = this.data[0];
    const last = this.data.pop()!;
    if (this.data.length > 0) {
      this.data[0] = last;
      this.siftDown(0);
    }
    return top;
  }

  /** Returns the smallest element without removing it, or undefined if empty. */
  peek(): bigint | undefined {
    return this.data.length === 0 ? undefined : this.data[0];
  }

  get size(): number {
    return this.data.length;
  }
  get isEmpty(): boolean {
    return this.data.length === 0;
  }
  clear(): void {
    this.data.length = 0;
  }

  /** Returns true if the heap contains the given value. O(n). */
  contains(value: bigint): boolean {
    for (let i = 0; i < this.data.length; i++) {
      if (this.data[i] === value) return true;
    }
    return false;
  }

  /** Returns a copy of the internal heap array (NOT sorted). */
  toArray(): bigint[] {
    return this.data.slice();
  }

  /** Pops all elements into an array in ascending order, consuming the queue. */
  drainSorted(): bigint[] {
    const out: bigint[] = [];
    while (this.data.length > 0) {
      out.push(this.pop()!);
    }
    return out;
  }

  /** Returns a string representation in heap-array order. */
  toString(): string {
    return `[${this.data.join(", ")}]`;
  }

  /** Yields values in heap-array order. */
  *[Symbol.iterator](): Generator<bigint> {
    for (let i = 0; i < this.data.length; i++) yield this.data[i];
  }

  private siftUp(start: number): void {
    let i = start;
    while (i > 0) {
      const parent = (i - 1) >> 1;
      if (this.data[i] < this.data[parent]) {
        const tmp = this.data[i];
        this.data[i] = this.data[parent];
        this.data[parent] = tmp;
        i = parent;
      } else {
        break;
      }
    }
  }

  private siftDown(start: number): void {
    let i = start;
    const n = this.data.length;
    while (true) {
      const left = 2 * i + 1;
      if (left >= n) break;
      const right = left + 1;
      let best = left;
      if (right < n && this.data[right] < this.data[left]) best = right;
      if (this.data[best] < this.data[i]) {
        const tmp = this.data[best];
        this.data[best] = this.data[i];
        this.data[i] = tmp;
        i = best;
      } else {
        break;
      }
    }
  }
}
