// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntPriorityQueue } from "./bigint-priority-queue.js";

describe("BigIntPriorityQueue generated", () => {
  it("push and peek", () => {
    const q = new BigIntPriorityQueue();
    q.push(2n);
    q.push(1n);
    q.push(3n);
    expect(q.size).toBe(3);
    expect(q.peek()).toBe(1n); // min element
  });

  it("of", () => {
    const q = BigIntPriorityQueue.of([3n, 1n, 2n]);
    expect(q.size).toBe(3);
    expect(q.peek()).toBe(1n); // heapified, min at root
  });

  it("pop", () => {
    const q = BigIntPriorityQueue.of([3n, 1n, 2n]);
    const first = q.pop();
    expect(first).toBe(1n);
    expect(q.size).toBe(2);
    const second = q.pop();
    expect(second).toBe(2n);
  });

  it("pop on empty returns undefined", () => {
    const q = new BigIntPriorityQueue();
    expect(q.pop()).toBeUndefined();
    expect(q.peek()).toBeUndefined();
  });

  it("isEmpty and clear", () => {
    const q = new BigIntPriorityQueue();
    expect(q.isEmpty).toBe(true);
    q.push(1n);
    expect(q.isEmpty).toBe(false);
    q.clear();
    expect(q.size).toBe(0);
    expect(q.isEmpty).toBe(true);
  });

  it("contains", () => {
    const q = BigIntPriorityQueue.of([1n, 2n, 3n]);
    expect(q.contains(2n)).toBe(true);
    expect(q.contains(99n)).toBe(false);
  });

  it("toArray returns heap order", () => {
    const q = BigIntPriorityQueue.of([3n, 1n, 2n]);
    const arr = q.toArray();
    expect(arr.length).toBe(3);
    // Heap order not sorted, but should contain all elements
    expect(arr).toContain(1n);
    expect(arr).toContain(2n);
    expect(arr).toContain(3n);
  });

  it("drainSorted returns sorted order", () => {
    const q = BigIntPriorityQueue.of([3n, 1n, 2n]);
    const sorted = q.drainSorted();
    expect(sorted).toEqual([1n, 2n, 3n]);
    expect(q.isEmpty).toBe(true);
  });

  it("toString", () => {
    const q = BigIntPriorityQueue.of([1n, 2n]);
    expect(q.toString()).not.toBe("");
  });

  it("Symbol.iterator", () => {
    const q = BigIntPriorityQueue.of([1n, 2n, 3n]);
    const values = [...q];
    expect(values.length).toBe(3);
  });

  it("large priority queue operations", () => {
    const q = new BigIntPriorityQueue();
    for (let i = 100; i >= 0; i--) {
      q.push(i); // push in reverse order
    }
    expect(q.size).toBe(101);
    expect(q.peek()).toBe(0);
    // Pop all and verify ascending order
    const results: number[] = [];
    while (!q.isEmpty) {
      results.push(q.pop()!);
    }
    for (let i = 0; i < results.length - 1; i++) {
      expect(results[i] <= results[i + 1]).toBe(true);
    }
  });
});
