// Code generated by mapdb-codegen. DO NOT EDIT.
import { NumberPriorityQueue } from "./number-priority-queue.js";

/**
 * Immutable min-heap priority queue for number values.
 * Wraps a mutable NumberPriorityQueue, exposing only read-only operations.
 * Persistent operations (push/pop) return new immutable queues.
 */
export class ImmutableNumberPriorityQueue {
  private readonly delegate: NumberPriorityQueue;

  constructor(source: NumberPriorityQueue) {
    // Copy all entries into a fresh mutable queue so the caller cannot mutate our data.
    this.delegate = new NumberPriorityQueue();
    for (const v of source.toArray()) {
      this.delegate.push(v);
    }
  }

  /** Creates an immutable priority queue from an array of values (heapified in O(n)). */
  static of(values: number[]): ImmutableNumberPriorityQueue {
    return new ImmutableNumberPriorityQueue(NumberPriorityQueue.of(values));
  }

  /** Returns the smallest element without removing it. Returns undefined if empty. */
  peek(): number | undefined {
    return this.delegate.peek();
  }

  /** Returns the number of elements. */
  get size(): number {
    return this.delegate.size;
  }

  /** Returns true if the queue has no elements. */
  get isEmpty(): boolean {
    return this.delegate.isEmpty;
  }

  /** Returns true if the queue contains the given value. O(n). */
  contains(value: number): boolean {
    return this.delegate.contains(value);
  }

  /** Returns a copy of the internal heap array (NOT sorted). */
  toArray(): number[] {
    return this.delegate.toArray();
  }

  /** Returns a NEW immutable queue with the value inserted. O(log n). */
  push(value: number): ImmutableNumberPriorityQueue {
    const copy = this.toMutable();
    copy.push(value);
    return new ImmutableNumberPriorityQueue(copy);
  }

  /** Returns a tuple [newQueue, poppedValue] with the smallest element removed. Returns undefined if empty. O(log n). */
  pop(): [ImmutableNumberPriorityQueue, number] | undefined {
    if (this.delegate.isEmpty) return undefined;
    const copy = this.toMutable();
    const value = copy.pop()!;
    return [new ImmutableNumberPriorityQueue(copy), value];
  }

  /** Returns a string representation in heap-array order. */
  toString(): string {
    return this.delegate.toString();
  }

  /** Makes the queue iterable with for-of loops. */
  *[Symbol.iterator](): IterableIterator<number> {
    yield* this.delegate[Symbol.iterator]();
  }

  /** Returns a new mutable copy of this queue. */
  toMutable(): NumberPriorityQueue {
    return NumberPriorityQueue.of(this.delegate.toArray());
  }
}
