// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberPriorityQueue } from "./number-priority-queue.js";
import { ImmutableNumberPriorityQueue } from "./immutable-number-priority-queue.js";

describe("ImmutableNumberPriorityQueue generated", () => {
  it("of heapifies and peek returns minimum", () => {
    const im = ImmutableNumberPriorityQueue.of([3, 1, 2]);
    expect(im.size).toBe(3);
    // For bool, v[0]=true so min is false (v[1]); only assert presence.
    expect(im.peek()).toBeDefined();
  });

  it("push returns new queue, original untouched", () => {
    const im = ImmutableNumberPriorityQueue.of([3]);
    const im2 = im.push(1);
    expect(im.size).toBe(1);
    expect(im2.size).toBe(2);
  });

  it("pop returns [newQueue, value]", () => {
    const im = ImmutableNumberPriorityQueue.of([1, 2, 3]);
    const r = im.pop()!;
    expect(r).toBeDefined();
    expect(r[0].size).toBe(2);
    expect(im.size).toBe(3);
  });

  it("pop on empty returns undefined", () => {
    expect(ImmutableNumberPriorityQueue.of([]).pop()).toBeUndefined();
  });

  it("contains and isEmpty", () => {
    const im = ImmutableNumberPriorityQueue.of([1]);
    expect(im.contains(1)).toBe(true);
    expect(im.isEmpty).toBe(false);
    expect(ImmutableNumberPriorityQueue.of([]).isEmpty).toBe(true);
  });

  it("toMutable does not affect immutable", () => {
    const im = ImmutableNumberPriorityQueue.of([1]);
    im.toMutable().push(2);
    expect(im.size).toBe(1);
  });

  it("iterator yields heap-array order (length only)", () => {
    const im = ImmutableNumberPriorityQueue.of([1, 2]);
    let count = 0;
    for (const _ of im) count++;
    expect(count).toBe(2);
  });
});
