// Code generated by mapdb-codegen. DO NOT EDIT.
import { BigIntPriorityQueue } from "./bigint-priority-queue.js";

/**
 * Immutable min-heap priority queue for bigint values.
 * Wraps a mutable BigIntPriorityQueue, exposing only read-only operations.
 * Persistent operations (push/pop) return new immutable queues.
 */
export class ImmutableBigIntPriorityQueue {
  private readonly delegate: BigIntPriorityQueue;

  constructor(source: BigIntPriorityQueue) {
    // Copy all entries into a fresh mutable queue so the caller cannot mutate our data.
    this.delegate = new BigIntPriorityQueue();
    for (const v of source.toArray()) {
      this.delegate.push(v);
    }
  }

  /** Creates an immutable priority queue from an array of values (heapified in O(n)). */
  static of(values: bigint[]): ImmutableBigIntPriorityQueue {
    return new ImmutableBigIntPriorityQueue(BigIntPriorityQueue.of(values));
  }

  /** Returns the smallest element without removing it. Returns undefined if empty. */
  peek(): bigint | undefined {
    return this.delegate.peek();
  }

  /** Returns the number of elements. */
  get size(): number {
    return this.delegate.size;
  }

  /** Returns true if the queue has no elements. */
  get isEmpty(): boolean {
    return this.delegate.isEmpty;
  }

  /** Returns true if the queue contains the given value. O(n). */
  contains(value: bigint): boolean {
    return this.delegate.contains(value);
  }

  /** Returns a copy of the internal heap array (NOT sorted). */
  toArray(): bigint[] {
    return this.delegate.toArray();
  }

  /** Returns a NEW immutable queue with the value inserted. O(log n). */
  push(value: bigint): ImmutableBigIntPriorityQueue {
    const copy = this.toMutable();
    copy.push(value);
    return new ImmutableBigIntPriorityQueue(copy);
  }

  /** Returns a tuple [newQueue, poppedValue] with the smallest element removed. Returns undefined if empty. O(log n). */
  pop(): [ImmutableBigIntPriorityQueue, bigint] | undefined {
    if (this.delegate.isEmpty) return undefined;
    const copy = this.toMutable();
    const value = copy.pop()!;
    return [new ImmutableBigIntPriorityQueue(copy), value];
  }

  /** Returns a string representation in heap-array order. */
  toString(): string {
    return this.delegate.toString();
  }

  /** Makes the queue iterable with for-of loops. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    yield* this.delegate[Symbol.iterator]();
  }

  /** Returns a new mutable copy of this queue. */
  toMutable(): BigIntPriorityQueue {
    return BigIntPriorityQueue.of(this.delegate.toArray());
  }
}
