// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberPriorityQueue } from "./number-priority-queue.js";

describe("NumberPriorityQueue generated", () => {
  it("push and peek", () => {
    const q = new NumberPriorityQueue();
    q.push(2);
    q.push(1);
    q.push(3);
    expect(q.size).toBe(3);
    expect(q.peek()).toBe(1); // min element
  });

  it("of", () => {
    const q = NumberPriorityQueue.of([3, 1, 2]);
    expect(q.size).toBe(3);
    expect(q.peek()).toBe(1); // heapified, min at root
  });

  it("pop", () => {
    const q = NumberPriorityQueue.of([3, 1, 2]);
    const first = q.pop();
    expect(first).toBe(1);
    expect(q.size).toBe(2);
    const second = q.pop();
    expect(second).toBe(2);
  });

  it("pop on empty returns undefined", () => {
    const q = new NumberPriorityQueue();
    expect(q.pop()).toBeUndefined();
    expect(q.peek()).toBeUndefined();
  });

  it("isEmpty and clear", () => {
    const q = new NumberPriorityQueue();
    expect(q.isEmpty).toBe(true);
    q.push(1);
    expect(q.isEmpty).toBe(false);
    q.clear();
    expect(q.size).toBe(0);
    expect(q.isEmpty).toBe(true);
  });

  it("contains", () => {
    const q = NumberPriorityQueue.of([1, 2, 3]);
    expect(q.contains(2)).toBe(true);
    expect(q.contains(99)).toBe(false);
  });

  it("toArray returns heap order", () => {
    const q = NumberPriorityQueue.of([3, 1, 2]);
    const arr = q.toArray();
    expect(arr.length).toBe(3);
    // Heap order not sorted, but should contain all elements
    expect(arr).toContain(1);
    expect(arr).toContain(2);
    expect(arr).toContain(3);
  });

  it("drainSorted returns sorted order", () => {
    const q = NumberPriorityQueue.of([3, 1, 2]);
    const sorted = q.drainSorted();
    expect(sorted).toEqual([1, 2, 3]);
    expect(q.isEmpty).toBe(true);
  });

  it("toString", () => {
    const q = NumberPriorityQueue.of([1, 2]);
    expect(q.toString()).not.toBe("");
  });

  it("Symbol.iterator", () => {
    const q = NumberPriorityQueue.of([1, 2, 3]);
    const values = [...q];
    expect(values.length).toBe(3);
  });

  it("large priority queue operations", () => {
    const q = new NumberPriorityQueue();
    for (let i = 100; i >= 0; i--) {
      q.push(i); // push in reverse order
    }
    expect(q.size).toBe(101);
    expect(q.peek()).toBe(0);
    // Pop all and verify ascending order
    const results: number[] = [];
    while (!q.isEmpty) {
      results.push(q.pop()!);
    }
    for (let i = 0; i < results.length - 1; i++) {
      expect(results[i] <= results[i + 1]).toBe(true);
    }
  });
});
