// Code generated by mapdb-codegen. DO NOT EDIT.
const RED = false;
const BLACK = true;

interface TreeNode {
  key: bigint;
  count: number;
  left: TreeNode | null;
  right: TreeNode | null;
  parent: TreeNode | null;
  color: boolean;
}

/** Sorted bag (multiset) of bigint values, backed by a red-black tree. */
export class BigIntTreeBag {
  private root: TreeNode | null = null;
  private _size = 0;
  private _distinctSize = 0;

  static of(values: bigint[]): BigIntTreeBag {
    const bag = new BigIntTreeBag();
    for (const v of values) bag.add(v);
    return bag;
  }

  /** Add one occurrence of the value. */
  add(value: bigint): void {
    if (this.root === null) {
      this.root = {
        key: value,
        count: 1,
        left: null,
        right: null,
        parent: null,
        color: BLACK,
      };
      this._size++;
      this._distinctSize++;
      return;
    }
    let node = this.root;
    while (true) {
      if (value < node.key) {
        if (!node.left) {
          node.left = {
            key: value,
            count: 1,
            left: null,
            right: null,
            parent: node,
            color: RED,
          };
          this.fixInsert(node.left);
          this._size++;
          this._distinctSize++;
          return;
        }
        node = node.left;
      } else if (value > node.key) {
        if (!node.right) {
          node.right = {
            key: value,
            count: 1,
            left: null,
            right: null,
            parent: node,
            color: RED,
          };
          this.fixInsert(node.right);
          this._size++;
          this._distinctSize++;
          return;
        }
        node = node.right;
      } else {
        node.count++;
        this._size++;
        return;
      }
    }
  }

  /** Remove one occurrence. Returns true if the value was present. */
  remove(value: bigint): boolean {
    const node = this.findNode(value);
    if (!node) return false;
    if (node.count > 1) {
      node.count--;
      this._size--;
    } else {
      this._size--;
      this._distinctSize--;
      this.deleteNode(node);
    }
    return true;
  }

  /** Remove all occurrences of the value. Returns true if the value was present. */
  removeAll(value: bigint): boolean {
    const node = this.findNode(value);
    if (!node) return false;
    this._size -= node.count;
    this._distinctSize--;
    this.deleteNode(node);
    return true;
  }

  /** Return the number of occurrences of the value. */
  occurrencesOf(value: bigint): number {
    const node = this.findNode(value);
    return node ? node.count : 0;
  }

  contains(value: bigint): boolean {
    return this.findNode(value) !== null;
  }

  /** Total count including duplicates. */
  get size(): number {
    return this._size;
  }

  /** Number of unique values. */
  get sizeDistinct(): number {
    return this._distinctSize;
  }

  get isEmpty(): boolean {
    return this._size === 0;
  }

  clear(): void {
    this.root = null;
    this._size = 0;
    this._distinctSize = 0;
  }

  min(): bigint | undefined {
    if (!this.root) return undefined;
    let n = this.root;
    while (n.left) n = n.left;
    return n.key;
  }

  max(): bigint | undefined {
    if (!this.root) return undefined;
    let n = this.root;
    while (n.right) n = n.right;
    return n.key;
  }

  /** Iterate values in sorted order, yielding each value once per occurrence. */
  forEach(fn: (value: bigint) => void): void {
    const walk = (node: TreeNode | null): void => {
      if (!node) return;
      walk(node.left);
      for (let i = 0; i < node.count; i++) fn(node.key);
      walk(node.right);
    };
    walk(this.root);
  }

  /** Iterate distinct values in sorted order, passing each value and its count. */
  forEachWithOccurrences(fn: (value: bigint, count: number) => void): void {
    const walk = (node: TreeNode | null): void => {
      if (!node) return;
      walk(node.left);
      fn(node.key, node.count);
      walk(node.right);
    };
    walk(this.root);
  }

  /** Returns a new bag with values satisfying the predicate (preserving counts). */
  select(predicate: (value: bigint) => boolean): BigIntTreeBag {
    const result = new BigIntTreeBag();
    this.forEachWithOccurrences((value, count) => {
      if (predicate(value)) {
        for (let i = 0; i < count; i++) result.add(value);
      }
    });
    return result;
  }

  /** Returns a new bag with values not satisfying the predicate (preserving counts). */
  reject(predicate: (value: bigint) => boolean): BigIntTreeBag {
    return this.select((v) => !predicate(v));
  }

  /** Returns a sorted array of all values including duplicates. */
  toArray(): bigint[] {
    const arr: bigint[] = [];
    this.forEach((v) => arr.push(v));
    return arr;
  }

  /** Returns a string like "{1x2, 3x1}". */
  toString(): string {
    const parts: string[] = [];
    this.forEachWithOccurrences((value, count) => {
      parts.push(`${value}x${count}`);
    });
    return `{${parts.join(", ")}}`;
  }

  /** Yields values with duplicates in sorted order. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    function* inorder(node: TreeNode | null): Generator<bigint> {
      if (!node) return;
      yield* inorder(node.left);
      for (let i = 0; i < node.count; i++) yield node.key;
      yield* inorder(node.right);
    }
    yield* inorder(this.root);
  }

  // --- TS-idiomatic aliases ---

  /** Alias for `select`. */
  filter(predicate: (value: bigint) => boolean): BigIntTreeBag {
    return this.select(predicate);
  }

  /** Returns the first (smallest) element satisfying the predicate, or undefined. */
  find(predicate: (value: bigint) => boolean): bigint | undefined {
    for (const v of this) if (predicate(v)) return v;
    return undefined;
  }

  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: bigint) => boolean): boolean {
    for (const v of this) if (!predicate(v)) return false;
    return true;
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: bigint) => boolean): boolean {
    for (const v of this) if (predicate(v)) return true;
    return false;
  }

  /** Reduces the bag to a single value using the accumulator function (in sorted order, with duplicates). */
  reduce<U>(fn: (acc: U, value: bigint) => U, initial: U): U {
    let acc = initial;
    for (const v of this) acc = fn(acc, v);
    return acc;
  }

  /** Returns true if the bag contains the value. Alias for `contains`. */
  includes(value: bigint): boolean {
    return this.contains(value);
  }

  /** Returns a new array with the results of calling `fn` on each element (in sorted order, with duplicates). */
  map<U>(fn: (value: bigint) => U): U[] {
    const result: U[] = [];
    for (const v of this) result.push(fn(v));
    return result;
  }

  // --- RB tree internals ---
  private findNode(key: bigint): TreeNode | null {
    let n = this.root;
    while (n) {
      if (key < n.key) n = n.left;
      else if (key > n.key) n = n.right;
      else return n;
    }
    return null;
  }
  private rotateLeft(x: TreeNode): void {
    const y = x.right!;
    x.right = y.left;
    if (y.left) y.left.parent = x;
    y.parent = x.parent;
    if (!x.parent) this.root = y;
    else if (x === x.parent.left) x.parent.left = y;
    else x.parent.right = y;
    y.left = x;
    x.parent = y;
  }
  private rotateRight(x: TreeNode): void {
    const y = x.left!;
    x.left = y.right;
    if (y.right) y.right.parent = x;
    y.parent = x.parent;
    if (!x.parent) this.root = y;
    else if (x === x.parent.right) x.parent.right = y;
    else x.parent.left = y;
    y.right = x;
    x.parent = y;
  }
  private fixInsert(z: TreeNode): void {
    while (z.parent && z.parent.color === RED) {
      if (z.parent === z.parent.parent!.left) {
        const y = z.parent.parent!.right;
        if (y && y.color === RED) {
          z.parent.color = BLACK;
          y.color = BLACK;
          z.parent.parent!.color = RED;
          z = z.parent.parent!;
        } else {
          if (z === z.parent.right) {
            z = z.parent;
            this.rotateLeft(z);
          }
          z.parent!.color = BLACK;
          z.parent!.parent!.color = RED;
          this.rotateRight(z.parent!.parent!);
        }
      } else {
        const y = z.parent.parent!.left;
        if (y && y.color === RED) {
          z.parent.color = BLACK;
          y.color = BLACK;
          z.parent.parent!.color = RED;
          z = z.parent.parent!;
        } else {
          if (z === z.parent.left) {
            z = z.parent;
            this.rotateRight(z);
          }
          z.parent!.color = BLACK;
          z.parent!.parent!.color = RED;
          this.rotateLeft(z.parent!.parent!);
        }
      }
    }
    this.root!.color = BLACK;
  }
  private deleteNode(z: TreeNode): void {
    if (z.left && z.right) {
      let s = z.right;
      while (s.left) s = s.left;
      z.key = s.key;
      z.count = s.count;
      z = s;
    }
    const child = z.left ?? z.right;
    if (child) {
      child.parent = z.parent;
      if (!z.parent) this.root = child;
      else if (z === z.parent.left) z.parent.left = child;
      else z.parent.right = child;
      if (z.color === BLACK) this.fixDelete(child);
    } else if (!z.parent) {
      this.root = null;
    } else {
      if (z.color === BLACK) this.fixDelete(z);
      if (z.parent) {
        if (z === z.parent.left) z.parent.left = null;
        else z.parent.right = null;
      }
    }
  }
  private fixDelete(x: TreeNode): void {
    while (x !== this.root && x.color === BLACK) {
      if (x === x.parent!.left) {
        let w = x.parent!.right;
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (w.color === RED) {
          w.color = BLACK;
          x.parent!.color = RED;
          this.rotateLeft(x.parent!);
          w = x.parent!.right;
        }
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (
          (!w.left || w.left.color === BLACK) &&
          (!w.right || w.right.color === BLACK)
        ) {
          w.color = RED;
          x = x.parent!;
        } else {
          if (!w.right || w.right.color === BLACK) {
            if (w.left) w.left.color = BLACK;
            w.color = RED;
            this.rotateRight(w);
            w = x.parent!.right!;
          }
          w.color = x.parent!.color;
          x.parent!.color = BLACK;
          if (w.right) w.right.color = BLACK;
          this.rotateLeft(x.parent!);
          x = this.root!;
        }
      } else {
        let w = x.parent!.left;
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (w.color === RED) {
          w.color = BLACK;
          x.parent!.color = RED;
          this.rotateRight(x.parent!);
          w = x.parent!.left;
        }
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (
          (!w.left || w.left.color === BLACK) &&
          (!w.right || w.right.color === BLACK)
        ) {
          w.color = RED;
          x = x.parent!;
        } else {
          if (!w.left || w.left.color === BLACK) {
            if (w.right) w.right.color = BLACK;
            w.color = RED;
            this.rotateLeft(w);
            w = x.parent!.left!;
          }
          w.color = x.parent!.color;
          x.parent!.color = BLACK;
          if (w.left) w.left.color = BLACK;
          this.rotateRight(x.parent!);
          x = this.root!;
        }
      }
    }
    x.color = BLACK;
  }
}
