// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigInt64Int16HashMap } from "./bigint64-int16-hash-map.js";

describe("BigInt64Int16HashMap generated", () => {
  it("put and get", () => {
    const m = new BigInt64Int16HashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    m.put(3n, 3);
    expect(m.get(1n)).toBe(1);
    expect(m.get(99n)).toBeUndefined();
    expect(m.size()).toBe(3);
  });
  it("put overwrite", () => {
    const m = new BigInt64Int16HashMap();
    m.put(1n, 1);
    const old = m.put(1n, 2);
    expect(old).toBe(1);
    expect(m.get(1n)).toBe(2);
  });
  it("remove", () => {
    const m = new BigInt64Int16HashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    expect(m.remove(1n)).toBe(1);
    expect(m.size()).toBe(1);
    expect(m.containsKey(1n)).toBe(false);
  });
  it("getOrDefault", () => {
    const m = new BigInt64Int16HashMap();
    m.put(1n, 1);
    expect(m.getOrDefault(1n, 3)).toBe(1);
    expect(m.getOrDefault(99n, 3)).toBe(3);
  });
  it("isEmpty and clear", () => {
    const m = new BigInt64Int16HashMap();
    expect(m.isEmpty()).toBe(true);
    m.put(1n, 1);
    expect(m.isEmpty()).toBe(false);
    m.clear();
    expect(m.isEmpty()).toBe(true);
  });
  it("select", () => {
    const m = new BigInt64Int16HashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    m.put(3n, 3);
    expect(m.select((_k, v) => v > 1).size()).toBe(2);
  });
  it("anySatisfy / allSatisfy", () => {
    const m = new BigInt64Int16HashMap();
    m.put(1n, 1);
    m.put(2n, 2);
    expect(m.anySatisfy((_k, v) => v === 2)).toBe(true);
    expect(m.allSatisfy((_k, v) => v > 0)).toBe(true);
  });
  it("resize", () => {
    const m = new BigInt64Int16HashMap();
    for (let i = 0n; i < 100n; i += 1n) m.put(i, Number(i) * 10);
    expect(m.size()).toBe(100);
  });
  it("memoryBytes", () => {
    const m = new BigInt64Int16HashMap(64);
    expect(m.memoryBytes()).toBeGreaterThan(0);
  });
  it("toString", () => {
    const m = new BigInt64Int16HashMap();
    m.put(1n, 1);
    expect(m.toString()).not.toBe("");
  });
});
