// Code generated by mapdb-codegen. DO NOT EDIT.

const DEFAULT_CAPACITY = 16;
const LOAD_FACTOR = 0.75;

/**
 * Float32→BigInt64 hash map backed by Float32Array and BigInt64Array.
 * Keys: 4 bytes each, values: 8 bytes each.
 * Contiguous memory, no GC pressure on the arrays.
 * Memory: 13 bytes/slot (vs ~50-70 bytes in Map<number, bigint>).
 */
export class Float32BigInt64HashMap {
  private keys: Float32Array;
  private values: BigInt64Array;
  private occupied: Uint8Array;
  private _size = 0;
  private capacity: number;

  constructor(capacity = DEFAULT_CAPACITY) {
    this.capacity = nextPowerOfTwo(capacity);
    this.keys = new Float32Array(this.capacity);
    this.values = new BigInt64Array(this.capacity);
    this.occupied = new Uint8Array(this.capacity);
  }

  put(key: number, value: bigint): bigint | undefined {
    if (this.needsResize()) this.resize();
    const mask = this.capacity - 1;
    let idx = this.hash(key) & mask;
    while (true) {
      if (!this.occupied[idx]) {
        this.keys[idx] = key;
        this.values[idx] = value;
        this.occupied[idx] = 1;
        this._size++;
        return undefined;
      }
      if (Object.is(this.keys[idx], key)) {
        const old = this.values[idx];
        this.values[idx] = value;
        return old;
      }
      idx = (idx + 1) & mask;
    }
  }

  get(key: number): bigint | undefined {
    if (this.capacity === 0) return undefined;
    const mask = this.capacity - 1;
    let idx = this.hash(key) & mask;
    while (true) {
      if (!this.occupied[idx]) return undefined;
      if (Object.is(this.keys[idx], key)) return this.values[idx];
      idx = (idx + 1) & mask;
    }
  }

  getOrDefault(key: number, defaultValue: bigint): bigint {
    const v = this.get(key);
    return v !== undefined ? v : defaultValue;
  }

  remove(key: number): bigint | undefined {
    if (this.capacity === 0) return undefined;
    const mask = this.capacity - 1;
    let idx = this.hash(key) & mask;
    while (true) {
      if (!this.occupied[idx]) return undefined;
      if (Object.is(this.keys[idx], key)) {
        const old = this.values[idx];
        this.occupied[idx] = 0;
        this._size--;
        this.rehashFrom(idx, mask);
        return old;
      }
      idx = (idx + 1) & mask;
    }
  }

  containsKey(key: number): boolean {
    return this.get(key) !== undefined;
  }
  size(): number {
    return this._size;
  }
  isEmpty(): boolean {
    return this._size === 0;
  }

  clear(): void {
    this.occupied.fill(0);
    this._size = 0;
  }

  *entries(): Generator<[number, bigint]> {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) yield [this.keys[i], this.values[i]];
    }
  }

  *keysIter(): Generator<number> {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) yield this.keys[i];
    }
  }

  *valuesIter(): Generator<bigint> {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) yield this.values[i];
    }
  }

  forEach(f: (key: number, value: bigint) => void): void {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) f(this.keys[i], this.values[i]);
    }
  }

  select(
    predicate: (key: number, value: bigint) => boolean,
  ): Float32BigInt64HashMap {
    const result = new Float32BigInt64HashMap();
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && predicate(this.keys[i], this.values[i])) {
        result.put(this.keys[i], this.values[i]);
      }
    }
    return result;
  }

  reject(
    predicate: (key: number, value: bigint) => boolean,
  ): Float32BigInt64HashMap {
    const result = new Float32BigInt64HashMap();
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && !predicate(this.keys[i], this.values[i])) {
        result.put(this.keys[i], this.values[i]);
      }
    }
    return result;
  }

  anySatisfy(predicate: (key: number, value: bigint) => boolean): boolean {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && predicate(this.keys[i], this.values[i]))
        return true;
    }
    return false;
  }

  allSatisfy(predicate: (key: number, value: bigint) => boolean): boolean {
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i] && !predicate(this.keys[i], this.values[i]))
        return false;
    }
    return true;
  }

  injectInto<R>(initial: R, f: (acc: R, key: number, value: bigint) => R): R {
    let result = initial;
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) result = f(result, this.keys[i], this.values[i]);
    }
    return result;
  }

  addToValue(key: number, amount: bigint): bigint {
    const existing = this.get(key);
    const newVal = (
      existing !== undefined ? (((existing as any) + amount) as any) : amount
    ) as bigint;
    this.put(key, newVal);
    return newVal;
  }

  /** Memory stats for this map */
  memoryBytes(): number {
    return this.capacity * (4 + 8 + 1);
  }

  toString(): string {
    const parts: string[] = [];
    for (let i = 0; i < this.capacity; i++) {
      if (this.occupied[i]) parts.push(`${this.keys[i]}: ${this.values[i]}`);
    }
    return `{${parts.join(", ")}}`;
  }

  private hash(key: number): number {
    let h = key | 0;
    h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
    h = (((h >> 16) ^ h) * 0x45d9f3b) | 0;
    return ((h >> 16) ^ h) >>> 0;
  }

  private needsResize(): boolean {
    return this._size + 1 > this.capacity * LOAD_FACTOR;
  }

  private resize(): void {
    const oldKeys = this.keys;
    const oldValues = this.values;
    const oldOccupied = this.occupied;
    const oldCap = this.capacity;
    this.capacity *= 2;
    this.keys = new Float32Array(this.capacity);
    this.values = new BigInt64Array(this.capacity);
    this.occupied = new Uint8Array(this.capacity);
    this._size = 0;
    for (let i = 0; i < oldCap; i++) {
      if (oldOccupied[i]) this.put(oldKeys[i], oldValues[i]);
    }
  }

  private rehashFrom(deleted: number, mask: number): void {
    let idx = (deleted + 1) & mask;
    while (this.occupied[idx]) {
      const ideal = this.hash(this.keys[idx]) & mask;
      const distCurrent = (idx - ideal + this.capacity) & mask;
      const distGap = (deleted - ideal + this.capacity) & mask;
      if (distCurrent > distGap) {
        this.keys[deleted] = this.keys[idx];
        this.values[deleted] = this.values[idx];
        this.occupied[deleted] = 1;
        this.occupied[idx] = 0;
        deleted = idx;
      }
      idx = (idx + 1) & mask;
      if (idx === deleted) break;
    }
  }
}

function nextPowerOfTwo(n: number): number {
  if (n <= 0) return 16;
  n--;
  n |= n >> 1;
  n |= n >> 2;
  n |= n >> 4;
  n |= n >> 8;
  n |= n >> 16;
  n++;
  return n;
}
