// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { Int16BigInt64HashMap } from "./int16-bigint64-hash-map.js";

describe("Int16BigInt64HashMap generated", () => {
  it("put and get", () => {
    const m = new Int16BigInt64HashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    m.put(3, 3n);
    expect(m.get(1)).toBe(1n);
    expect(m.get(99)).toBeUndefined();
    expect(m.size()).toBe(3);
  });
  it("put overwrite", () => {
    const m = new Int16BigInt64HashMap();
    m.put(1, 1n);
    const old = m.put(1, 2n);
    expect(old).toBe(1n);
    expect(m.get(1)).toBe(2n);
  });
  it("remove", () => {
    const m = new Int16BigInt64HashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    expect(m.remove(1)).toBe(1n);
    expect(m.size()).toBe(1);
    expect(m.containsKey(1)).toBe(false);
  });
  it("getOrDefault", () => {
    const m = new Int16BigInt64HashMap();
    m.put(1, 1n);
    expect(m.getOrDefault(1, 3n)).toBe(1n);
    expect(m.getOrDefault(99, 3n)).toBe(3n);
  });
  it("isEmpty and clear", () => {
    const m = new Int16BigInt64HashMap();
    expect(m.isEmpty()).toBe(true);
    m.put(1, 1n);
    expect(m.isEmpty()).toBe(false);
    m.clear();
    expect(m.isEmpty()).toBe(true);
  });
  it("select", () => {
    const m = new Int16BigInt64HashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    m.put(3, 3n);
    expect(m.select((_k, v) => v > 1n).size()).toBe(2);
  });
  it("anySatisfy / allSatisfy", () => {
    const m = new Int16BigInt64HashMap();
    m.put(1, 1n);
    m.put(2, 2n);
    expect(m.anySatisfy((_k, v) => v === 2n)).toBe(true);
    expect(m.allSatisfy((_k, v) => v > 0n)).toBe(true);
  });
  it("resize", () => {
    const m = new Int16BigInt64HashMap();
    for (let i = 0; i < 100; i += 1) m.put(i, BigInt(i) * 10n);
    expect(m.size()).toBe(100);
  });
  it("memoryBytes", () => {
    const m = new Int16BigInt64HashMap(64);
    expect(m.memoryBytes()).toBeGreaterThan(0);
  });
  it("toString", () => {
    const m = new Int16BigInt64HashMap();
    m.put(1, 1n);
    expect(m.toString()).not.toBe("");
  });
});
