// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntNumberPair } from "./bigint-number-pair.js";

describe("BigIntNumberPair generated", () => {
  it("one and two", () => {
    const p = new BigIntNumberPair(1n, 2);
    expect(p.one()).toBe(1n);
    expect(p.two()).toBe(2);
  });
  it("equals", () => {
    const p1 = new BigIntNumberPair(1n, 2);
    const p2 = new BigIntNumberPair(1n, 2);
    const p3 = new BigIntNumberPair(2n, 1);
    expect(p1.equals(p2)).toBe(true);
    expect(p1.equals(p3)).toBe(false);
  });
  it("toString", () => {
    const p = new BigIntNumberPair(1n, 2);
    expect(p.toString()).not.toBe("");
  });
});
