// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberNumberPair } from "./number-number-pair.js";

describe("NumberNumberPair generated", () => {
  it("one and two", () => {
    const p = new NumberNumberPair(1, 2);
    expect(p.one()).toBe(1);
    expect(p.two()).toBe(2);
  });
  it("equals", () => {
    const p1 = new NumberNumberPair(1, 2);
    const p2 = new NumberNumberPair(1, 2);
    const p3 = new NumberNumberPair(2, 1);
    expect(p1.equals(p2)).toBe(true);
    expect(p1.equals(p3)).toBe(false);
  });
  it("toString", () => {
    const p = new NumberNumberPair(1, 2);
    expect(p.toString()).not.toBe("");
  });
});
