// Code generated by mapdb-codegen. DO NOT EDIT.

/**
 * Immutable pair of (number, number) values.
 */
export class NumberNumberPair {
  private readonly _one: number;
  private readonly _two: number;

  constructor(one: number, two: number) {
    this._one = one;
    this._two = two;
  }

  /** Returns the first element. */
  one(): number {
    return this._one;
  }

  /** Returns the second element. */
  two(): number {
    return this._two;
  }

  /** Returns true if both elements are equal to the other pair's elements. */
  equals(other: NumberNumberPair): boolean {
    return this._one === other.one() && this._two === other.two();
  }

  /** Compares this pair to another lexicographically (first by one, then by two). */
  compareTo(other: NumberNumberPair): number {
    const cmp1 = this._one - other.one();
    if (cmp1 !== 0) return cmp1;
    return this._two - other.two();
  }

  /** Returns a string representation. */
  toString(): string {
    return `(${this._one}, ${this._two})`;
  }
}
