// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberBigIntPair } from "./number-bigint-pair.js";

describe("NumberBigIntPair generated", () => {
  it("one and two", () => {
    const p = new NumberBigIntPair(1, 2n);
    expect(p.one()).toBe(1);
    expect(p.two()).toBe(2n);
  });
  it("equals", () => {
    const p1 = new NumberBigIntPair(1, 2n);
    const p2 = new NumberBigIntPair(1, 2n);
    const p3 = new NumberBigIntPair(2, 1n);
    expect(p1.equals(p2)).toBe(true);
    expect(p1.equals(p3)).toBe(false);
  });
  it("toString", () => {
    const p = new NumberBigIntPair(1, 2n);
    expect(p.toString()).not.toBe("");
  });
});
