// Code generated by mapdb-codegen. DO NOT EDIT.

/**
 * A multimap that maps number keys to lists of bigint values.
 * Backed by a JavaScript Map from key to array of values.
 */
export class NumberBigIntListMultimap {
  private _map: Map<number, bigint[]>;
  private _totalSize: number;

  constructor() {
    this._map = new Map<number, bigint[]>();
    this._totalSize = 0;
  }

  /** Creates a new empty multimap. */
  static of(): NumberBigIntListMultimap {
    return new NumberBigIntListMultimap();
  }

  /** Adds a value under the given key. */
  put(key: number, value: bigint): void {
    const list = this._map.get(key);
    if (list !== undefined) {
      list.push(value);
    } else {
      this._map.set(key, [value]);
    }
    this._totalSize++;
  }

  /** Returns the values for the key as a readonly array. Returns an empty array if the key is absent. */
  get(key: number): readonly bigint[] {
    return this._map.get(key) ?? [];
  }

  /** Returns the number of values for the given key. */
  getCount(key: number): number {
    const list = this._map.get(key);
    return list !== undefined ? list.length : 0;
  }

  /** Removes all values for the key and returns them. Returns an empty array if the key is absent. */
  removeAll(key: number): bigint[] {
    const list = this._map.get(key);
    if (list === undefined) {
      return [];
    }
    this._map.delete(key);
    this._totalSize -= list.length;
    return list;
  }

  /** Returns true if the multimap contains the given key. */
  containsKey(key: number): boolean {
    return this._map.has(key);
  }

  /** Returns true if the multimap contains the given key-value pair. */
  containsKeyValue(key: number, value: bigint): boolean {
    const list = this._map.get(key);
    if (list === undefined) return false;
    for (let i = 0; i < list.length; i++) {
      if (list[i] === value) return true;
    }
    return false;
  }

  /** Returns the number of distinct keys. */
  get keysCount(): number {
    return this._map.size;
  }

  /** Returns the total number of values across all keys. */
  get size(): number {
    return this._totalSize;
  }

  /** Returns true if the multimap has no entries. */
  get isEmpty(): boolean {
    return this._totalSize === 0;
  }

  /** Removes all entries. */
  clear(): void {
    this._map.clear();
    this._totalSize = 0;
  }

  /** Calls the function for each key-value pair. */
  forEach(fn: (key: number, value: bigint) => void): void {
    this._map.forEach((list, key) => {
      for (let i = 0; i < list.length; i++) {
        fn(key, list[i]);
      }
    });
  }

  /** Calls the function for each key and its associated list of values. */
  forEachKey(fn: (key: number, values: readonly bigint[]) => void): void {
    this._map.forEach((list, key) => {
      fn(key, list);
    });
  }

  /** Returns a new multimap containing only the key-value pairs that satisfy the predicate. */
  select(
    predicate: (key: number, value: bigint) => boolean,
  ): NumberBigIntListMultimap {
    const result = new NumberBigIntListMultimap();
    this._map.forEach((list, key) => {
      for (let i = 0; i < list.length; i++) {
        if (predicate(key, list[i])) {
          result.put(key, list[i]);
        }
      }
    });
    return result;
  }

  /** Returns a new multimap containing only the key-value pairs that do NOT satisfy the predicate. */
  reject(
    predicate: (key: number, value: bigint) => boolean,
  ): NumberBigIntListMultimap {
    const result = new NumberBigIntListMultimap();
    this._map.forEach((list, key) => {
      for (let i = 0; i < list.length; i++) {
        if (!predicate(key, list[i])) {
          result.put(key, list[i]);
        }
      }
    });
    return result;
  }

  /** Returns an array of all distinct keys. */
  uniqueKeys(): number[] {
    return Array.from(this._map.keys());
  }

  /** Returns an array of all values across all keys. */
  values(): bigint[] {
    const result: bigint[] = [];
    this._map.forEach((list) => {
      for (let i = 0; i < list.length; i++) {
        result.push(list[i]);
      }
    });
    return result;
  }

  /** Returns all key-value pairs as an array of tuples. */
  toArray(): [number, bigint][] {
    const result: [number, bigint][] = [];
    this._map.forEach((list, key) => {
      for (let i = 0; i < list.length; i++) {
        result.push([key, list[i]]);
      }
    });
    return result;
  }

  /** Returns a string representation of the multimap. */
  toString(): string {
    const parts: string[] = [];
    this._map.forEach((list, key) => {
      parts.push(`${key}: [${list.join(", ")}]`);
    });
    return `{${parts.join(", ")}}`;
  }

  /** Returns true if this multimap has the same entries as the other multimap. */
  equals(other: NumberBigIntListMultimap): boolean {
    if (this._totalSize !== other._totalSize) return false;
    if (this._map.size !== other._map.size) return false;
    for (const [key, list] of this._map) {
      const otherList = other._map.get(key);
      if (otherList === undefined) return false;
      if (list.length !== otherList.length) return false;
      for (let i = 0; i < list.length; i++) {
        if (list[i] !== otherList[i]) return false;
      }
    }
    return true;
  }

  /** Yields all key-value pairs as [key, value] tuples. */
  *[Symbol.iterator](): Generator<[number, bigint]> {
    for (const [key, list] of this._map) {
      for (let i = 0; i < list.length; i++) {
        yield [key, list[i]];
      }
    }
  }

  /** Yields all key-value pairs as [key, value] tuples. */
  *entries(): Generator<[number, bigint]> {
    yield* this[Symbol.iterator]();
  }
}
