// Code generated by mapdb-codegen. DO NOT EDIT.

/** Read-only collection of `T` values. The minimal common surface that
 *  every concrete collection in the library satisfies. */
export interface MapDbCollection<T> {
  size(): number;
  isEmpty(): boolean;
  contains(value: T): boolean;

  // ── Array.prototype-style iteration / functional methods ──────────
  /** Calls `f` for each element in the collection. */
  forEach(f: (value: T) => void): void;
  /** Returns a new array with the results of calling `f` on each element. */
  map<U>(f: (value: T) => U): U[];
  /** Returns a new array with elements satisfying the predicate. */
  filter(predicate: (value: T) => boolean): T[];
  /** Returns the first element satisfying the predicate, or undefined. */
  find(predicate: (value: T) => boolean): T | undefined;
  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: T) => boolean): boolean;
  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: T) => boolean): boolean;
  /** Reduces the collection to a single value using the accumulator function. */
  reduce<U>(f: (acc: U, value: T) => U, initial: U): U;
  /** Returns true if the collection contains the value. Alias for `contains`. */
  includes(value: T): boolean;

  // ── Conversion ────────────────────────────────────────────────────
  /** Returns all elements as a plain array. */
  toArray(): T[];

  // ── Iterator protocol ─────────────────────────────────────────────
  /** Makes the collection iterable with for-of loops. */
  [Symbol.iterator](): IterableIterator<T>;
}

/** Mutable collection: any operation that empties the structure. */
export interface MapDbMutableCollection<T> extends MapDbCollection<T> {
  clear(): void;
}

// ── Category interfaces ────────────────────────────────────────────────

/** Read-only ordered list with positional access. */
export interface MapDbList<T> extends MapDbCollection<T> {
  get(index: number): T;
  /** Returns the index of the first occurrence of the value, or -1 if not found. */
  indexOf(value: T): number;
}

/** Mutable ordered list. */
export interface MapDbMutableList<T>
  extends MapDbList<T>, MapDbMutableCollection<T> {
  add(value: T): void;
  set(index: number, value: T): T;
}

/** Read-only set marker (uniqueness implied; no extra methods). */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface MapDbSet<T> extends MapDbCollection<T> {}

/** Mutable set. `add` returns true if the value was newly inserted. */
export interface MapDbMutableSet<T>
  extends MapDbSet<T>, MapDbMutableCollection<T> {
  add(value: T): boolean;
}

/** Read-only multiset (bag) with occurrence counts. */
export interface MapDbBag<T> extends MapDbCollection<T> {
  occurrencesOf(value: T): number;
  sizeDistinct(): number;
}

/** Mutable bag. `add` adds one occurrence of the value. */
export interface MapDbMutableBag<T>
  extends MapDbBag<T>, MapDbMutableCollection<T> {
  add(value: T): void;
}

/** Read-only LIFO stack. `peek` returns the top element. */
export interface MapDbStack<T> extends MapDbCollection<T> {
  peek(): T;
}

/** Mutable LIFO stack. */
export interface MapDbMutableStack<T>
  extends MapDbStack<T>, MapDbMutableCollection<T> {
  push(value: T): void;
  pop(): T;
}

// ── Map interfaces ─────────────────────────────────────────────────────

/** Read-only map from `K` keys to `V` values. */
export interface MapDbMap<K, V> {
  size(): number;
  isEmpty(): boolean;
  containsKey(key: K): boolean;
  get(key: K): V | undefined;
}

/** Mutable map. */
export interface MapDbMutableMap<K, V> extends MapDbMap<K, V> {
  put(key: K, value: V): V | undefined;
  remove(key: K): V | undefined;
  clear(): void;
}
