// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BitSet } from "./bit-set.js";

describe("BitSet generated", () => {
  it("set and get", () => {
    const bs = new BitSet();
    bs.set(0);
    bs.set(5);
    bs.set(10);
    expect(bs.get(0)).toBe(true);
    expect(bs.get(5)).toBe(true);
    expect(bs.get(10)).toBe(true);
    expect(bs.get(1)).toBe(false);
  });

  it("clearBit", () => {
    const bs = new BitSet();
    bs.set(5);
    expect(bs.get(5)).toBe(true);
    bs.clearBit(5);
    expect(bs.get(5)).toBe(false);
  });

  it("flip", () => {
    const bs = new BitSet();
    bs.set(5);
    expect(bs.get(5)).toBe(true);
    bs.flip(5);
    expect(bs.get(5)).toBe(false);
    bs.flip(5);
    expect(bs.get(5)).toBe(true);
  });

  it("empty BitSet", () => {
    const bs = new BitSet();
    expect(bs.isEmpty).toBe(true);
    expect(bs.cardinality).toBe(0);
  });

  it("cardinality", () => {
    const bs = new BitSet();
    bs.set(0);
    bs.set(5);
    bs.set(10);
    expect(bs.cardinality).toBe(3);
  });

  it("length", () => {
    const bs = new BitSet(100);
    expect(bs.length).toBe(100);
    bs.set(150);
    expect(bs.length).toBe(151);
  });

  it("clearAll", () => {
    const bs = new BitSet();
    bs.set(0);
    bs.set(5);
    bs.set(10);
    expect(bs.cardinality).toBe(3);
    bs.clearAll();
    expect(bs.cardinality).toBe(0);
    expect(bs.isEmpty).toBe(true);
  });

  it("intersects", () => {
    const bs1 = new BitSet();
    bs1.set(0);
    bs1.set(5);
    const bs2 = new BitSet();
    bs2.set(5);
    bs2.set(10);
    expect(bs1.intersects(bs2)).toBe(true);
    const bs3 = new BitSet();
    bs3.set(20);
    expect(bs1.intersects(bs3)).toBe(false);
  });

  it("andInPlace", () => {
    const bs1 = new BitSet();
    bs1.set(0);
    bs1.set(5);
    bs1.set(10);
    const bs2 = new BitSet();
    bs2.set(5);
    bs2.set(10);
    bs2.set(15);
    bs1.andInPlace(bs2);
    expect(bs1.cardinality).toBe(2);
    expect(bs1.get(0)).toBe(false);
    expect(bs1.get(5)).toBe(true);
    expect(bs1.get(10)).toBe(true);
  });

  it("orInPlace", () => {
    const bs1 = new BitSet();
    bs1.set(0);
    bs1.set(5);
    const bs2 = new BitSet();
    bs2.set(5);
    bs2.set(10);
    bs1.orInPlace(bs2);
    expect(bs1.cardinality).toBe(3);
    expect(bs1.get(0)).toBe(true);
    expect(bs1.get(5)).toBe(true);
    expect(bs1.get(10)).toBe(true);
  });

  it("xorInPlace", () => {
    const bs1 = new BitSet();
    bs1.set(0);
    bs1.set(5);
    const bs2 = new BitSet();
    bs2.set(5);
    bs2.set(10);
    bs1.xorInPlace(bs2);
    expect(bs1.cardinality).toBe(2);
    expect(bs1.get(0)).toBe(true);
    expect(bs1.get(5)).toBe(false);
    expect(bs1.get(10)).toBe(true);
  });

  it("andNotInPlace", () => {
    const bs1 = new BitSet();
    bs1.set(0);
    bs1.set(5);
    bs1.set(10);
    const bs2 = new BitSet();
    bs2.set(5);
    bs1.andNotInPlace(bs2);
    expect(bs1.cardinality).toBe(2);
    expect(bs1.get(0)).toBe(true);
    expect(bs1.get(5)).toBe(false);
    expect(bs1.get(10)).toBe(true);
  });

  it("nextSetBit", () => {
    const bs = new BitSet();
    bs.set(0);
    bs.set(5);
    bs.set(10);
    expect(bs.nextSetBit(0)).toBe(0);
    expect(bs.nextSetBit(1)).toBe(5);
    expect(bs.nextSetBit(6)).toBe(10);
    expect(bs.nextSetBit(11)).toBe(-1);
  });

  it("toArray", () => {
    const bs = new BitSet();
    bs.set(0);
    bs.set(5);
    bs.set(10);
    expect(bs.toArray()).toEqual([0, 5, 10]);
  });

  it("equals", () => {
    const bs1 = new BitSet();
    bs1.set(0);
    bs1.set(5);
    const bs2 = new BitSet();
    bs2.set(0);
    bs2.set(5);
    const bs3 = new BitSet();
    bs3.set(0);
    expect(bs1.equals(bs2)).toBe(true);
    expect(bs1.equals(bs3)).toBe(false);
  });

  it("toString", () => {
    const bs = new BitSet();
    bs.set(0);
    bs.set(5);
    expect(bs.toString()).toBe("{0, 5}");
  });

  it("large BitSet operations", () => {
    const bs = new BitSet();
    for (let i = 0; i < 1000; i += 2) {
      bs.set(i); // set even bits
    }
    expect(bs.cardinality).toBe(500);
    expect(bs.get(0)).toBe(true);
    expect(bs.get(1)).toBe(false);
    expect(bs.get(999)).toBe(false);
  });
});
