// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BitSet } from "./bit-set.js";
import { ImmutableBitSet } from "./immutable-bit-set.js";

describe("ImmutableBitSet generated", () => {
  it("empty and withBitLength constructors", () => {
    const e = ImmutableBitSet.empty();
    expect(e.isEmpty).toBe(true);
    expect(e.cardinality).toBe(0);
    const p = ImmutableBitSet.withBitLength(64);
    expect(p.cardinality).toBe(0);
  });

  it("get reads bits from source", () => {
    const src = new BitSet();
    src.set(3);
    src.set(65);
    const im = new ImmutableBitSet(src);
    expect(im.get(3)).toBe(true);
    expect(im.get(65)).toBe(true);
    expect(im.get(4)).toBe(false);
    expect(im.cardinality).toBe(2);
  });

  it("set returns new ImmutableBitSet without mutating original", () => {
    const src = new BitSet();
    src.set(1);
    const a = new ImmutableBitSet(src);
    const b = a.set(5);
    expect(a.get(5)).toBe(false);
    expect(b.get(5)).toBe(true);
    expect(b.get(1)).toBe(true);
  });

  it("clearBit returns new ImmutableBitSet", () => {
    const src = new BitSet();
    src.set(1);
    src.set(2);
    const a = new ImmutableBitSet(src);
    const b = a.clearBit(1);
    expect(a.get(1)).toBe(true);
    expect(b.get(1)).toBe(false);
    expect(b.get(2)).toBe(true);
  });

  it("flip toggles bit", () => {
    const src = new BitSet();
    src.set(1);
    const a = new ImmutableBitSet(src);
    const b = a.flip(1).flip(2);
    expect(b.get(1)).toBe(false);
    expect(b.get(2)).toBe(true);
  });

  it("intersects and has", () => {
    const sa = new BitSet();
    sa.set(1);
    sa.set(2);
    const sb = new BitSet();
    sb.set(2);
    sb.set(3);
    const a = new ImmutableBitSet(sa);
    const b = new ImmutableBitSet(sb);
    expect(a.intersects(b)).toBe(true);
    expect(a.has(1)).toBe(true);
    const sc = new BitSet();
    sc.set(100);
    expect(a.intersects(new ImmutableBitSet(sc))).toBe(false);
  });

  it("and/or/xor/andNot", () => {
    const sa = new BitSet();
    sa.set(1);
    sa.set(2);
    sa.set(3);
    const sb = new BitSet();
    sb.set(2);
    sb.set(3);
    sb.set(4);
    const a = new ImmutableBitSet(sa);
    const b = new ImmutableBitSet(sb);
    expect(a.and(b).cardinality).toBe(2);
    expect(a.or(b).cardinality).toBe(4);
    expect(a.xor(b).cardinality).toBe(2);
  });

  it("toArray returns ascending set-bit indices", () => {
    const src = new BitSet();
    src.set(5);
    src.set(0);
    src.set(10);
    const im = new ImmutableBitSet(src);
    expect(im.toArray()).toEqual([0, 5, 10]);
  });
});
