// Code generated by mapdb-codegen. DO NOT EDIT.
import { BitSet } from "./bit-set.js";

/**
 * Immutable bit-packed storage for booleans.
 * Wraps a mutable BitSet, exposing only read-only operations.
 * Set operations return new immutable BitSets.
 */
export class ImmutableBitSet {
  private readonly delegate: BitSet;

  constructor(source: BitSet) {
    // Copy all bits into a fresh mutable BitSet so the caller cannot mutate our data.
    this.delegate = new BitSet(source.length);
    const bits = source.toArray();
    for (const bit of bits) {
      this.delegate.set(bit);
    }
  }

  /** Creates an empty immutable BitSet. */
  static empty(): ImmutableBitSet {
    return new ImmutableBitSet(BitSet.empty());
  }

  /** Creates an immutable BitSet preallocated for `nBits` bits (all zero). */
  static withBitLength(nBits: number): ImmutableBitSet {
    return new ImmutableBitSet(BitSet.withBitLength(nBits));
  }

  /** Returns true if the bit at `index` is 1. Out-of-range returns false. */
  get(bit: number): boolean {
    return this.delegate.get(bit);
  }

  /** Logical bit length (tracks highest bit set + 1, or explicit prealloc). */
  get length(): number {
    return this.delegate.length;
  }

  /** Number of set bits. */
  get cardinality(): number {
    return this.delegate.cardinality;
  }

  /** True if no bits are set. */
  get isEmpty(): boolean {
    return this.delegate.isEmpty;
  }

  /** Returns true if the bit is set. Alias for `get`. */
  has(bit: number): boolean {
    return this.delegate.get(bit);
  }

  /** Returns indices of set bits, ascending. */
  toArray(): number[] {
    return this.delegate.toArray();
  }

  /** Returns a NEW immutable BitSet with the bit at `index` set to 1. */
  set(bit: number): ImmutableBitSet {
    const copy = this.delegate;
    const newSet = new BitSet(copy.length);
    const bits = copy.toArray();
    for (const b of bits) {
      newSet.set(b);
    }
    newSet.set(bit);
    return new ImmutableBitSet(newSet);
  }

  /** Returns a NEW immutable BitSet with the bit at `index` cleared. */
  clearBit(bit: number): ImmutableBitSet {
    const copy = this.delegate;
    const newSet = new BitSet(copy.length);
    const bits = copy.toArray();
    for (const b of bits) {
      newSet.set(b);
    }
    newSet.clearBit(bit);
    return new ImmutableBitSet(newSet);
  }

  /** Returns a NEW immutable BitSet with the bit at `index` flipped. */
  flip(bit: number): ImmutableBitSet {
    const copy = this.delegate;
    const newSet = new BitSet(copy.length);
    const bits = copy.toArray();
    for (const b of bits) {
      newSet.set(b);
    }
    newSet.flip(bit);
    return new ImmutableBitSet(newSet);
  }

  /** Returns true if any bit is set in both `this` and `other`. */
  intersects(other: ImmutableBitSet): boolean {
    return this.delegate.intersects(other.delegate);
  }

  /** Returns a NEW immutable BitSet that is the intersection of `this` and `other`. */
  and(other: ImmutableBitSet): ImmutableBitSet {
    const newSet = new BitSet(
      Math.max(this.delegate.length, other.delegate.length),
    );
    const thisBits = this.delegate.toArray();
    for (const b of thisBits) {
      if (other.delegate.get(b)) {
        newSet.set(b);
      }
    }
    return new ImmutableBitSet(newSet);
  }

  /** Returns a NEW immutable BitSet that is the union of `this` and `other`. */
  or(other: ImmutableBitSet): ImmutableBitSet {
    const newSet = new BitSet(
      Math.max(this.delegate.length, other.delegate.length),
    );
    const thisBits = this.delegate.toArray();
    const otherBits = other.delegate.toArray();
    for (const b of thisBits) {
      newSet.set(b);
    }
    for (const b of otherBits) {
      newSet.set(b);
    }
    return new ImmutableBitSet(newSet);
  }

  /** Returns a NEW immutable BitSet that is the symmetric difference of `this` and `other`. */
  xor(other: ImmutableBitSet): ImmutableBitSet {
    const newSet = new BitSet(
      Math.max(this.delegate.length, other.delegate.length),
    );
    const thisBits = this.delegate.toArray();
    const otherBits = other.delegate.toArray();
    for (const b of thisBits) {
      if (!other.delegate.get(b)) {
        newSet.set(b);
      }
    }
    for (const b of otherBits) {
      if (!this.delegate.get(b)) {
        newSet.set(b);
      }
    }
    return new ImmutableBitSet(newSet);
  }

  /** Returns a NEW immutable BitSet with bits in `other` cleared. */
  andNot(other: ImmutableBitSet): ImmutableBitSet {
    const newSet = new BitSet(this.delegate.length);
    const thisBits = this.delegate.toArray();
    for (const b of thisBits) {
      if (!other.delegate.get(b)) {
        newSet.set(b);
      }
    }
    return new ImmutableBitSet(newSet);
  }

  /** Returns the index of the next set bit at or after `from`, or -1. */
  nextSetBit(from: number): number {
    return this.delegate.nextSetBit(from);
  }

  /** Returns true if both BitSets have the same length and bits. */
  equals(other: ImmutableBitSet): boolean {
    return this.delegate.equals(other.delegate);
  }

  /** Returns a string representation. */
  toString(): string {
    return this.delegate.toString();
  }

  /** Returns a new mutable copy of this BitSet. */
  toMutable(): BitSet {
    const copy = new BitSet(this.delegate.length);
    const bits = this.delegate.toArray();
    for (const bit of bits) {
      copy.set(bit);
    }
    return copy;
  }
}
