// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntTreeSet } from "./bigint-tree-set.js";

describe("BigIntTreeSet generated", () => {
  it("add and contains", () => {
    const s = new BigIntTreeSet();
    s.add(3n);
    s.add(1n);
    s.add(2n);
    expect(s.size()).toBe(3);
    expect(s.contains(2n)).toBe(true);
    expect(s.contains(99n)).toBe(false);
  });
  it("duplicate", () => {
    const s = new BigIntTreeSet();
    expect(s.add(1n)).toBe(true);
    expect(s.add(1n)).toBe(false);
  });
  it("remove", () => {
    const s = new BigIntTreeSet();
    s.add(1n);
    s.add(2n);
    expect(s.remove(1n)).toBe(true);
    expect(s.contains(1n)).toBe(false);
  });
  it("min and max", () => {
    const s = new BigIntTreeSet();
    s.add(3n);
    s.add(1n);
    expect(s.min()).toBe(1n);
    expect(s.max()).toBe(3n);
  });
  it("sorted iteration", () => {
    const s = new BigIntTreeSet();
    s.add(3n);
    s.add(1n);
    s.add(2n);
    const vals = [...s.values()];
    for (let i = 1; i < vals.length; i++) {
      expect(vals[i] >= vals[i - 1]).toBe(true);
    }
  });
  it("clear", () => {
    const s = new BigIntTreeSet();
    s.add(1n);
    s.clear();
    expect(s.isEmpty()).toBe(true);
  });
  it("toString", () => {
    const s = new BigIntTreeSet();
    s.add(1n);
    expect(s.toString()).not.toBe("");
  });
});
