// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbMutableSet } from "../api/index";

const RED = false;
const BLACK = true;

interface TreeNode {
  key: bigint;
  left: TreeNode | null;
  right: TreeNode | null;
  parent: TreeNode | null;
  color: boolean;
}

/** Sorted set of bigint values, backed by a red-black tree. */
export class BigIntTreeSet implements MapDbMutableSet<bigint> {
  private root: TreeNode | null = null;
  private _size = 0;

  static of(values: bigint[]): BigIntTreeSet {
    const s = new BigIntTreeSet();
    for (const v of values) s.add(v);
    return s;
  }

  add(value: bigint): boolean {
    if (this.root === null) {
      this.root = {
        key: value,
        left: null,
        right: null,
        parent: null,
        color: BLACK,
      };
      this._size++;
      return true;
    }
    let node = this.root;
    while (true) {
      if (value < node.key) {
        if (!node.left) {
          node.left = {
            key: value,
            left: null,
            right: null,
            parent: node,
            color: RED,
          };
          this.fixInsert(node.left);
          this._size++;
          return true;
        }
        node = node.left;
      } else if (value > node.key) {
        if (!node.right) {
          node.right = {
            key: value,
            left: null,
            right: null,
            parent: node,
            color: RED,
          };
          this.fixInsert(node.right);
          this._size++;
          return true;
        }
        node = node.right;
      } else {
        return false;
      }
    }
  }

  remove(value: bigint): boolean {
    const node = this.findNode(value);
    if (!node) return false;
    this.deleteNode(node);
    this._size--;
    return true;
  }

  contains(value: bigint): boolean {
    return this.findNode(value) !== null;
  }
  size(): number {
    return this._size;
  }
  isEmpty(): boolean {
    return this._size === 0;
  }
  clear(): void {
    this.root = null;
    this._size = 0;
  }

  min(): bigint | undefined {
    if (!this.root) return undefined;
    let n = this.root;
    while (n.left) n = n.left;
    return n.key;
  }

  max(): bigint | undefined {
    if (!this.root) return undefined;
    let n = this.root;
    while (n.right) n = n.right;
    return n.key;
  }

  floor(value: bigint): bigint | undefined {
    let result: TreeNode | null = null;
    let node = this.root;
    while (node) {
      if (value === node.key) return node.key;
      if (value > node.key) {
        result = node;
        node = node.right;
      } else {
        node = node.left;
      }
    }
    return result?.key;
  }

  ceiling(value: bigint): bigint | undefined {
    let result: TreeNode | null = null;
    let node = this.root;
    while (node) {
      if (value === node.key) return node.key;
      if (value < node.key) {
        result = node;
        node = node.left;
      } else {
        node = node.right;
      }
    }
    return result?.key;
  }

  *values(): Generator<bigint> {
    function* inorder(node: TreeNode | null): Generator<bigint> {
      if (!node) return;
      yield* inorder(node.left);
      yield node.key;
      yield* inorder(node.right);
    }
    yield* inorder(this.root);
  }

  *rangeValues(from: bigint, to: bigint): Generator<bigint> {
    for (const v of this.values()) {
      if (v < from) continue;
      if (v >= to) return;
      yield v;
    }
  }

  forEach(f: (value: bigint) => void): void {
    for (const v of this.values()) f(v);
  }

  /** Returns a new array with the results of calling `f` on each element (in ascending order). */
  map<U>(f: (value: bigint) => U): U[] {
    const result: U[] = [];
    for (const v of this.values()) result.push(f(v));
    return result;
  }

  /** Returns a new array with elements satisfying the predicate (in ascending order). */
  filter(predicate: (value: bigint) => boolean): bigint[] {
    const result: bigint[] = [];
    for (const v of this.values()) if (predicate(v)) result.push(v);
    return result;
  }

  /** Returns the first (smallest) element satisfying the predicate, or undefined. */
  find(predicate: (value: bigint) => boolean): bigint | undefined {
    for (const v of this.values()) if (predicate(v)) return v;
    return undefined;
  }

  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: bigint) => boolean): boolean {
    for (const v of this.values()) if (!predicate(v)) return false;
    return true;
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: bigint) => boolean): boolean {
    for (const v of this.values()) if (predicate(v)) return true;
    return false;
  }

  /** Reduces the set to a single value using the accumulator function (in ascending order). */
  reduce<U>(f: (acc: U, value: bigint) => U, initial: U): U {
    let acc = initial;
    for (const v of this.values()) acc = f(acc, v);
    return acc;
  }

  /** Returns true if the set contains the value. Alias for `contains`. */
  includes(value: bigint): boolean {
    return this.contains(value);
  }

  /** Makes the set iterable with for-of loops. Yields elements in ascending order. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    yield* this.values();
  }

  select(pred: (v: bigint) => boolean): BigIntTreeSet {
    const r = new BigIntTreeSet();
    for (const v of this.values()) if (pred(v)) r.add(v);
    return r;
  }

  union(other: BigIntTreeSet): BigIntTreeSet {
    const r = new BigIntTreeSet();
    for (const v of this.values()) r.add(v);
    for (const v of other.values()) r.add(v);
    return r;
  }

  intersect(other: BigIntTreeSet): BigIntTreeSet {
    const r = new BigIntTreeSet();
    for (const v of this.values()) if (other.contains(v)) r.add(v);
    return r;
  }

  difference(other: BigIntTreeSet): BigIntTreeSet {
    const r = new BigIntTreeSet();
    for (const v of this.values()) if (!other.contains(v)) r.add(v);
    return r;
  }

  toArray(): bigint[] {
    return [...this.values()];
  }

  toString(): string {
    const parts: string[] = [];
    for (const v of this.values()) parts.push(`${v}`);
    return `{${parts.join(", ")}}`;
  }

  // --- RB tree internals ---
  private findNode(key: bigint): TreeNode | null {
    let n = this.root;
    while (n) {
      if (key < n.key) n = n.left;
      else if (key > n.key) n = n.right;
      else return n;
    }
    return null;
  }
  private rotateLeft(x: TreeNode): void {
    const y = x.right!;
    x.right = y.left;
    if (y.left) y.left.parent = x;
    y.parent = x.parent;
    if (!x.parent) this.root = y;
    else if (x === x.parent.left) x.parent.left = y;
    else x.parent.right = y;
    y.left = x;
    x.parent = y;
  }
  private rotateRight(x: TreeNode): void {
    const y = x.left!;
    x.left = y.right;
    if (y.right) y.right.parent = x;
    y.parent = x.parent;
    if (!x.parent) this.root = y;
    else if (x === x.parent.right) x.parent.right = y;
    else x.parent.left = y;
    y.right = x;
    x.parent = y;
  }
  private fixInsert(z: TreeNode): void {
    while (z.parent && z.parent.color === RED) {
      if (z.parent === z.parent.parent!.left) {
        const y = z.parent.parent!.right;
        if (y && y.color === RED) {
          z.parent.color = BLACK;
          y.color = BLACK;
          z.parent.parent!.color = RED;
          z = z.parent.parent!;
        } else {
          if (z === z.parent.right) {
            z = z.parent;
            this.rotateLeft(z);
          }
          z.parent!.color = BLACK;
          z.parent!.parent!.color = RED;
          this.rotateRight(z.parent!.parent!);
        }
      } else {
        const y = z.parent.parent!.left;
        if (y && y.color === RED) {
          z.parent.color = BLACK;
          y.color = BLACK;
          z.parent.parent!.color = RED;
          z = z.parent.parent!;
        } else {
          if (z === z.parent.left) {
            z = z.parent;
            this.rotateRight(z);
          }
          z.parent!.color = BLACK;
          z.parent!.parent!.color = RED;
          this.rotateLeft(z.parent!.parent!);
        }
      }
    }
    this.root!.color = BLACK;
  }
  private deleteNode(z: TreeNode): void {
    if (z.left && z.right) {
      let s = z.right;
      while (s.left) s = s.left;
      z.key = s.key;
      z = s;
    }
    const child = z.left ?? z.right;
    if (child) {
      child.parent = z.parent;
      if (!z.parent) this.root = child;
      else if (z === z.parent.left) z.parent.left = child;
      else z.parent.right = child;
      if (z.color === BLACK) this.fixDelete(child);
    } else if (!z.parent) {
      this.root = null;
    } else {
      if (z.color === BLACK) this.fixDelete(z);
      if (z.parent) {
        if (z === z.parent.left) z.parent.left = null;
        else z.parent.right = null;
      }
    }
  }
  private fixDelete(x: TreeNode): void {
    while (x !== this.root && x.color === BLACK) {
      if (x === x.parent!.left) {
        let w = x.parent!.right;
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (w.color === RED) {
          w.color = BLACK;
          x.parent!.color = RED;
          this.rotateLeft(x.parent!);
          w = x.parent!.right;
        }
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (
          (!w.left || w.left.color === BLACK) &&
          (!w.right || w.right.color === BLACK)
        ) {
          w.color = RED;
          x = x.parent!;
        } else {
          if (!w.right || w.right.color === BLACK) {
            if (w.left) w.left.color = BLACK;
            w.color = RED;
            this.rotateRight(w);
            w = x.parent!.right!;
          }
          w.color = x.parent!.color;
          x.parent!.color = BLACK;
          if (w.right) w.right.color = BLACK;
          this.rotateLeft(x.parent!);
          x = this.root!;
        }
      } else {
        let w = x.parent!.left;
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (w.color === RED) {
          w.color = BLACK;
          x.parent!.color = RED;
          this.rotateRight(x.parent!);
          w = x.parent!.left;
        }
        if (!w) {
          x = x.parent!;
          continue;
        }
        if (
          (!w.left || w.left.color === BLACK) &&
          (!w.right || w.right.color === BLACK)
        ) {
          w.color = RED;
          x = x.parent!;
        } else {
          if (!w.left || w.left.color === BLACK) {
            if (w.right) w.right.color = BLACK;
            w.color = RED;
            this.rotateLeft(w);
            w = x.parent!.left!;
          }
          w.color = x.parent!.color;
          x.parent!.color = BLACK;
          if (w.left) w.left.color = BLACK;
          this.rotateRight(x.parent!);
          x = this.root!;
        }
      }
    }
    x.color = BLACK;
  }
}
