// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntArrayList } from "./bigint-array-list.js";

describe("BigIntArrayList generated", () => {
  it("add and get", () => {
    const l = new BigIntArrayList();
    l.add(1n);
    l.add(2n);
    l.add(3n);
    expect(l.size()).toBe(3);
    expect(l.get(0)).toBe(1n);
    expect(l.get(2)).toBe(3n);
  });

  it("of", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n]);
    expect(l.size()).toBe(3);
    expect(l.get(1)).toBe(2n);
  });

  it("set", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n]);
    const old = l.set(1, 4n);
    expect(old).toBe(2n);
    expect(l.get(1)).toBe(4n);
  });

  it("removeAtIndex", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n]);
    const removed = l.removeAtIndex(1);
    expect(removed).toBe(2n);
    expect(l.size()).toBe(2);
  });

  it("contains", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n]);
    expect(l.contains(2n)).toBe(true);
    expect(l.contains(99n)).toBe(false);
  });

  it("indexOf", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n]);
    expect(l.indexOf(2n)).toBe(1);
    expect(l.indexOf(99n)).toBe(-1);
  });

  it("isEmpty and clear", () => {
    const l = new BigIntArrayList();
    expect(l.isEmpty()).toBe(true);
    l.add(1n);
    expect(l.isEmpty()).toBe(false);
    l.clear();
    expect(l.size()).toBe(0);
    expect(l.isEmpty()).toBe(true);
  });

  it("select and reject", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n, 4n, 5n]);
    expect(l.select((v) => v > 3n).size()).toBe(2);
    expect(l.reject((v) => v > 3n).size()).toBe(3);
  });

  it("detect", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n]);
    expect(l.detect((v) => v === 2n)).toBe(2n);
    expect(l.detect((v) => v === 99n)).toBeUndefined();
  });

  it("anySatisfy / allSatisfy", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n]);
    expect(l.anySatisfy((v) => v === 2n)).toBe(true);
    expect(l.anySatisfy((v) => v === 99n)).toBe(false);
    expect(l.allSatisfy((v) => v > 0n)).toBe(true);
  });

  it("count", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n, 4n, 5n]);
    expect(l.count((v) => v > 3n)).toBe(2);
  });

  it("sum, min, max", () => {
    const l = BigIntArrayList.of([3n, 1n, 2n]);
    expect(l.sum()).toBe(6n);
    expect(l.min()).toBe(1n);
    expect(l.max()).toBe(3n);
  });

  it("sort", () => {
    const l = BigIntArrayList.of([3n, 1n, 2n]);
    l.sort();
    expect(l.toArray()).toEqual([1n, 2n, 3n]);
  });

  it("entries generator", () => {
    const l = BigIntArrayList.of([1n, 2n]);
    const values = [...l.entries()];
    expect(values).toEqual([1n, 2n]);
  });

  it("toArray", () => {
    const l = BigIntArrayList.of([1n, 2n, 3n]);
    expect(l.toArray()).toEqual([1n, 2n, 3n]);
  });

  it("toString", () => {
    const l = BigIntArrayList.of([1n]);
    expect(l.toString()).not.toBe("");
  });

  it("resize", () => {
    const l = new BigIntArrayList();
    for (let i = 0n; i < 100n; i += 1n) l.add(i);
    expect(l.size()).toBe(100);
  });
});
