// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbMutableList } from "../api/index";

const DEFAULT_CAPACITY = 16;

/**
 * Resizable array list holding bigint values.
 */
export class BigIntArrayList implements MapDbMutableList<bigint> {
  private data: bigint[];
  private _size: number;

  constructor(capacity: number = DEFAULT_CAPACITY) {
    this.data = new Array<bigint>(capacity).fill(0n);
    this._size = 0;
  }

  /** Creates a new list from an array of values. */
  static of(values: bigint[]): BigIntArrayList {
    const list = new BigIntArrayList(values.length);
    for (const v of values) {
      list.add(v);
    }
    return list;
  }

  /** Appends a value to the end of the list. */
  add(value: bigint): void {
    this.ensureCapacity(this._size + 1);
    this.data[this._size] = value;
    this._size++;
  }

  /** Returns the value at the given index. Throws if out of bounds. */
  get(index: number): bigint {
    this.checkBounds(index);
    return this.data[index];
  }

  /** Sets the value at the given index. Throws if out of bounds. Returns the old value. */
  set(index: number, value: bigint): bigint {
    this.checkBounds(index);
    const old = this.data[index];
    this.data[index] = value;
    return old;
  }

  /** Removes the element at the given index and shifts subsequent elements left. Returns the removed value. */
  removeAtIndex(index: number): bigint {
    this.checkBounds(index);
    const old = this.data[index];
    for (let i = index; i < this._size - 1; i++) {
      this.data[i] = this.data[i + 1];
    }
    this._size--;
    this.data[this._size] = 0n;
    return old;
  }

  /** Returns true if the list contains the given value. */
  contains(value: bigint): boolean {
    for (let i = 0; i < this._size; i++) {
      if (Object.is(this.data[i], value)) return true;
    }
    return false;
  }

  /** Returns the index of the first occurrence of the value, or -1 if not found. */
  indexOf(value: bigint): number {
    for (let i = 0; i < this._size; i++) {
      if (Object.is(this.data[i], value)) return i;
    }
    return -1;
  }

  /** Returns the number of elements. */
  size(): number {
    return this._size;
  }

  /** Returns true if the list is empty. */
  isEmpty(): boolean {
    return this._size === 0;
  }

  /** Removes all elements. */
  clear(): void {
    this.data.fill(0n);
    this._size = 0;
  }

  /** Sorts the list in ascending order in place. */
  sort(): void {
    const view = this.data.slice(0, this._size);
    view.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
    for (let i = 0; i < this._size; i++) {
      this.data[i] = view[i];
    }
  }

  /** Returns a new list with elements satisfying the predicate. */
  select(predicate: (value: bigint) => boolean): BigIntArrayList {
    const result = new BigIntArrayList();
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) {
        result.add(this.data[i]);
      }
    }
    return result;
  }

  /** Returns a new list with elements NOT satisfying the predicate. */
  reject(predicate: (value: bigint) => boolean): BigIntArrayList {
    const result = new BigIntArrayList();
    for (let i = 0; i < this._size; i++) {
      if (!predicate(this.data[i])) {
        result.add(this.data[i]);
      }
    }
    return result;
  }

  /** Returns the first element satisfying the predicate, or undefined. */
  detect(predicate: (value: bigint) => boolean): bigint | undefined {
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) return this.data[i];
    }
    return undefined;
  }

  /** Returns true if any element satisfies the predicate. */
  anySatisfy(predicate: (value: bigint) => boolean): boolean {
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) return true;
    }
    return false;
  }

  /** Returns true if all elements satisfy the predicate. */
  allSatisfy(predicate: (value: bigint) => boolean): boolean {
    for (let i = 0; i < this._size; i++) {
      if (!predicate(this.data[i])) return false;
    }
    return true;
  }

  /** Returns the number of elements satisfying the predicate. */
  count(predicate: (value: bigint) => boolean): number {
    let c = 0;
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) c++;
    }
    return c;
  }

  /** Returns the sum of all elements. */
  sum(): bigint {
    let s: bigint = 0n;
    for (let i = 0; i < this._size; i++) {
      s += this.data[i];
    }
    return s;
  }

  /** Returns the minimum element, or undefined if empty. */
  min(): bigint | undefined {
    if (this._size === 0) return undefined;
    let m = this.data[0];
    for (let i = 1; i < this._size; i++) {
      if (this.data[i] < m) m = this.data[i];
    }
    return m;
  }

  /** Returns the maximum element, or undefined if empty. */
  max(): bigint | undefined {
    if (this._size === 0) return undefined;
    let m = this.data[0];
    for (let i = 1; i < this._size; i++) {
      if (this.data[i] > m) m = this.data[i];
    }
    return m;
  }

  /** Returns the elements as a plain array. */
  toArray(): bigint[] {
    return this.data.slice(0, this._size);
  }

  /** Calls the function for each element. */
  forEach(f: (value: bigint, index: number) => void): void {
    for (let i = 0; i < this._size; i++) {
      f(this.data[i], i);
    }
  }

  /** Returns a new array with the results of calling `f` on each element. */
  map<U>(f: (value: bigint) => U): U[] {
    const result: U[] = [];
    for (let i = 0; i < this._size; i++) {
      result.push(f(this.data[i]));
    }
    return result;
  }

  /** Returns a new array with elements satisfying the predicate. */
  filter(predicate: (value: bigint) => boolean): bigint[] {
    const result: bigint[] = [];
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) result.push(this.data[i]);
    }
    return result;
  }

  /** Returns the first element satisfying the predicate, or undefined. Alias for `detect`. */
  find(predicate: (value: bigint) => boolean): bigint | undefined {
    return this.detect(predicate);
  }

  /** Returns true if every element satisfies the predicate. Alias for `allSatisfy`. */
  every(predicate: (value: bigint) => boolean): boolean {
    return this.allSatisfy(predicate);
  }

  /** Returns true if at least one element satisfies the predicate. Alias for `anySatisfy`. */
  some(predicate: (value: bigint) => boolean): boolean {
    return this.anySatisfy(predicate);
  }

  /** Reduces the list to a single value using the accumulator function. */
  reduce<U>(f: (acc: U, value: bigint) => U, initial: U): U {
    let acc = initial;
    for (let i = 0; i < this._size; i++) {
      acc = f(acc, this.data[i]);
    }
    return acc;
  }

  /** Returns true if the list contains the value. Alias for `contains`. */
  includes(value: bigint): boolean {
    return this.contains(value);
  }

  /** Makes the list iterable with for-of loops. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    for (let i = 0; i < this._size; i++) {
      yield this.data[i];
    }
  }

  /** Yields all elements in order. */
  *entries(): Generator<bigint> {
    for (let i = 0; i < this._size; i++) {
      yield this.data[i];
    }
  }

  /** Returns a string representation. */
  toString(): string {
    const parts: string[] = [];
    for (let i = 0; i < this._size; i++) {
      parts.push(`${this.data[i]}`);
    }
    return `[${parts.join(", ")}]`;
  }

  private checkBounds(index: number): void {
    if (index < 0 || index >= this._size) {
      throw new RangeError(
        `Index ${index} out of bounds for size ${this._size}`,
      );
    }
  }

  private ensureCapacity(minCapacity: number): void {
    if (minCapacity > this.data.length) {
      const newCap = Math.max(this.data.length * 2, minCapacity);
      const newData = new Array<bigint>(newCap).fill(0n);
      for (let i = 0; i < this._size; i++) {
        newData[i] = this.data[i];
      }
      this.data = newData;
    }
  }
}
