// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntArrayList } from "./bigint-array-list.js";
import { ImmutableBigIntArrayList } from "./immutable-bigint-array-list.js";

describe("ImmutableBigIntArrayList generated", () => {
  it("get and size", () => {
    const im = ImmutableBigIntArrayList.of([1n, 2n, 3n]);
    expect(im.size()).toBe(3);
    expect(im.get(1)).toBe(2n);
  });
  it("contains", () => {
    const im = ImmutableBigIntArrayList.of([1n, 2n]);
    expect(im.contains(1n)).toBe(true);
    expect(im.contains(99n)).toBe(false);
  });
  it("select and reject", () => {
    const im = ImmutableBigIntArrayList.of([1n, 2n, 3n, 4n, 5n]);
    expect(im.select((v) => v > 3n).size()).toBe(2);
    expect(im.reject((v) => v > 3n).size()).toBe(3);
  });
  it("toArray", () => {
    const im = ImmutableBigIntArrayList.of([1n, 2n]);
    expect(im.toArray()).toEqual([1n, 2n]);
  });
  it("toMutable does not affect immutable", () => {
    const im = ImmutableBigIntArrayList.of([1n]);
    const m = im.toMutable();
    m.add(2n);
    expect(im.size()).toBe(1);
  });
  it("toString", () => {
    const im = ImmutableBigIntArrayList.of([1n]);
    expect(im.toString()).not.toBe("");
  });
});
