// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntHashBag } from "./bigint-hash-bag.js";

describe("BigIntHashBag generated", () => {
  it("add and occurrences", () => {
    const b = new BigIntHashBag();
    b.add(1n);
    b.add(1n);
    b.add(2n);
    expect(b.occurrencesOf(1n)).toBe(2);
    expect(b.occurrencesOf(2n)).toBe(1);
    expect(b.size()).toBe(3);
    expect(b.sizeDistinct()).toBe(2);
  });
  it("of", () => {
    const b = BigIntHashBag.of([1n, 1n, 2n]);
    expect(b.size()).toBe(3);
  });
  it("remove", () => {
    const b = BigIntHashBag.of([1n, 1n, 1n, 2n]);
    b.remove(1n);
    expect(b.occurrencesOf(1n)).toBe(2);
  });
  it("removeAll", () => {
    const b = BigIntHashBag.of([1n, 1n, 2n]);
    b.removeAll(1n);
    expect(b.contains(1n)).toBe(false);
  });
  it("clear and isEmpty", () => {
    const b = BigIntHashBag.of([1n]);
    b.clear();
    expect(b.isEmpty()).toBe(true);
  });
  it("forEachWithOccurrences", () => {
    const b = BigIntHashBag.of([1n, 1n, 2n, 2n, 2n]);
    let total = 0;
    b.forEachWithOccurrences((_v, c) => {
      total += c;
    });
    expect(total).toBe(5);
  });
  it("select", () => {
    const b = BigIntHashBag.of([1n, 2n, 3n]);
    expect(b.select((v) => v > 1n).size()).toBe(2);
  });
  it("entries generator", () => {
    const b = BigIntHashBag.of([1n, 1n, 2n]);
    expect([...b.entries()].length).toBe(2);
  });
  it("toString", () => {
    const b = BigIntHashBag.of([1n]);
    expect(b.toString()).not.toBe("");
  });
});
