// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbBag } from "../api/index";
import { BigIntHashBag } from "./bigint-hash-bag.js";

/**
 * Immutable hash bag (multiset) for bigint values.
 * Wraps a mutable BigIntHashBag, exposing only read-only operations.
 */
export class ImmutableBigIntHashBag implements MapDbBag<bigint> {
  private readonly delegate: BigIntHashBag;

  constructor(source: BigIntHashBag) {
    // Copy all entries into a fresh mutable bag so the caller cannot mutate our data.
    this.delegate = new BigIntHashBag();
    for (const [value, count] of source.entries()) {
      this.delegate.addOccurrences(value, count);
    }
  }

  /** Creates an immutable bag from an array of values. */
  static of(values: bigint[]): ImmutableBigIntHashBag {
    return new ImmutableBigIntHashBag(BigIntHashBag.of(values));
  }

  /** Returns the number of occurrences of the value. */
  occurrencesOf(value: bigint): number {
    return this.delegate.occurrencesOf(value);
  }

  /** Returns true if the bag contains at least one occurrence of the value. */
  contains(value: bigint): boolean {
    return this.delegate.contains(value);
  }

  /** Returns the total number of elements (including duplicates). */
  size(): number {
    return this.delegate.size();
  }

  /** Returns the number of distinct elements. */
  sizeDistinct(): number {
    return this.delegate.sizeDistinct();
  }

  /** Returns true if the bag is empty. */
  isEmpty(): boolean {
    return this.delegate.isEmpty();
  }

  /** Yields all distinct elements with their occurrence counts as [value, count] tuples. */
  *entries(): Generator<[bigint, number]> {
    yield* this.delegate.entries();
  }

  /** Calls the function for each element (including duplicates). */
  forEach(f: (value: bigint) => void): void {
    this.delegate.forEach(f);
  }

  /** Returns a new array with the results of calling `f` on each element (including duplicates). */
  map<U>(f: (value: bigint) => U): U[] {
    return this.delegate.map(f);
  }

  /** Returns a new array with elements satisfying the predicate (including duplicates). */
  filter(predicate: (value: bigint) => boolean): bigint[] {
    return this.delegate.filter(predicate);
  }

  /** Returns the first element satisfying the predicate, or undefined. */
  find(predicate: (value: bigint) => boolean): bigint | undefined {
    return this.delegate.find(predicate);
  }

  /** Returns true if every distinct element satisfies the predicate. */
  every(predicate: (value: bigint) => boolean): boolean {
    return this.delegate.every(predicate);
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: bigint) => boolean): boolean {
    return this.delegate.some(predicate);
  }

  /** Reduces the bag to a single value using the accumulator function (including duplicates). */
  reduce<U>(f: (acc: U, value: bigint) => U, initial: U): U {
    return this.delegate.reduce(f, initial);
  }

  /** Returns true if the bag contains the value. Alias for `contains`. */
  includes(value: bigint): boolean {
    return this.delegate.includes(value);
  }

  /** Makes the bag iterable with for-of loops. Yields all elements including duplicates. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    yield* this.delegate[Symbol.iterator]();
  }

  /** Calls the function for each distinct element with its occurrence count. */
  forEachWithOccurrences(
    f: (value: bigint, occurrences: number) => void,
  ): void {
    this.delegate.forEachWithOccurrences(f);
  }

  /** Returns a new immutable bag with elements satisfying the predicate. */
  select(predicate: (value: bigint) => boolean): ImmutableBigIntHashBag {
    return new ImmutableBigIntHashBag(this.delegate.select(predicate));
  }

  /** Returns a new immutable bag with elements NOT satisfying the predicate. */
  reject(predicate: (value: bigint) => boolean): ImmutableBigIntHashBag {
    return new ImmutableBigIntHashBag(this.delegate.reject(predicate));
  }

  /** Returns all elements (including duplicates) as a plain array. */
  toArray(): bigint[] {
    return this.delegate.toArray();
  }

  /** Returns a new mutable copy of this bag. */
  toMutable(): BigIntHashBag {
    const m = new BigIntHashBag();
    for (const [value, count] of this.delegate.entries()) {
      m.addOccurrences(value, count);
    }
    return m;
  }

  /** Returns a string representation. */
  toString(): string {
    return this.delegate.toString();
  }
}
