// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberHashBag } from "./number-hash-bag.js";

describe("NumberHashBag generated", () => {
  it("add and occurrences", () => {
    const b = new NumberHashBag();
    b.add(1);
    b.add(1);
    b.add(2);
    expect(b.occurrencesOf(1)).toBe(2);
    expect(b.occurrencesOf(2)).toBe(1);
    expect(b.size()).toBe(3);
    expect(b.sizeDistinct()).toBe(2);
  });
  it("of", () => {
    const b = NumberHashBag.of([1, 1, 2]);
    expect(b.size()).toBe(3);
  });
  it("remove", () => {
    const b = NumberHashBag.of([1, 1, 1, 2]);
    b.remove(1);
    expect(b.occurrencesOf(1)).toBe(2);
  });
  it("removeAll", () => {
    const b = NumberHashBag.of([1, 1, 2]);
    b.removeAll(1);
    expect(b.contains(1)).toBe(false);
  });
  it("clear and isEmpty", () => {
    const b = NumberHashBag.of([1]);
    b.clear();
    expect(b.isEmpty()).toBe(true);
  });
  it("forEachWithOccurrences", () => {
    const b = NumberHashBag.of([1, 1, 2, 2, 2]);
    let total = 0;
    b.forEachWithOccurrences((_v, c) => {
      total += c;
    });
    expect(total).toBe(5);
  });
  it("select", () => {
    const b = NumberHashBag.of([1, 2, 3]);
    expect(b.select((v) => v > 1).size()).toBe(2);
  });
  it("entries generator", () => {
    const b = NumberHashBag.of([1, 1, 2]);
    expect([...b.entries()].length).toBe(2);
  });
  it("toString", () => {
    const b = NumberHashBag.of([1]);
    expect(b.toString()).not.toBe("");
  });
});
