// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { BigIntInterval } from "./bigint-interval.js";

describe("BigIntInterval generated", () => {
  it("fromTo ascending", () => {
    const iv = BigIntInterval.fromTo(1n, 5n);
    expect(iv.size()).toBe(5);
    expect(iv.toArray()).toEqual([1n, 2n, 3n, 4n, 5n]);
  });
  it("fromTo descending", () => {
    const iv = BigIntInterval.fromTo(5n, 1n);
    expect(iv.size()).toBe(5);
    expect(iv.toArray()).toEqual([5n, 4n, 3n, 2n, 1n]);
  });
  it("fromToBy", () => {
    const iv = BigIntInterval.fromToBy(
      1n as bigint,
      5n as bigint,
      2n as bigint,
    );
    expect(iv.toArray()).toEqual([1n, 3n as bigint, 5n as bigint]);
  });
  it("single element", () => {
    const iv = BigIntInterval.fromTo(3n, 3n);
    expect(iv.size()).toBe(1);
    expect(iv.toArray()).toEqual([3n]);
  });
  it("contains", () => {
    const iv = BigIntInterval.fromTo(1n, 5n);
    expect(iv.contains(1n)).toBe(true);
    expect(iv.contains(3n)).toBe(true);
    expect(iv.contains(99n)).toBe(false);
  });
  it("get", () => {
    const iv = BigIntInterval.fromTo(1n, 5n);
    expect(iv.get(0)).toBe(1n);
    expect(iv.get(4)).toBe(5n);
    expect(() => iv.get(5)).toThrow();
  });
  it("reversed", () => {
    const iv = BigIntInterval.fromTo(1n, 5n);
    expect(iv.reversed().toArray()).toEqual([5n, 4n, 3n, 2n, 1n]);
  });
  it("oneTo", () => {
    const iv = BigIntInterval.oneTo(3n);
    expect(iv.toArray()).toEqual([1n, 2n, 3n]);
  });
  it("zeroTo", () => {
    const iv = BigIntInterval.zeroTo(3n);
    expect(iv.toArray()).toEqual([0n, 1n, 2n, 3n]);
  });
  it("isEmpty", () => {
    expect(BigIntInterval.fromTo(1n, 5n).isEmpty()).toBe(false);
  });
  it("forEach", () => {
    const iv = BigIntInterval.fromTo(1n, 3n);
    let sum = 0n;
    iv.forEach((v) => {
      sum = (sum + v) as bigint;
    });
    expect(sum).toBe(6n);
  });
  it("every and some", () => {
    const iv = BigIntInterval.fromTo(1n, 5n);
    expect(iv.every((v) => v > 0n)).toBe(true);
    expect(iv.some((v) => v === 3n)).toBe(true);
    expect(iv.some((v) => v === 99n)).toBe(false);
  });
  it("map and filter", () => {
    const iv = BigIntInterval.fromTo(1n, 3n);
    expect(iv.map((v) => v)).toEqual([1n, 2n, 3n]);
    expect(iv.filter((v) => v > 1n)).toEqual([2n, 3n]);
  });
  it("find", () => {
    const iv = BigIntInterval.fromTo(1n, 5n);
    expect(iv.find((v) => v === 3n)).toBe(3n);
    expect(iv.find((v) => v === 99n)).toBeUndefined();
  });
  it("Symbol.iterator", () => {
    const iv = BigIntInterval.fromTo(1n, 3n);
    expect([...iv]).toEqual([1n, 2n, 3n]);
  });
  it("zero step throws", () => {
    expect(() => BigIntInterval.fromToBy(1n, 5n, 0n)).toThrow();
  });
  it("toString", () => {
    const iv = BigIntInterval.fromTo(1n, 3n);
    expect(iv.toString()).toContain("BigIntInterval");
  });
});
