// Code generated by mapdb-codegen. DO NOT EDIT.

/**
 * A virtual collection representing a range of bigint values [from, to] with
 * a given step. No elements are materialised in memory — iteration computes
 * values on the fly.
 */
export class BigIntInterval {
  private readonly _from: bigint;
  private readonly _to: bigint;
  private readonly _step: bigint;

  private constructor(from: bigint, to: bigint, step: bigint) {
    this._from = from;
    this._to = to;
    this._step = step;
  }

  /** Creates an interval from `from` to `to` (inclusive) with the given step. */
  static fromToBy(from: bigint, to: bigint, step: bigint): BigIntInterval {
    if (step === 0n) throw new Error("BigIntInterval: step must not be zero");
    if (from < to && step < 0n)
      throw new Error("BigIntInterval: step must be positive when from < to");
    if (from > to && step > 0n)
      throw new Error("BigIntInterval: step must be negative when from > to");
    return new BigIntInterval(from, to, step);
  }

  /** Creates an interval from `from` to `to` (inclusive) with step 1 or -1. */
  static fromTo(from: bigint, to: bigint): BigIntInterval {
    const step: bigint = from <= to ? 1n : (-1n as bigint);
    return new BigIntInterval(from, to, step);
  }

  /** Creates an interval from 1 to `to` (inclusive). */
  static oneTo(to: bigint): BigIntInterval {
    return BigIntInterval.fromTo(1n as bigint, to);
  }

  /** Creates an interval from 0 to `to` (inclusive). */
  static zeroTo(to: bigint): BigIntInterval {
    return BigIntInterval.fromTo(0n, to);
  }

  /** Returns the start of the interval. */
  from(): bigint {
    return this._from;
  }

  /** Returns the end of the interval (inclusive). */
  to(): bigint {
    return this._to;
  }

  /** Returns the step. */
  step(): bigint {
    return this._step;
  }

  /** Returns the number of elements. */
  size(): number {
    if (
      (this._step > 0n && this._from > this._to) ||
      (this._step < 0n && this._from < this._to)
    ) {
      return 0;
    }
    return Number((this._to - this._from) / this._step) + 1;
  }

  /** Returns true if the interval is empty. */
  isEmpty(): boolean {
    return this.size() === 0;
  }

  /** Returns true if the interval contains the given value. */
  contains(value: bigint): boolean {
    if (this._step > 0n) {
      return (
        value >= this._from &&
        value <= this._to &&
        (value - this._from) % this._step === 0n
      );
    }
    return (
      value <= this._from &&
      value >= this._to &&
      (this._from - value) % (-this._step as bigint) === 0n
    );
  }

  /** Returns the element at the given index, or throws if out of bounds. */
  get(index: number): bigint {
    if (index < 0 || index >= this.size()) {
      throw new RangeError(
        `${index} out of bounds for interval size ${this.size()}`,
      );
    }
    return this._from + this._step * (BigInt(index) as bigint);
  }

  /** Calls the function for each element in order. */
  forEach(f: (value: bigint) => void): void {
    for (const v of this) {
      f(v);
    }
  }

  /** Returns a new array with the results of calling `f` on each element. */
  map<U>(f: (value: bigint) => U): U[] {
    const result: U[] = [];
    for (const v of this) {
      result.push(f(v));
    }
    return result;
  }

  /** Returns elements satisfying the predicate as an array. */
  filter(predicate: (value: bigint) => boolean): bigint[] {
    const result: bigint[] = [];
    for (const v of this) {
      if (predicate(v)) result.push(v);
    }
    return result;
  }

  /** Returns the first element satisfying the predicate, or undefined. */
  find(predicate: (value: bigint) => boolean): bigint | undefined {
    for (const v of this) {
      if (predicate(v)) return v;
    }
    return undefined;
  }

  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: bigint) => boolean): boolean {
    for (const v of this) {
      if (!predicate(v)) return false;
    }
    return true;
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: bigint) => boolean): boolean {
    for (const v of this) {
      if (predicate(v)) return true;
    }
    return false;
  }

  /** Reduces to a single value using the accumulator function. */
  reduce<U>(f: (acc: U, value: bigint) => U, initial: U): U {
    let acc = initial;
    for (const v of this) {
      acc = f(acc, v);
    }
    return acc;
  }

  /** Alias for `contains`. */
  includes(value: bigint): boolean {
    return this.contains(value);
  }

  /** Returns all elements as an array. */
  toArray(): bigint[] {
    const result: bigint[] = [];
    for (const v of this) {
      result.push(v);
    }
    return result;
  }

  /** Makes the interval iterable with for-of loops. */
  *[Symbol.iterator](): IterableIterator<bigint> {
    let current = this._from;
    if (this._step > 0n) {
      while (current <= this._to) {
        yield current;
        current = (current + this._step) as bigint;
      }
    } else {
      while (current >= this._to) {
        yield current;
        current = (current + this._step) as bigint;
      }
    }
  }

  /** Returns a new interval with elements in reverse order. */
  reversed(): BigIntInterval {
    return new BigIntInterval(this._to, this._from, -this._step as bigint);
  }

  toString(): string {
    return `BigIntInterval(${this._from}, ${this._to}, step ${this._step})`;
  }
}
