// Code generated by mapdb-codegen. DO NOT EDIT.

/**
 * A virtual collection representing a range of number values [from, to] with
 * a given step. No elements are materialised in memory — iteration computes
 * values on the fly.
 */
export class NumberInterval {
  private readonly _from: number;
  private readonly _to: number;
  private readonly _step: number;

  private constructor(from: number, to: number, step: number) {
    this._from = from;
    this._to = to;
    this._step = step;
  }

  /** Creates an interval from `from` to `to` (inclusive) with the given step. */
  static fromToBy(from: number, to: number, step: number): NumberInterval {
    if (step === 0) throw new Error("NumberInterval: step must not be zero");
    if (from < to && step < 0)
      throw new Error("NumberInterval: step must be positive when from < to");
    if (from > to && step > 0)
      throw new Error("NumberInterval: step must be negative when from > to");
    return new NumberInterval(from, to, step);
  }

  /** Creates an interval from `from` to `to` (inclusive) with step 1 or -1. */
  static fromTo(from: number, to: number): NumberInterval {
    const step: number = from <= to ? 1 : (-1 as number);
    return new NumberInterval(from, to, step);
  }

  /** Creates an interval from 1 to `to` (inclusive). */
  static oneTo(to: number): NumberInterval {
    return NumberInterval.fromTo(1 as number, to);
  }

  /** Creates an interval from 0 to `to` (inclusive). */
  static zeroTo(to: number): NumberInterval {
    return NumberInterval.fromTo(0, to);
  }

  /** Returns the start of the interval. */
  from(): number {
    return this._from;
  }

  /** Returns the end of the interval (inclusive). */
  to(): number {
    return this._to;
  }

  /** Returns the step. */
  step(): number {
    return this._step;
  }

  /** Returns the number of elements. */
  size(): number {
    if (
      (this._step > 0 && this._from > this._to) ||
      (this._step < 0 && this._from < this._to)
    ) {
      return 0;
    }
    return Number((this._to - this._from) / this._step) + 1;
  }

  /** Returns true if the interval is empty. */
  isEmpty(): boolean {
    return this.size() === 0;
  }

  /** Returns true if the interval contains the given value. */
  contains(value: number): boolean {
    if (this._step > 0) {
      return (
        value >= this._from &&
        value <= this._to &&
        (value - this._from) % this._step === 0
      );
    }
    return (
      value <= this._from &&
      value >= this._to &&
      (this._from - value) % (-this._step as number) === 0
    );
  }

  /** Returns the element at the given index, or throws if out of bounds. */
  get(index: number): number {
    if (index < 0 || index >= this.size()) {
      throw new RangeError(
        `${index} out of bounds for interval size ${this.size()}`,
      );
    }
    return this._from + this._step * (index as number);
  }

  /** Calls the function for each element in order. */
  forEach(f: (value: number) => void): void {
    for (const v of this) {
      f(v);
    }
  }

  /** Returns a new array with the results of calling `f` on each element. */
  map<U>(f: (value: number) => U): U[] {
    const result: U[] = [];
    for (const v of this) {
      result.push(f(v));
    }
    return result;
  }

  /** Returns elements satisfying the predicate as an array. */
  filter(predicate: (value: number) => boolean): number[] {
    const result: number[] = [];
    for (const v of this) {
      if (predicate(v)) result.push(v);
    }
    return result;
  }

  /** Returns the first element satisfying the predicate, or undefined. */
  find(predicate: (value: number) => boolean): number | undefined {
    for (const v of this) {
      if (predicate(v)) return v;
    }
    return undefined;
  }

  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: number) => boolean): boolean {
    for (const v of this) {
      if (!predicate(v)) return false;
    }
    return true;
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: number) => boolean): boolean {
    for (const v of this) {
      if (predicate(v)) return true;
    }
    return false;
  }

  /** Reduces to a single value using the accumulator function. */
  reduce<U>(f: (acc: U, value: number) => U, initial: U): U {
    let acc = initial;
    for (const v of this) {
      acc = f(acc, v);
    }
    return acc;
  }

  /** Alias for `contains`. */
  includes(value: number): boolean {
    return this.contains(value);
  }

  /** Returns all elements as an array. */
  toArray(): number[] {
    const result: number[] = [];
    for (const v of this) {
      result.push(v);
    }
    return result;
  }

  /** Makes the interval iterable with for-of loops. */
  *[Symbol.iterator](): IterableIterator<number> {
    let current = this._from;
    if (this._step > 0) {
      while (current <= this._to) {
        yield current;
        current = (current + this._step) as number;
      }
    } else {
      while (current >= this._to) {
        yield current;
        current = (current + this._step) as number;
      }
    }
  }

  /** Returns a new interval with elements in reverse order. */
  reversed(): NumberInterval {
    return new NumberInterval(this._to, this._from, -this._step as number);
  }

  toString(): string {
    return `NumberInterval(${this._from}, ${this._to}, step ${this._step})`;
  }
}
