// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberInterval } from "./number-interval.js";

describe("NumberInterval generated", () => {
  it("fromTo ascending", () => {
    const iv = NumberInterval.fromTo(1, 5);
    expect(iv.size()).toBe(5);
    expect(iv.toArray()).toEqual([1, 2, 3, 4, 5]);
  });
  it("fromTo descending", () => {
    const iv = NumberInterval.fromTo(5, 1);
    expect(iv.size()).toBe(5);
    expect(iv.toArray()).toEqual([5, 4, 3, 2, 1]);
  });
  it("fromToBy", () => {
    const iv = NumberInterval.fromToBy(1, 5, 2);
    expect(iv.toArray()).toEqual([1, 3, 5]);
  });
  it("single element", () => {
    const iv = NumberInterval.fromTo(3, 3);
    expect(iv.size()).toBe(1);
    expect(iv.toArray()).toEqual([3]);
  });
  it("contains", () => {
    const iv = NumberInterval.fromTo(1, 5);
    expect(iv.contains(1)).toBe(true);
    expect(iv.contains(3)).toBe(true);
    expect(iv.contains(99)).toBe(false);
  });
  it("get", () => {
    const iv = NumberInterval.fromTo(1, 5);
    expect(iv.get(0)).toBe(1);
    expect(iv.get(4)).toBe(5);
    expect(() => iv.get(5)).toThrow();
  });
  it("reversed", () => {
    const iv = NumberInterval.fromTo(1, 5);
    expect(iv.reversed().toArray()).toEqual([5, 4, 3, 2, 1]);
  });
  it("oneTo", () => {
    const iv = NumberInterval.oneTo(3);
    expect(iv.toArray()).toEqual([1, 2, 3]);
  });
  it("zeroTo", () => {
    const iv = NumberInterval.zeroTo(3);
    expect(iv.toArray()).toEqual([0, 1, 2, 3]);
  });
  it("isEmpty", () => {
    expect(NumberInterval.fromTo(1, 5).isEmpty()).toBe(false);
  });
  it("forEach", () => {
    const iv = NumberInterval.fromTo(1, 3);
    let sum = 0;
    iv.forEach((v) => {
      sum = sum + v;
    });
    expect(sum).toBe(6);
  });
  it("every and some", () => {
    const iv = NumberInterval.fromTo(1, 5);
    expect(iv.every((v) => v > 0)).toBe(true);
    expect(iv.some((v) => v === 3)).toBe(true);
    expect(iv.some((v) => v === 99)).toBe(false);
  });
  it("map and filter", () => {
    const iv = NumberInterval.fromTo(1, 3);
    expect(iv.map((v) => v)).toEqual([1, 2, 3]);
    expect(iv.filter((v) => v > 1)).toEqual([2, 3]);
  });
  it("find", () => {
    const iv = NumberInterval.fromTo(1, 5);
    expect(iv.find((v) => v === 3)).toBe(3);
    expect(iv.find((v) => v === 99)).toBeUndefined();
  });
  it("Symbol.iterator", () => {
    const iv = NumberInterval.fromTo(1, 3);
    expect([...iv]).toEqual([1, 2, 3]);
  });
  it("zero step throws", () => {
    expect(() => NumberInterval.fromToBy(1, 5, 0)).toThrow();
  });
  it("toString", () => {
    const iv = NumberInterval.fromTo(1, 3);
    expect(iv.toString()).toContain("NumberInterval");
  });
});
