// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbStack } from "../api/index";
import { NumberArrayStack } from "./number-array-stack.js";

/**
 * Immutable array-backed stack for number values (LIFO).
 * Wraps a mutable NumberArrayStack, exposing only read-only operations.
 * Persistent operations (push, pop) return new immutable stacks.
 */
export class ImmutableNumberArrayStack implements MapDbStack<number> {
  private readonly delegate: NumberArrayStack;

  constructor(source: NumberArrayStack) {
    // Copy all entries into a fresh mutable stack so the caller cannot mutate our data.
    this.delegate = new NumberArrayStack(source.size());
    const arr = source.toArray();
    // toArray returns top-first, so push in reverse order to preserve stack order.
    for (let i = arr.length - 1; i >= 0; i--) {
      this.delegate.push(arr[i]);
    }
  }

  /** Creates an immutable stack from an array of values. The last element becomes the top. */
  static of(values: number[]): ImmutableNumberArrayStack {
    return new ImmutableNumberArrayStack(NumberArrayStack.of(values));
  }

  /** Returns the top element without removing it. Throws if empty. */
  peek(): number {
    return this.delegate.peek();
  }

  /** Returns the element at the given distance from the top (0 = top). Throws if out of bounds. */
  peekAt(index: number): number {
    return this.delegate.peekAt(index);
  }

  /** Returns the number of elements. */
  size(): number {
    return this.delegate.size();
  }

  /** Returns true if the stack is empty. */
  isEmpty(): boolean {
    return this.delegate.isEmpty();
  }

  /** Returns true if the stack contains the given value. */
  contains(value: number): boolean {
    return this.delegate.contains(value);
  }

  /** Yields all values from top to bottom. */
  *values(): Generator<number> {
    yield* this.delegate.values();
  }

  /** Calls the function for each element from top to bottom. */
  forEach(f: (value: number) => void): void {
    this.delegate.forEach(f);
  }

  /** Returns a new array with the results of calling `f` on each element (top to bottom). */
  map<U>(f: (value: number) => U): U[] {
    return this.delegate.map(f);
  }

  /** Returns a new array with elements satisfying the predicate (top to bottom). */
  filter(predicate: (value: number) => boolean): number[] {
    return this.delegate.filter(predicate);
  }

  /** Returns the first element (from top) satisfying the predicate, or undefined. */
  find(predicate: (value: number) => boolean): number | undefined {
    return this.delegate.find(predicate);
  }

  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: number) => boolean): boolean {
    return this.delegate.every(predicate);
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: number) => boolean): boolean {
    return this.delegate.some(predicate);
  }

  /** Reduces the stack to a single value using the accumulator function (top to bottom). */
  reduce<U>(f: (acc: U, value: number) => U, initial: U): U {
    return this.delegate.reduce(f, initial);
  }

  /** Returns true if the stack contains the value. Alias for `contains`. */
  includes(value: number): boolean {
    return this.delegate.includes(value);
  }

  /** Makes the stack iterable with for-of loops. Yields top to bottom. */
  *[Symbol.iterator](): IterableIterator<number> {
    yield* this.delegate[Symbol.iterator]();
  }

  /** Returns a new immutable stack with elements satisfying the predicate (order preserved). */
  select(predicate: (value: number) => boolean): ImmutableNumberArrayStack {
    return new ImmutableNumberArrayStack(this.delegate.select(predicate));
  }

  /** Returns a new immutable stack with elements NOT satisfying the predicate (order preserved). */
  reject(predicate: (value: number) => boolean): ImmutableNumberArrayStack {
    return new ImmutableNumberArrayStack(this.delegate.reject(predicate));
  }

  /** Returns a NEW immutable stack with the value pushed on top. */
  push(value: number): ImmutableNumberArrayStack {
    const copy = this.toMutable();
    copy.push(value);
    return new ImmutableNumberArrayStack(copy);
  }

  /** Returns a tuple [newStack, poppedValue] with the top element removed. Throws if empty. */
  pop(): [ImmutableNumberArrayStack, number] {
    const copy = this.toMutable();
    const value = copy.pop();
    return [new ImmutableNumberArrayStack(copy), value];
  }

  /** Returns all elements as an array (top element first). */
  toArray(): number[] {
    return this.delegate.toArray();
  }

  /** Returns a new mutable copy of this stack. */
  toMutable(): NumberArrayStack {
    const m = new NumberArrayStack(this.delegate.size());
    const arr = this.delegate.toArray();
    // toArray returns top-first, so push in reverse order to preserve stack order.
    for (let i = arr.length - 1; i >= 0; i--) {
      m.push(arr[i]);
    }
    return m;
  }

  /** Returns a string representation (top element first). */
  toString(): string {
    return this.delegate.toString();
  }
}
