// Code generated by mapdb-codegen. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { NumberArrayStack } from "./number-array-stack.js";

describe("NumberArrayStack generated", () => {
  it("push, peek, pop", () => {
    const s = new NumberArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    expect(s.size()).toBe(3);
    expect(s.peek()).toBe(3);
    expect(s.pop()).toBe(3);
    expect(s.size()).toBe(2);
  });
  it("LIFO order", () => {
    const s = new NumberArrayStack();
    s.push(1);
    s.push(2);
    s.push(3);
    expect(s.pop()).toBe(3);
    expect(s.pop()).toBe(2);
    expect(s.pop()).toBe(1);
  });
  it("isEmpty and clear", () => {
    const s = new NumberArrayStack();
    expect(s.isEmpty()).toBe(true);
    s.push(1);
    expect(s.isEmpty()).toBe(false);
    s.clear();
    expect(s.isEmpty()).toBe(true);
  });
  it("contains", () => {
    const s = new NumberArrayStack();
    s.push(1);
    s.push(2);
    expect(s.contains(1)).toBe(true);
    expect(s.contains(3)).toBe(false);
  });
  it("values generator", () => {
    const s = new NumberArrayStack();
    s.push(1);
    s.push(2);
    expect([...s.values()].length).toBe(2);
  });
  it("toArray", () => {
    const s = new NumberArrayStack();
    s.push(1);
    s.push(2);
    expect(s.toArray().length).toBe(2);
  });
  it("forEach", () => {
    const s = new NumberArrayStack();
    s.push(1);
    s.push(2);
    let count = 0;
    s.forEach(() => count++);
    expect(count).toBe(2);
  });
  it("toString", () => {
    const s = new NumberArrayStack();
    s.push(1);
    expect(s.toString()).not.toBe("");
  });
});
