// Code generated by mapdb-codegen. DO NOT EDIT.
import type { MapDbMutableStack } from "../api/index";

const DEFAULT_CAPACITY = 16;

/**
 * Array-backed stack for number values (LIFO).
 */
export class NumberArrayStack implements MapDbMutableStack<number> {
  private data: number[];
  private _size: number;

  constructor(capacity: number = DEFAULT_CAPACITY) {
    this.data = new Array<number>(capacity).fill(0);
    this._size = 0;
  }

  /** Creates a new stack from an array of values. The last element becomes the top. */
  static of(values: number[]): NumberArrayStack {
    const stack = new NumberArrayStack(values.length);
    for (const v of values) {
      stack.push(v);
    }
    return stack;
  }

  /** Pushes a value onto the top of the stack. */
  push(value: number): void {
    this.ensureCapacity(this._size + 1);
    this.data[this._size] = value;
    this._size++;
  }

  /** Removes and returns the top element. Throws if empty. */
  pop(): number {
    if (this._size === 0) {
      throw new Error("Stack is empty");
    }
    this._size--;
    const value = this.data[this._size];
    this.data[this._size] = 0;
    return value;
  }

  /** Returns the top element without removing it. Throws if empty. */
  peek(): number {
    if (this._size === 0) {
      throw new Error("Stack is empty");
    }
    return this.data[this._size - 1];
  }

  /** Returns the element at the given distance from the top (0 = top). Throws if out of bounds. */
  peekAt(index: number): number {
    if (index < 0 || index >= this._size) {
      throw new RangeError(
        `Index ${index} out of bounds for stack size ${this._size}`,
      );
    }
    return this.data[this._size - 1 - index];
  }

  /** Returns the number of elements. */
  size(): number {
    return this._size;
  }

  /** Returns true if the stack is empty. */
  isEmpty(): boolean {
    return this._size === 0;
  }

  /** Removes all elements. */
  clear(): void {
    this.data.fill(0);
    this._size = 0;
  }

  /** Returns true if the stack contains the given value. */
  contains(value: number): boolean {
    for (let i = 0; i < this._size; i++) {
      if (Object.is(this.data[i], value)) return true;
    }
    return false;
  }

  /** Returns a new stack with elements satisfying the predicate (order preserved). */
  select(predicate: (value: number) => boolean): NumberArrayStack {
    const result = new NumberArrayStack();
    for (let i = 0; i < this._size; i++) {
      if (predicate(this.data[i])) {
        result.push(this.data[i]);
      }
    }
    return result;
  }

  /** Returns a new stack with elements NOT satisfying the predicate (order preserved). */
  reject(predicate: (value: number) => boolean): NumberArrayStack {
    const result = new NumberArrayStack();
    for (let i = 0; i < this._size; i++) {
      if (!predicate(this.data[i])) {
        result.push(this.data[i]);
      }
    }
    return result;
  }

  /** Calls the function for each element from top to bottom. */
  forEach(f: (value: number) => void): void {
    for (let i = this._size - 1; i >= 0; i--) {
      f(this.data[i]);
    }
  }

  /** Returns a new array with the results of calling `f` on each element (top to bottom). */
  map<U>(f: (value: number) => U): U[] {
    const result: U[] = [];
    for (let i = this._size - 1; i >= 0; i--) {
      result.push(f(this.data[i]));
    }
    return result;
  }

  /** Returns a new array with elements satisfying the predicate (top to bottom). */
  filter(predicate: (value: number) => boolean): number[] {
    const result: number[] = [];
    for (let i = this._size - 1; i >= 0; i--) {
      if (predicate(this.data[i])) result.push(this.data[i]);
    }
    return result;
  }

  /** Returns the first element (from top) satisfying the predicate, or undefined. */
  find(predicate: (value: number) => boolean): number | undefined {
    for (let i = this._size - 1; i >= 0; i--) {
      if (predicate(this.data[i])) return this.data[i];
    }
    return undefined;
  }

  /** Returns true if every element satisfies the predicate. */
  every(predicate: (value: number) => boolean): boolean {
    for (let i = this._size - 1; i >= 0; i--) {
      if (!predicate(this.data[i])) return false;
    }
    return true;
  }

  /** Returns true if at least one element satisfies the predicate. */
  some(predicate: (value: number) => boolean): boolean {
    for (let i = this._size - 1; i >= 0; i--) {
      if (predicate(this.data[i])) return true;
    }
    return false;
  }

  /** Reduces the stack to a single value using the accumulator function (top to bottom). */
  reduce<U>(f: (acc: U, value: number) => U, initial: U): U {
    let acc = initial;
    for (let i = this._size - 1; i >= 0; i--) {
      acc = f(acc, this.data[i]);
    }
    return acc;
  }

  /** Returns true if the stack contains the value. Alias for `contains`. */
  includes(value: number): boolean {
    return this.contains(value);
  }

  /** Makes the stack iterable with for-of loops. Yields top to bottom. */
  *[Symbol.iterator](): IterableIterator<number> {
    for (let i = this._size - 1; i >= 0; i--) {
      yield this.data[i];
    }
  }

  /** Yields all values from top to bottom. */
  *values(): Generator<number> {
    for (let i = this._size - 1; i >= 0; i--) {
      yield this.data[i];
    }
  }

  /** Returns all elements as an array (top element first). */
  toArray(): number[] {
    const result: number[] = [];
    for (let i = this._size - 1; i >= 0; i--) {
      result.push(this.data[i]);
    }
    return result;
  }

  /** Returns a string representation (top element first). */
  toString(): string {
    const parts: string[] = [];
    for (let i = this._size - 1; i >= 0; i--) {
      parts.push(`${this.data[i]}`);
    }
    return `[${parts.join(", ")}]`;
  }

  private ensureCapacity(minCapacity: number): void {
    if (minCapacity > this.data.length) {
      const newCap = Math.max(this.data.length * 2, minCapacity);
      const newData = new Array<number>(newCap).fill(0);
      for (let i = 0; i < this._size; i++) {
        newData[i] = this.data[i];
      }
      this.data = newData;
    }
  }
}
